<a target="_blank" href="https://colab.research.google.com/github/cns-iu/hra-vccf-cell-distance-visualizations/blob/main/us5-data-processing-cifar-peter-zandstra.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from pprint import pprint

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [96]:
INPUT_DATA_PATH = "/u/yashjain/hubmap-htan-ct-ann-mx/cifar-data/original-data/peter-zandstra-data"
OUTPUT_DATA_PATH = "/u/yashjain/hubmap-htan-ct-ann-mx/cifar-data/processed-data/peter-zandstra-data"
CDN_PATH = "/u/yashjain/vitessce-files/cifar-data/peter-zandstra-data"

In [3]:
# Print names of all files in input data path.
pprint("Files in input data path:")
pprint(os.listdir(INPUT_DATA_PATH))

'Files in input data path:'
['MultiRun-CombinedData.csv',
 'MultiRun-CombinedDataT087.csv',
 'MultiRun-CombinedDataT098 2.csv',
 'MultiRun-CombinedDataT098.csv',
 'MultiRun-CombinedData 2.csv',
 'MultiRun-CombinedDataT096.csv',
 'MultiRun-CombinedDataT097.csv',
 'MultiRun-CombinedDataT100.csv']

In [4]:
# Read all csv files in input data path as separate dataframes.
df_list = []
for filename in os.listdir(INPUT_DATA_PATH):
    if filename.endswith('.csv'):
        df = pd.read_csv(os.path.join(INPUT_DATA_PATH, filename))
        df_list.append(df)

In [5]:
# Print the number of dataframes read.
print(f"Number of dataframes read: {len(df_list)}")

Number of dataframes read: 8

In [6]:
# Print the first few rows of each dataframe.
i=0
print(f"Dataframe {os.listdir(INPUT_DATA_PATH)[i]}:")
df_list[i].head()

Dataframe MultiRun-CombinedData.csv:

,CellID,RunID,RegionID,RegCellID,cell_id:cell_id,region:region,tile_num:tile_num,x:x,y:y,z:z,x_tile:x_tile,y_tile:y_tile,size:size,interior:interior,border:border,cyc001_ch001:DAPI-01,cyc001_ch002:Blank,cyc001_ch003:Blank,cyc001_ch004:Blank,cyc002_ch001:DAPI-02,cyc002_ch002:CD45,"cyc002_ch003:HLA-A,B,C",cyc002_ch004:HES4,cyc003_ch001:DAPI-03,cyc003_ch002:Cytokeratin 5/8,cyc003_ch003:SATB1,cyc003_ch004:FOXP3,cyc004_ch001:DAPI-04,cyc004_ch002:CD19,cyc004_ch003:JAG2,cyc004_ch004:CD326,cyc005_ch001:DAPI-05,cyc005_ch002:SMA,cyc005_ch003:CD86,cyc005_ch004:CD45RA,cyc006_ch001:DAPI-06,cyc006_ch002:CD11b,cyc006_ch003:TCRgd,cyc006_ch004:PDGFRa,cyc007_ch001:DAPI-07,cyc007_ch002:CD5,cyc007_ch003:CD274,cyc007_ch004:CD38,cyc008_ch001:DAPI-08,cyc008_ch002:CD54,cyc008_ch003:CD31,cyc008_ch004:CD44,cyc009_ch001:DAPI-09,cyc009_ch002:CD3,cyc009_ch003:CD279,cyc009_ch004:Vimentin,cyc010_ch001:DAPI-10,cyc010_ch002:CD11c,cyc010_ch003:COL4,cyc010_ch004:Ki67,cyc011_ch001:DAPI-11,cyc011_ch002:CD7,cyc011_ch003:CD4,cyc011_ch004:CD47,cyc012_ch001:DAPI-12,cyc012_ch002:DLL1,cyc012_ch003:ERTR7,cyc012_ch004:Laminin,cyc013_ch001:DAPI-13,cyc013_ch002:CD1a,cyc013_ch003:CD8a,cyc013_ch004:CD197,cyc014_ch001:DAPI-14,cyc014_ch002:CD68,cyc014_ch003:VCAM,cyc014_ch004:MCAM,cyc015_ch001:DAPI-15,cyc015_ch002:CD29,cyc015_ch003:CD45RO,cyc015_ch004:IgM,cyc016_ch001:DAPI-16,cyc016_ch002:Empty,cyc016_ch003:DLL4,cyc016_ch004:Fibronectin,cyc017_ch001:DAPI-17,"cyc017_ch002:HLA-DR,DP,DQ",cyc017_ch003:CD40,cyc017_ch004:CD62L,cyc018_ch001:DAPI-18,cyc018_ch002:Empty,cyc018_ch003:JAG1,cyc018_ch004:15-PGDH,cyc019_ch001:DAPI-19,cyc019_ch002:Blank,cyc019_ch003:Blank,cyc019_ch004:Blank,cyc020_ch001:DAPI-20,cyc020_ch002:WGA,cyc020_ch003:Empty,cyc020_ch004:DRAQ5,cyc001_ch001:DAPI-01_interior,cyc001_ch002:Blank_interior,cyc001_ch003:Blank_interior,cyc001_ch004:Blank_interior,cyc002_ch001:DAPI-02_interior,cyc002_ch002:CD45_interior,"cyc002_ch003:HLA-A,B,C_interior",cyc002_ch004:HES4_interior,cyc003_ch001:DAPI-03_interior,cyc003_ch002:Cytokeratin 5/8_interior,cyc003_ch003:SATB1_interior,cyc003_ch004:FOXP3_interior,cyc004_ch001:DAPI-04_interior,cyc004_ch002:CD19_interior,cyc004_ch003:JAG2_interior,cyc004_ch004:CD326_interior,cyc005_ch001:DAPI-05_interior,cyc005_ch002:SMA_interior,cyc005_ch003:CD86_interior,cyc005_ch004:CD45RA_interior,cyc006_ch001:DAPI-06_interior,cyc006_ch002:CD11b_interior,cyc006_ch003:TCRgd_interior,cyc006_ch004:PDGFRa_interior,cyc007_ch001:DAPI-07_interior,cyc007_ch002:CD5_interior,cyc007_ch003:CD274_interior,cyc007_ch004:CD38_interior,cyc008_ch001:DAPI-08_interior,cyc008_ch002:CD54_interior,cyc008_ch003:CD31_interior,cyc008_ch004:CD44_interior,cyc009_ch001:DAPI-09_interior,cyc009_ch002:CD3_interior,cyc009_ch003:CD279_interior,cyc009_ch004:Vimentin_interior,cyc010_ch001:DAPI-10_interior,cyc010_ch002:CD11c_interior,cyc010_ch003:COL4_interior,cyc010_ch004:Ki67_interior,cyc011_ch001:DAPI-11_interior,cyc011_ch002:CD7_interior,cyc011_ch003:CD4_interior,cyc011_ch004:CD47_interior,cyc012_ch001:DAPI-12_interior,cyc012_ch002:DLL1_interior,cyc012_ch003:ERTR7_interior,cyc012_ch004:Laminin_interior,cyc013_ch001:DAPI-13_interior,cyc013_ch002:CD1a_interior,cyc013_ch003:CD8a_interior,cyc013_ch004:CD197_interior,cyc014_ch001:DAPI-14_interior,cyc014_ch002:CD68_interior,cyc014_ch003:VCAM_interior,cyc014_ch004:MCAM_interior,cyc015_ch001:DAPI-15_interior,cyc015_ch002:CD29_interior,cyc015_ch003:CD45RO_interior,cyc015_ch004:IgM_interior,cyc016_ch001:DAPI-16_interior,cyc016_ch002:Empty_interior,cyc016_ch003:DLL4_interior,cyc016_ch004:Fibronectin_interior,cyc017_ch001:DAPI-17_interior,"cyc017_ch002:HLA-DR,DP,DQ_interior",cyc017_ch003:CD40_interior,cyc017_ch004:CD62L_interior,cyc018_ch001:DAPI-18_interior,cyc018_ch002:Empty_interior,cyc018_ch003:JAG1_interior,cyc018_ch004:15-PGDH_interior,cyc019_ch001:DAPI-19_interior,cyc019_ch002:Blank_interior,cyc019_ch003:Blank_interior,cyc019_ch004:Blank_interior,cyc020_ch001:DAPI-20_interior,cyc020_ch002:WGA_interior,cyc020_ch003:Empty_interior,cyc020_ch004:DRAQ5_interior,cyc001_ch001:DAPI-01_border,cyc001_ch002:Blank_border,cyc001_ch003:Blank_border,cyc001_ch004:Blank_border,cyc002_ch001:DAPI-02_border,cyc002_ch002:CD45_border,"cyc002_ch003:HLA-A,B,C_border",cyc002_ch004:HES4_border,cyc003_ch001:DAPI-03_border,cyc003_ch002:Cytokeratin 5/8_border,cyc003_ch003:SATB1_border,cyc003_ch004:FOXP3_border,cyc004_ch001:DAPI-04_border,cyc004_ch002:CD19_border,cyc004_ch003:JAG2_border,cyc004_ch004:CD326_border,cyc005_ch001:DAPI-05_border,cyc005_ch002:SMA_border,cyc005_ch003:CD86_border,cyc005_ch004:CD45RA_border,cyc006_ch001:DAPI-06_border,cyc006_ch002:CD11b_border,cyc006_ch003:TCRgd_border,cyc006_ch004:PDGFRa_border,cyc007_ch001:DAPI-07_border,cyc007_ch002:CD5_border,cyc007_ch003:CD274_border,cyc007_ch004:CD38_border,cyc008_ch001:DAPI-08_border,cyc008_ch002:CD54_border,cyc008_ch003:CD31_border,cyc008_ch004:CD44_border,cyc009_ch001:DAPI-09_border,cyc009_ch002:CD3_border,cyc009_ch003:CD279_border,cyc009_ch004:Vimentin_border,cyc010_ch001:DAPI-10_border,cyc010_ch002:CD11c_border,cyc010_ch003:COL4_border,cyc010_ch004:Ki67_border,cyc011_ch001:DAPI-11_border,cyc011_ch002:CD7_border,cyc011_ch003:CD4_border,cyc011_ch004:CD47_border,cyc012_ch001:DAPI-12_border,cyc012_ch002:DLL1_border,cyc012_ch003:ERTR7_border,cyc012_ch004:Laminin_border,cyc013_ch001:DAPI-13_border,cyc013_ch002:CD1a_border,cyc013_ch003:CD8a_border,cyc013_ch004:CD197_border,cyc014_ch001:DAPI-14_border,cyc014_ch002:CD68_border,cyc014_ch003:VCAM_border,cyc014_ch004:MCAM_border,cyc015_ch001:DAPI-15_border,cyc015_ch002:CD29_border,cyc015_ch003:CD45RO_border,cyc015_ch004:IgM_border,cyc016_ch001:DAPI-16_border,cyc016_ch002:Empty_border,cyc016_ch003:DLL4_border,cyc016_ch004:Fibronectin_border,cyc017_ch001:DAPI-17_border,"cyc017_ch002:HLA-DR,DP,DQ_border",cyc017_ch003:CD40_border,cyc017_ch004:CD62L_border,cyc018_ch001:DAPI-18_border,cyc018_ch002:Empty_border,cyc018_ch003:JAG1_border,cyc018_ch004:15-PGDH_border,cyc019_ch001:DAPI-19_border,cyc019_ch002:Blank_border,cyc019_ch003:Blank_border,cyc019_ch004:Blank_border,cyc020_ch001:DAPI-20_border,cyc020_ch002:WGA_border,cyc020_ch003:Empty_border,cyc020_ch004:DRAQ5_border,tissueID,condition,louvain_raw,louvain_hf,umap_1,umap_2,clusterID,mergedID,CelltypeName,CelltypeID,kmeans_neighborhood,knn_niche,knn_umap_X,knn_umap_Y,knn_niche_20,NicheName,knn_niche_30
0,0,20201203_Laura_Thymus_2,1,0,1.0,1.0,1.0,3155,2718,3.0,3155.0,2718.0,265.0,174.0,91.0,2707.998621,0.000000,0.000000,0.000000,1043.068384,882.131623,0.000000,575.471980,1543.630071,2737.624494,0.000000,0.000000,2480.633821,0.000000,4154.455156,0.000000,1858.140054,0.000000,0.0,0.000000,4525.555096,0.000000,0.000000,250.434500,5640.485063,0.000000,1074.023832,6599.478495,5548.300984,0.000000,0.000000,0.000000,3170.757254,109.426226,0.000000,0.000000,6464.809248,0.0,0.000000,5952.000512,2434.969951,0.000000,3375.921330,4429.328921,6920.841569,0.0,0.0,5847.602418,6046.299332,3013.658123,7184.326778,0.000000,8053.505566,0.000000,0.000000,8671.792257,5024.642121,2234.038008,4250.008607,2261.035545,5305.322225,0.000000,4964.796020,0.000000,6068.265268,5568.449114,0.000000,3735.845730,4948.867433,2618.907525,886.930788,1731.186430,6714.868772,2307.811942,2194.220637,1021.253630,3845.326295,4300.968511,0.000000,2027.108677,2402.931673,0.000000,0.0,0.000000,1033.322313,5647.752251,2032.242666,0.0,1324.379132,7438.379049,0.000000,1299.679364,2159.5304,0.000000,6063.466644,1161.739495,1560.623189,0.000000,0.0,437.706170,4131.274055,0.000000,0.000000,2787.951725,5084.752756,0.000000,3469.685578,12167.272151,4769.124788,0.000000,0.000000,0.000000,2754.409959,982.490939,0.000000,0.0,5748.37065,0.0,0.0,6261.062840,2174.957183,91.227516,7150.390880,10323.114152,6050.544304,0.0,0.0,11131.814718,5345.681081,4905.902298,14438.790415,0.000000,7123.229496,0.000000,0.000000,13906.447259,4358.829506,5589.980039,7073.852756,3310.886144,4783.260262,0.000000,6883.187043,0.000000,5429.728159,11836.757072,2748.464789,5360.418821,4393.057018,4615.112077,3230.171540,1268.220658,5829.270036,2407.003129,2359.313135,3037.616134,3511.634344,6989.287481,0.000000,1647.311933,4758.864523,0.000000,0.000000,241.341629,2082.049738,0.000000,0.000000,2882.866800,3789.727894,0.000000,1629.922041,0.000000,4672.035091,0.000000,183.485114,0.000000,4297.503215,0.000000,0.000000,0.000000,5821.068571,480.009952,0.000000,0.000000,7329.139237,0.000000,0.000000,1977.752915,8542.905103,0.0000,0.000000,0.000000,5509.285504,0.000000,0.0,0.000000,8517.727324,0.0,0.000000,5059.738415,4139.822344,0.000000,0.000000,382.651911,9795.553102,0.0,0.000000,2096.943259,8325.997298,595.135754,75.092143,0.000000,10603.919393,0.000000,0.000000,0.000000,7670.214028,0.000000,1584.143055,1678.749581,6945.925189,0.000000,0.000000,0.000000,8062.902732,390.917156,0.000000,1412.863942,6967.546564,0.0,0.000000,2978.916611,9507.831238,2021.903350,1515.368184,0.000000,5147.086809,1604.014081,6568.039481,4736.600163,20201203_Laura_Thymus_2_1,healthy,7,0,24.620150,-1.069352,105,39,DP cells,10,3,2,-15.835876,-0.556352,5,VCAM+ DP & DP cell niche,2
1,1,20201203_Laura_Thymus_2,1,1,2.0,1.0,1.0,2917,2857,3.0,2917.0,2857.0,196.0,124.0,72.0,0.000000,0.000000,0.000000,0.000000,0.000000,486.989373,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6269.794398,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,11769.490374,0.000000,0.000000,0.000000,0.000000,3206.005895,0.000000,0.0,0.0,29950.371622,0.000000,3056.879915,2291.278344,63.889418,0.000000,2574.360824,19932.585985,0.000000,0.000000,1618.649978,557.812826,6899.951779,0.000000,1513.877989,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,17208.724704,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,2723.345616,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8059.123478,0.000000,0.000000,1008.032630,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,4076.600395,0.000000,0.0,0.0,380.234293,0.000000,2625.341325,3445.923622,0.000000,0.000000,0.000000,3302.498905,0.000000,0.000000,0.000000,2452.435291,0.000000,0.000000,4267.227061,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2819.971404,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2225.153065,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,404.914490,0.000000,0.000000,0.000000,2490.036010,0.000000,0.000000,3828.101011,1917.339240,0.0000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2488.714199,0.0,22971.084540,0.000000,0.000000,0.000000,0.000000,1756.576993,3095.119877,0.0,0.000000,39334.642700,2611.976342,2752.014339,855.237341,2608.253262,3637.504889,9392.915952,29143.538066,0.000000,1325.761320,4110.632150,0.000000,10723.524591,1830.000511,0.000000,0.000000,0.000000,2534.639495,339.473940,0.000000,1462.500177,1826.076606,0.0,1768.301263,2164.425846,2315.426401,0.000000,0.000000,0.000000,65.228710,30235.235544,0.000000,68.963257,20201203_Laura_Thymus_2_1,healthy,12,10,1.191181,3.588288,10,50,WGA+ cells,33,8,2,-11.548785,2.868561,2,Perivasculature & trabeculae niche,2
2,2,20201203_Laura_Thymus_2,1,3,4.0,1.0,1.0,2310,92,3.0,2310.0,92.0,230.0,162.0,68.0,0.000000,0.000000,0.000000,0.000000,0.000000,7441.499876,5747.677666,3817.916668,0.000000,3648.277987,7347.363670,0.000000,0.000000,575.788437,3620.188369,3304.560486,0.000000,0.000000,0.0,0.000000,1023.597630,0.000000,3692.896448,13931.081874,1357.137940,8992.516937,10692.610804,10210.164113,193.342467,0.000000,0.000000,1669.108584,375.523465,6798.972649,0.000000,2194.826373,494.783097,0.0,0.000000,1225.820327,0.000000,0.000000,2631.138728,12812.629829,1167.124635,0.0,0.0,2738.995295,2436.223797,5065.211804,3352.658773,0.000000,2949.679225,0.000000,0.000000,0.000000,1479.146059,5557.328961,8685.681246,2125.570637,797.339511,121.152738,11376.192444,3731.494999,3940.138886,14234.720121,808.860604,0.000000,2414.732703,13098.100354,2341.028065,5513.830329,2118.323798,0.000000,0.000000,0.000000,3051.812906,4379.603124,3634.365945,3598.291188,0.000000,0.000000,0.0,0.000000,0.000000,10812.641593,9894.480969,0.0,0.000000,5207.029796,4311.090191,0.000000,0.0000,26.748368,3185.884643,6263.279458,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,6193.028343,13284.880466,0.000000,9551.467023,11510.035282,10253.358768,0.000000,0.000000,0.000000,4031.612217,0.000000,10086.034101,0.000000,0.0,0.00000,0.0,0.0,739.512064,0.000000,1347.578803,5308.159375,19238.155324,0.000000,0.0,0.0,3108.611695,802.353240,4286.490516,5091.225974,0.000000,1331.993378,0.000000,0.000000,0.000000,48.981117,6402.810675,10854.764708,3121.097132,0.000000,1784.890891,8501.886609,5238.228075,2130.103883,14522.337272,1906.496914,743.149140,763.656402,18731.778767,3511.181991,5018.217511,425.411037,0.000000,0.000000,0.000000,1149.450249,2554.645155,1146.727729,1422.254805,5551.128458,0.000000,0.000000,0.000000,871.679093,5099.638768,3449.321470,9902.530887,3300.591044,2601.688368,21636.675942,0.000000,5219.995988,2369.680834,3839.850046,2024.222611,5293.939719,773.809056,2999.770684,292.036429,8264.334700,0.000000,363.766287,12980.026307,8826.704786,7555.755168,8827.786910,10516.965590,6349.434489,0.0000,0.000000,649.022541,7283.037871,3444.840048,0.0,14230.855075,7061.168656,0.0,0.000000,3573.268632,4724.365894,0.000000,926.987251,8454.639388,7342.334895,0.0,1650.792042,2665.213999,9977.807930,5938.223145,2428.925715,0.000000,9657.941844,0.000000,0.000000,1551.792748,8497.405529,5054.537408,6814.087476,2019.200877,7090.798002,0.000000,18110.838223,23.886183,11363.331446,14830.926216,483.242793,0.000000,9707.723449,0.0,1305.835326,5833.191379,9993.874804,0.000000,549.114181,0.000000,11355.356046,7701.787152,6613.572154,12262.375418,20201203_Laura_Thymus_2_1,healthy,4,82,8.216305,-10.352919,82,53,Class II+ DP cells,9,3,1,-14.729506,-3.209070,1,PD-L1+ & Class II+ late DP niche,1
3,3,20201203_Laura_Thymus_2,1,4,5.0,1.0,1.0,3427,1750,3.0,3427.0,1750.0,228.0,154.0,74.0,0.000000,0.000000,0.000000,0.000000,0.000000,417.561606,3919.806204,838.672691,0.000000,4003.481183,2274.073748,0.000000,0.000000,1358.556515,3232.207659,1896.523500,0.000000,0.000000,0.0,164.165393,0.000000,257.305491,5150.476953,1931.969245,0.000000,3643.922916,11717.465511,377.938194,0.000000,1652.527672,3680.690103,4388.243179,0.000000,573.511104,1221.534612,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,578.471461,0.000000,0.0,0.0,4277.758722,0.000000,0.000000,0.000000,0.000000,0.000000,256.729141,588.316306,557.557444,0.000000,2346.223164,1578.136279,3710.409721,0.000000,0.000000,0.000000,0.000000,0.000000,7946.922894,2399.171781,562.053514,0.000000,0.000000,2102.461942,1266.791626,0.000000,5688.890077,4124.840637,0.000000,0.000000,8044.451608,0.000000,0.000000,0.000000,62.949043,0.0,2057.757092,0.000000,3365.702413,5223.459101,0.0,0.000000,7482.673812,2119.205969,0.000000,0.0000,2722.221537,2006.341479,3459.672891,0.000000,0.000000,0.0,1032.946406,0.000000,587.434158,2733.656862,627.053910,0.000000,2776.081781,13845.994152,2332.013522,0.000000,1527.362826,5894.449518,5211.530689,0.000000,1870.892110,1862.098800,0.0,0.00000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,4588.610132,0.000000,0.0,0.0,3975.263559,0.000000,0.000000,0.000000,133.025197,0.000000,535.669716,390.740730,0.000000,0.000000,6319.142529,4525.246267,2551.693531,0.000000,0.000000,0.000000,0.000000,0.000000,13965.156824,4456.021894,2641.457037,0.000000,0.000000,3340.555992,1162.894212,0.000000,5366.208791,3885.294225,0.000000,0.000000,11249.960433,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3328.306771,3884.841669,0.000000,944.167012,3001.291626,0.000000,0.000000,0.000000,5260.264167,1203.309217,0.000000,0.000000,373.567786,0.000000,0.000000,0.000000,7753.757830,4308.137947,925.300266,4963.402240,7603.102262,0.000000,0.000000,2166.1423,410.263518,4139.176233,0.000000,0.000000,0.0,884.403071,0.000000,0.0,15.516165,20.796220,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,4196.198314,0.000000,0.000000,0.000000,0.000000,2752.080480,422.591346,1046.920028,3309.005794,0.000000,0.000000,0.000000,4670.681918,0.000000,4767.817774,1839.359092,0.000000,1171.639194,2838.917456,1473.505325,0.000000,1564.551663,0.0,1003.264352,1676.277871,991.978827,5802.195887,4263.507544,0.000000,257.070591,4785.021147,0.000000,2136.830704,20201203_Laura_Thymus_2_1,healthy,4,0,25.728025,-2.094930,100,42,DP cells,10,25,3,-4.583569,-2.030168,1,PD-L1+ & Class II+ late DP niche,3
4,4,20201203_Laura_Thymus_2,1,6,7.0,1.0,1.0,588,1609,3.0,588.0,1609.0,382.0,261.0,121.0,0.000000,55.036858,3653.180127,2903.912853,0.000000,0.000000,2768.124104,0.000000,0.000000,13867.952093,2207.200006,12851.992288,0.000000,11399.985838,6474.649683,2912.737551,0.000000,1669.070271,0.0,332.575552,0.000000,0.000000,404.526751,10132.329570,0.000000,2982.457546,35442.081853,0.000000,0.000000,0.000000,3049.278534,1448.743168,0.000000,653.831792,0.000000,0.000000,0.000000,0.0,0.000000,5365.892658,0.000000,1520.740585,0.000000,12094.118965,0.000000,0.0,0.0,2105.792142,0.000000,0.000000,0.000000,7121.775182,0.000000,0.000000,0.000000,1938.295607,0.000000,9714.446903,0.000000,1860.470664,0.000000,0.000000,4009.962629,10921.681504,0.000000,11700.150271,2152.828327,17208.125732,0.000000,0.000000,1314.065982,14057.296918,0.000000,0.000000,0.000000,3703.513725,0.000000,2093.614471,0.000000,0.000000,0.000000,0.000000,0.0,743.564719,0.000000,0.000000,2747.123403,0.0,0.000000,7348.169170,2700.812776,8577.170264,0.0000,3902.529557,3310.642641,2113.879049,0.000000,862.316186,0.0,427.325623,0.000000,0.000000,0.000000,5739.830434,0.000000,866.158191,22249.111722,0.000000,0.000000,0.000000,6049.191552,2313.540430,0.000000,1362.361413,655.824795,0.0,0.00000,0.0,0.0,4388.220338,0.000000,2201.152506,0.000000,13841.342597,0.000000,0.0,0.0,976.041472,0.000000,0.000000,0.000000,4839.758634,0.000000,0.000000,0.000000,1042.065362,0.000000,7142.414907,0.000000,1028.574598,0.000000,0.000000,3456.852488,12325.616075,0.000000,9291.785841,2110.074984,16650.042051,0.000000,0.000000,760.901742,14576.608564,0.000000,0.000000,0.000000,2506.435070,0.000000,3363.852588,0.000000,0.000000,0.000000,7105.113947,11087.822814,5633.350538,0.000000,0.000000,3197.835157,3126.028235,0.000000,20071.967675,0.000000,12741.464388,0.000000,23339.543750,11552.699143,3789.423080,0.000000,5127.151217,0.000000,448.915017,0.000000,0.000000,3207.559309,16568.271677,0.000000,6586.702862,45986.729629,1048.256687,0.000000,0.0000,0.000000,1282.343140,0.000000,395.940866,0.0,0.000000,0.000000,0.0,0.000000,9274.102662,0.000000,1225.653281,0.000000,10257.100369,0.000000,0.0,0.000000,2918.833775,0.000000,0.000000,0.000000,9862.181338,0.000000,0.000000,0.000000,3158.068298,0.000000,11238.019302,0.000000,2670.694265,0.000000,1636.591686,4992.914754,5709.989631,0.000000,13920.292069,2496.404149,14934.271336,0.000000,0.0,2123.119709,10113.631000,0.000000,1715.852844,525.126870,5039.740107,0.000000,1141.838989,0.000000,0.000000,20201203_Laura_Thymus_2_1,healthy,4,4,0.488293,4.352634,16,54,PD-L1+ CD3+ DP cells,24,2,3,-2.726925,-1.926185,0,Medulla,3

In [7]:
# Print the first few rows of each dataframe.
i=1
print(f"Dataframe {os.listdir(INPUT_DATA_PATH)[i]}:")
df_list[i].head()

Dataframe MultiRun-CombinedDataT087.csv:

,CellID,RunID,RegionID,mergedID,RegCellID,cell_id:cell_id,region:region,tile_num:tile_num,x:x,y:y,z:z,x_tile:x_tile,y_tile:y_tile,size:size,interior:interior,border:border,cyc001_ch001:DAPI-01,cyc001_ch002:Blank,cyc001_ch003:Blank,cyc001_ch004:Blank,cyc002_ch001:DAPI-02,cyc002_ch002:CD45,"cyc002_ch003:HLA-A,B,C",cyc002_ch004:HES4,cyc003_ch001:DAPI-03,cyc003_ch002:Cytokeratin 5/8,cyc003_ch003:SATB1,cyc003_ch004:FOXP3,cyc004_ch001:DAPI-04,cyc004_ch002:CD19,cyc004_ch003:JAG2,cyc004_ch004:CD326,cyc005_ch001:DAPI-05,cyc005_ch002:SMA,cyc005_ch003:CD86,cyc005_ch004:CD45RA,cyc006_ch001:DAPI-06,cyc006_ch002:CD11b,cyc006_ch003:TCRgd,cyc006_ch004:PDGFRa,cyc007_ch001:DAPI-07,cyc007_ch002:CD5,cyc007_ch003:CD274,cyc007_ch004:CD38,cyc008_ch001:DAPI-08,cyc008_ch002:CD54,cyc008_ch003:CD31,cyc008_ch004:CD44,cyc009_ch001:DAPI-09,cyc009_ch002:CD3,cyc009_ch003:CD279,cyc009_ch004:Vimentin,cyc010_ch001:DAPI-10,cyc010_ch002:CD11c,cyc010_ch003:COL4,cyc010_ch004:Ki67,cyc011_ch001:DAPI-11,cyc011_ch002:CD7,cyc011_ch003:CD4,cyc011_ch004:CD47,cyc012_ch001:DAPI-12,cyc012_ch002:DLL1,cyc012_ch003:ERTR7,cyc012_ch004:Laminin,cyc013_ch001:DAPI-13,cyc013_ch002:CD1a,cyc013_ch003:CD8a,cyc013_ch004:CD197,cyc014_ch001:DAPI-14,cyc014_ch002:CD68,cyc014_ch003:VCAM,cyc014_ch004:MCAM,cyc015_ch001:DAPI-15,cyc015_ch002:CD29,cyc015_ch003:CD45RO,cyc015_ch004:IgM,cyc016_ch001:DAPI-16,cyc016_ch002:Empty,cyc016_ch003:DLL4,cyc016_ch004:Fibronectin,cyc017_ch001:DAPI-17,"cyc017_ch002:HLA-DR,DP,DQ",cyc017_ch003:CD40,cyc017_ch004:CD62L,cyc018_ch001:DAPI-18,cyc018_ch002:Empty,cyc018_ch003:JAG1,cyc018_ch004:15-PGDH,cyc019_ch001:DAPI-19,cyc019_ch002:Blank,cyc019_ch003:Blank,cyc019_ch004:Blank,cyc020_ch001:DAPI-20,cyc020_ch002:WGA,cyc020_ch003:Empty,cyc020_ch004:DRAQ5,cyc001_ch001:DAPI-01_interior,cyc001_ch002:Blank_interior,cyc001_ch003:Blank_interior,cyc001_ch004:Blank_interior,cyc002_ch001:DAPI-02_interior,cyc002_ch002:CD45_interior,"cyc002_ch003:HLA-A,B,C_interior",cyc002_ch004:HES4_interior,cyc003_ch001:DAPI-03_interior,cyc003_ch002:Cytokeratin 5/8_interior,cyc003_ch003:SATB1_interior,cyc003_ch004:FOXP3_interior,cyc004_ch001:DAPI-04_interior,cyc004_ch002:CD19_interior,cyc004_ch003:JAG2_interior,cyc004_ch004:CD326_interior,cyc005_ch001:DAPI-05_interior,cyc005_ch002:SMA_interior,cyc005_ch003:CD86_interior,cyc005_ch004:CD45RA_interior,cyc006_ch001:DAPI-06_interior,cyc006_ch002:CD11b_interior,cyc006_ch003:TCRgd_interior,cyc006_ch004:PDGFRa_interior,cyc007_ch001:DAPI-07_interior,cyc007_ch002:CD5_interior,cyc007_ch003:CD274_interior,cyc007_ch004:CD38_interior,cyc008_ch001:DAPI-08_interior,cyc008_ch002:CD54_interior,cyc008_ch003:CD31_interior,cyc008_ch004:CD44_interior,cyc009_ch001:DAPI-09_interior,cyc009_ch002:CD3_interior,cyc009_ch003:CD279_interior,cyc009_ch004:Vimentin_interior,cyc010_ch001:DAPI-10_interior,cyc010_ch002:CD11c_interior,cyc010_ch003:COL4_interior,cyc010_ch004:Ki67_interior,cyc011_ch001:DAPI-11_interior,cyc011_ch002:CD7_interior,cyc011_ch003:CD4_interior,cyc011_ch004:CD47_interior,cyc012_ch001:DAPI-12_interior,cyc012_ch002:DLL1_interior,cyc012_ch003:ERTR7_interior,cyc012_ch004:Laminin_interior,cyc013_ch001:DAPI-13_interior,cyc013_ch002:CD1a_interior,cyc013_ch003:CD8a_interior,cyc013_ch004:CD197_interior,cyc014_ch001:DAPI-14_interior,cyc014_ch002:CD68_interior,cyc014_ch003:VCAM_interior,cyc014_ch004:MCAM_interior,cyc015_ch001:DAPI-15_interior,cyc015_ch002:CD29_interior,cyc015_ch003:CD45RO_interior,cyc015_ch004:IgM_interior,cyc016_ch001:DAPI-16_interior,cyc016_ch002:Empty_interior,cyc016_ch003:DLL4_interior,cyc016_ch004:Fibronectin_interior,cyc017_ch001:DAPI-17_interior,"cyc017_ch002:HLA-DR,DP,DQ_interior",cyc017_ch003:CD40_interior,cyc017_ch004:CD62L_interior,cyc018_ch001:DAPI-18_interior,cyc018_ch002:Empty_interior,cyc018_ch003:JAG1_interior,cyc018_ch004:15-PGDH_interior,cyc019_ch001:DAPI-19_interior,cyc019_ch002:Blank_interior,cyc019_ch003:Blank_interior,cyc019_ch004:Blank_interior,cyc020_ch001:DAPI-20_interior,cyc020_ch002:WGA_interior,cyc020_ch003:Empty_interior,cyc020_ch004:DRAQ5_interior,cyc001_ch001:DAPI-01_border,cyc001_ch002:Blank_border,cyc001_ch003:Blank_border,cyc001_ch004:Blank_border,cyc002_ch001:DAPI-02_border,cyc002_ch002:CD45_border,"cyc002_ch003:HLA-A,B,C_border",cyc002_ch004:HES4_border,cyc003_ch001:DAPI-03_border,cyc003_ch002:Cytokeratin 5/8_border,cyc003_ch003:SATB1_border,cyc003_ch004:FOXP3_border,cyc004_ch001:DAPI-04_border,cyc004_ch002:CD19_border,cyc004_ch003:JAG2_border,cyc004_ch004:CD326_border,cyc005_ch001:DAPI-05_border,cyc005_ch002:SMA_border,cyc005_ch003:CD86_border,cyc005_ch004:CD45RA_border,cyc006_ch001:DAPI-06_border,cyc006_ch002:CD11b_border,cyc006_ch003:TCRgd_border,cyc006_ch004:PDGFRa_border,cyc007_ch001:DAPI-07_border,cyc007_ch002:CD5_border,cyc007_ch003:CD274_border,cyc007_ch004:CD38_border,cyc008_ch001:DAPI-08_border,cyc008_ch002:CD54_border,cyc008_ch003:CD31_border,cyc008_ch004:CD44_border,cyc009_ch001:DAPI-09_border,cyc009_ch002:CD3_border,cyc009_ch003:CD279_border,cyc009_ch004:Vimentin_border,cyc010_ch001:DAPI-10_border,cyc010_ch002:CD11c_border,cyc010_ch003:COL4_border,cyc010_ch004:Ki67_border,cyc011_ch001:DAPI-11_border,cyc011_ch002:CD7_border,cyc011_ch003:CD4_border,cyc011_ch004:CD47_border,cyc012_ch001:DAPI-12_border,cyc012_ch002:DLL1_border,cyc012_ch003:ERTR7_border,cyc012_ch004:Laminin_border,cyc013_ch001:DAPI-13_border,cyc013_ch002:CD1a_border,cyc013_ch003:CD8a_border,cyc013_ch004:CD197_border,cyc014_ch001:DAPI-14_border,cyc014_ch002:CD68_border,cyc014_ch003:VCAM_border,cyc014_ch004:MCAM_border,cyc015_ch001:DAPI-15_border,cyc015_ch002:CD29_border,cyc015_ch003:CD45RO_border,cyc015_ch004:IgM_border,cyc016_ch001:DAPI-16_border,cyc016_ch002:Empty_border,cyc016_ch003:DLL4_border,cyc016_ch004:Fibronectin_border,cyc017_ch001:DAPI-17_border,"cyc017_ch002:HLA-DR,DP,DQ_border",cyc017_ch003:CD40_border,cyc017_ch004:CD62L_border,cyc018_ch001:DAPI-18_border,cyc018_ch002:Empty_border,cyc018_ch003:JAG1_border,cyc018_ch004:15-PGDH_border,cyc019_ch001:DAPI-19_border,cyc019_ch002:Blank_border,cyc019_ch003:Blank_border,cyc019_ch004:Blank_border,cyc020_ch001:DAPI-20_border,cyc020_ch002:WGA_border,cyc020_ch003:Empty_border,cyc020_ch004:DRAQ5_border,tissueID,condition,louvain_raw,louvain_hf,umap_1,umap_2,clusterID,CelltypeName,CelltypeID,kmeans_neighborhood,knn_niche,knn_umap_X,knn_umap_Y,knn_niche_20
0,0,20201203_Laura_Thymus_2,1,1,0,1.0,1.0,1.0,3155,2718,3.0,3155.0,2718.0,265.0,174.0,91.0,2301.628454,0.0,0.000000,0.000000,720.409648,805.006116,0.000000,392.757051,1190.031964,2677.197815,0.000000,0.000000,2030.081118,0.000000,3587.418311,0.000000,1463.410948,0.000000,0.00000,0.000000,3912.765885,0.000000,0.000000,146.580706,4984.225053,0.000000,802.090754,6545.786781,4863.777493,0.000000,0.000000,0.000000,2709.735389,54.588990,0.000000,0.000000,5771.713874,0.0,0.000000,6129.430199,2018.481510,0.000000,3284.601250,4298.948019,6252.551423,0.0,0.0,4760.569681,5379.397574,2943.386622,7080.446836,0.000000,7262.103994,0.000000,0.000000,7765.211375,4425.090485,2015.546247,4261.251550,1934.991406,4695.189500,0.000000,4563.747395,0.000000,5411.300932,5329.158044,0.000000,3465.388365,4389.391210,2358.300782,561.173666,1576.704419,6010.325339,1626.473952,1418.880800,226.616475,3325.919795,3830.698413,0.000000,1637.871367,2014.691962,0.000000,0.000000,0.000000,717.929195,5394.235109,1807.645355,0.000000,993.437442,7234.500732,0.000000,1155.371179,1741.180639,0.000000,5494.458712,1049.525132,1200.191730,0.000000,0.000000,380.141456,3547.000383,0.000000,0.000000,2594.663736,4459.850605,0.000000,3010.944722,12002.688347,4139.940304,0.000000,0.000000,0.000000,2318.790311,885.469757,0.000000,0.0,5094.074155,0.0,0.0,6463.158880,1779.999374,20.215122,6896.866933,9893.299643,5402.334179,0.0,0.000000,9929.185011,4708.283867,4642.127455,14129.462132,0.000000,6366.764863,0.000000,0.000000,12712.785373,3794.175090,5135.788598,7003.049595,2821.192548,4189.931615,0.000000,6411.003807,0.000000,4794.024091,11320.169109,2476.190847,4988.930642,3855.705677,4292.233849,2682.926486,1138.206649,5168.705669,1804.655471,1679.774870,2030.375057,3003.803816,6267.342005,0.000000,1266.847401,4364.923720,0.0,0.000000,0.000000,1767.310226,0.000000,0.000000,2616.588870,3391.067443,0.000000,1549.580036,0.000000,4194.299073,0.000000,0.000000,0.000000,3847.881631,0.000000,0.000000,0.000000,5276.386709,233.297201,0.000000,0.000000,6748.153105,0.000000,0.000000,2084.452195,7864.843947,0.000000,0.000000,0.000000,5041.846266,0.00000,0.0,0.000000,7885.066253,0.0,0.000000,5179.958902,3751.754411,0.0,0.000000,490.971007,9172.383407,0.0,0.000000,1733.623469,7683.858966,771.883433,236.738123,0.000000,9855.174333,0.000000,0.000000,0.000000,7042.555788,0.000000,1705.168341,1449.630971,6425.063555,0.000000,0.000000,0.0,7447.625867,366.114975,0.000000,1341.529283,6471.804903,0.0,0.000000,2781.983352,8839.187836,1202.689167,676.535726,0.000000,4710.271923,1340.219285,6229.856064,4378.297126,20201203_Laura_Thymus_2_1,healthy,0,0,-11.652596,8.709279,29,DPs,6,3,21,3.566945,35.006706,17
1,1,20201203_Laura_Thymus_2,1,40,1,2.0,1.0,1.0,2917,2857,3.0,2917.0,2857.0,196.0,124.0,72.0,0.000000,0.0,0.000000,0.000000,0.000000,421.992582,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6224.095553,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,10442.524641,0.000000,0.000000,0.000000,0.000000,3126.303503,0.000000,0.0,0.0,24503.362604,0.000000,2985.881494,2330.066065,0.000000,0.000000,1775.837743,16285.282860,0.000000,0.000000,1437.118676,649.926380,6072.296824,0.000000,1373.966995,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15779.587079,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2566.689833,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7968.355378,0.000000,0.000000,881.730744,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,3904.004312,0.000000,0.0,0.000000,328.731723,0.000000,2443.645843,3416.768865,0.000000,0.000000,0.000000,2665.612167,0.000000,0.000000,0.000000,2459.899559,0.000000,0.000000,4026.424590,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2601.151255,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1930.350715,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,191.168447,0.000000,0.000000,0.000000,2174.185664,0.000000,0.000000,3888.884956,1620.960316,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,0.000000,2190.601466,0.0,19083.953255,0.000000,0.000000,0.0,0.000000,1814.888872,2785.824357,0.0,0.000000,32896.332798,2291.423782,2865.443154,994.711415,2224.277296,3266.110638,6898.912426,23494.047452,0.000000,1083.079904,3908.393593,0.000000,9720.468568,1561.139695,0.000000,0.000000,0.0,2222.734939,316.051525,0.000000,1389.245872,1573.126851,0.0,1337.656891,2002.197898,2032.351429,0.000000,0.000000,0.000000,0.000000,28311.591193,0.000000,0.000000,20201203_Laura_Thymus_2_1,healthy,9,2,4.158942,11.100905,2,cTECs,14,0,10,7.194742,20.358446,2
2,2,20201203_Laura_Thymus_2,1,11,2,3.0,1.0,1.0,3143,486,3.0,3143.0,486.0,66.0,32.0,34.0,3067.267824,0.0,6595.565317,14554.680556,0.000000,17176.765038,20562.490984,23450.223463,1173.119233,2587.842019,1372.736119,9327.853952,3815.602007,0.000000,2421.749525,52383.615848,2659.163991,1060.262903,3834.85965,11376.382119,4807.507818,0.000000,0.000000,10173.833812,5654.816356,18332.474536,3262.833918,2943.964117,5028.883191,1827.360872,5027.130688,12994.115121,4296.616043,16198.098300,0.000000,10622.561028,4365.632330,0.0,0.000000,290.478492,3993.908154,4072.631498,0.000000,4672.619335,5332.357394,0.0,0.0,506.772655,5470.022391,0.000000,8475.045622,7362.781341,6894.875493,0.000000,0.000000,0.000000,4397.275163,0.000000,0.000000,5051.259626,5747.328779,0.000000,8153.283781,229.653874,6606.442257,22488.055995,11761.910385,11816.759291,6469.418897,0.000000,3330.343477,504.799894,6826.820558,4298.263638,6023.259745,17324.205410,6510.085182,11042.826288,9026.588549,6633.203103,3818.805933,1312.724935,11239.171936,25536.232941,601.139139,37128.126137,43809.210182,15524.495313,1866.481546,6645.396567,2206.215020,5756.843436,4578.674425,0.000000,7716.874476,128920.866081,3402.734187,3986.489373,9552.402377,17181.342639,5605.426249,0.000000,0.000000,15702.934844,6085.844867,24693.239760,7076.515196,8828.644653,5859.822270,1082.463244,9583.303750,26558.902071,4840.833610,27217.122430,0.000000,0.0,5079.928877,0.0,0.0,745.158829,4670.538005,9400.896310,0.000000,16806.599884,5891.584952,0.0,3357.573093,0.000000,6228.639389,0.000000,20018.118866,10259.102297,7873.301040,0.000000,0.000000,0.000000,4985.089836,6034.937885,5687.682466,8523.864336,6590.384395,0.000000,9835.808470,3963.385666,7330.731758,37761.375150,26586.255278,10527.100758,6943.255004,0.000000,7615.017741,511.969740,7508.232608,5916.416858,8071.837036,25503.861162,7165.583568,21261.452087,2895.820461,7209.311035,11644.166494,0.0,901.484897,1583.629579,6150.070874,1978.093043,7481.210139,17154.796808,9097.341798,0.000000,2094.232556,6739.972446,12359.307203,0.000000,0.000000,19010.657101,10863.213836,0.000000,0.000000,6633.481156,13230.482427,262.301920,0.000000,2566.500813,15217.574000,9756.280128,0.000000,0.000000,13156.842866,4156.867804,166.732095,4777.710926,13020.994162,5576.41477,0.0,13966.314803,12182.791956,0.0,0.000000,0.000000,12045.027921,0.0,0.000000,0.000000,13194.566023,0.0,0.000000,470.230289,13560.587180,0.000000,0.000000,3431.555350,14426.003297,0.000000,0.000000,0.000000,13039.574834,0.000000,0.000000,2253.210145,13437.067487,0.000000,8133.430040,0.0,14894.231521,9513.723827,4565.865176,7683.944544,15067.783395,0.0,526.980125,1491.281806,15514.472450,5161.095163,5156.406396,5538.572094,15212.852938,2897.863171,9694.497625,16442.127473,20201203_Laura_Thymus_2_1,healthy,2,56,4.358849,12.749584,56,mTECs,15,0,5,11.095416,19.204384,0
3,3,20201203_Laura_Thymus_2,1,41,3,4.0,1.0,1.0,2310,92,3.0,2310.0,92.0,230.0,162.0,68.0,0.000000,0.0,0.000000,0.000000,0.000000,7163.037466,5427.177724,3394.429709,0.000000,3560.723976,7204.241814,0.000000,0.000000,363.016101,3096.725819,3107.378821,0.000000,0.000000,0.00000,0.000000,688.172140,0.000000,3173.202330,13030.822822,999.286570,8184.406583,9614.390171,10068.934847,0.000000,0.000000,0.000000,1524.384431,104.399457,6539.298350,0.000000,1950.883366,202.516349,0.0,0.000000,1307.053843,0.000000,0.000000,2566.093472,12334.954553,832.645683,0.0,0.0,2214.281900,2008.942709,4960.436533,3360.499598,0.000000,2491.671167,0.000000,0.000000,0.000000,1125.539759,5139.238980,8599.769113,1814.174459,466.401207,61.662925,10657.227470,3396.872719,3421.133139,13686.407266,694.899093,0.000000,2001.896273,12138.423087,1811.522916,5194.104680,1716.370471,0.000000,0.000000,0.000000,2587.434527,3903.491563,3311.798946,3094.868190,0.000000,0.000000,0.000000,0.000000,0.000000,10388.054466,9293.821815,0.000000,0.000000,5070.105844,4292.742420,0.000000,0.000000,0.000000,2798.862793,5819.899946,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5480.098143,12510.745756,0.000000,8559.120368,10364.703542,10123.164387,0.000000,0.000000,0.000000,3807.531504,0.000000,9610.647432,0.000000,0.0,0.000000,0.0,0.0,808.873445,0.000000,1220.287613,5114.117107,18441.237987,0.000000,0.0,0.000000,2764.993069,484.519056,4045.008839,5020.137645,0.000000,982.486688,0.000000,0.000000,0.000000,0.000000,5898.272927,10719.928758,2655.988674,0.000000,1666.194768,7955.753645,4873.351609,1724.976532,13897.450954,1695.613155,621.979571,457.526914,17590.606334,2931.174815,4718.182268,138.613637,0.000000,0.000000,0.000000,813.321489,2230.301178,1036.645883,1059.335192,5114.547946,0.0,0.000000,0.000000,633.977151,4998.895484,3252.037188,9209.987233,2932.340650,2567.223119,20785.858479,0.000000,4707.482429,2059.272688,3279.243837,1922.272253,4781.422641,507.857185,2558.033065,255.194772,7570.365307,0.000000,193.043518,12156.957599,8163.666629,7180.608765,8110.547175,10411.769165,5797.733674,0.000000,0.000000,546.557138,6718.348550,3375.56267,0.0,13684.791103,6509.331639,0.0,0.000000,3682.674505,4304.591955,0.0,995.948422,8269.159620,6834.083417,0.0,1384.427453,2209.186035,9242.705500,5958.115345,2523.675204,0.000000,8960.437690,0.000000,0.000000,1347.971628,7819.553905,4808.939257,6829.829039,1760.950753,6562.800206,0.000000,16931.461116,0.0,10566.938264,14418.826721,408.672989,0.000000,9082.584404,0.0,936.527366,5514.637965,9299.175715,0.000000,0.000000,0.000000,10573.286833,7084.483655,6273.657853,11512.143879,20201203_Laura_Thymus_2_1,healthy,6,95,4.054614,19.646503,95,Class II+ DPs,4,4,0,4.488177,15.952962,1
4,4,20201203_Laura_Thymus_2,1,1,4,5.0,1.0,1.0,3427,1750,3.0,3427.0,1750.0,228.0,154.0,74.0,0.000000,0.0,0.000000,0.000000,0.000000,354.695869,3660.092705,636.413444,0.000000,3905.346073,2265.544768,0.000000,0.000000,1061.858229,2740.388449,1768.304539,0.000000,0.000000,0.00000,121.001077,0.000000,93.897302,4486.958139,1730.226581,0.000000,3251.521766,10553.335420,475.081655,0.000000,1339.008000,3302.735009,4203.009511,0.000000,504.463371,975.376967,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,607.619739,0.000000,0.0,0.0,3474.696728,0.000000,0.000000,0.000000,0.000000,0.000000,11.518806,316.123084,372.228993,0.000000,2120.993517,1647.901564,3227.643252,0.000000,0.000000,0.000000,0.000000,0.000000,7622.820235,2209.921054,456.117443,0.000000,0.000000,1606.384665,1132.596560,0.000000,4559.802091,3049.743196,0.000000,0.000000,7296.092559,0.000000,0.000000,0.000000,0.000000,0.000000,1236.207577,0.000000,3187.770672,4846.221449,0.000000,0.000000,7277.466377,2144.728994,0.000000,0.000000,2310.600207,1693.917134,3198.288775,0.000000,0.000000,0.000000,934.066039,0.000000,423.994059,2349.618651,553.339030,0.000000,2425.039828,12501.187498,2344.150814,0.000000,1271.634915,5409.658679,4950.323331,0.000000,1736.946806,1582.821811,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,4394.930555,0.000000,0.0,0.000000,3538.856112,0.000000,0.000000,0.000000,0.000000,0.000000,253.245551,143.895986,0.000000,0.000000,5819.787142,4497.605811,2160.345222,0.000000,0.000000,0.000000,0.000000,0.000000,13362.739292,4059.245286,2417.373446,0.000000,0.000000,2780.441563,1037.655602,0.000000,4382.008851,2981.732826,0.000000,0.000000,10146.011217,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,3133.934611,3557.719297,0.000000,948.956578,2868.137125,0.000000,0.000000,0.000000,4576.343353,1132.275104,0.000000,0.000000,210.913022,0.000000,0.000000,0.000000,6983.831137,3956.221869,695.182218,4690.328301,6966.991139,0.000000,0.000000,1762.968477,301.915258,4018.828294,0.000000,0.00000,0.0,810.560151,0.000000,0.0,0.000000,104.356552,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,3490.404261,0.000000,0.000000,0.000000,0.000000,2428.647144,198.913657,757.118045,2985.353715,0.000000,0.000000,0.000000,4185.551592,0.000000,4591.487775,1616.407139,0.0,934.531464,2748.457149,1363.937897,0.000000,1323.951710,0.0,674.086089,1534.849824,779.850863,4446.689291,2937.710124,0.000000,92.199333,4336.812523,0.000000,1913.918868,20201203_Laura_Thymus_2_1,healthy,2,0,-11.261544,9.965876,13,DPs,6,0,40,-1.843992,18.887125,4

In [8]:
# Print the first few rows of each dataframe.
i=2
print(f"Dataframe {os.listdir(INPUT_DATA_PATH)[i]}:")
df_list[i].head()

Dataframe MultiRun-CombinedDataT098 2.csv:

,CellID,RunID,RegionID,RegCellID,cell_id:cell_id,region:region,tile_num:tile_num,x:x,y:y,z:z,x_tile:x_tile,y_tile:y_tile,size:size,interior:interior,border:border,cyc001_ch001f:DAPI-01,cyc001_ch002f:Blank,cyc001_ch003f:Blank,cyc001_ch004f:Blank,cyc002_ch001f:DAPI-02,cyc002_ch002f:CD45,"cyc002_ch003f:HLA-A,B,C",cyc002_ch004f:TCRgd,cyc003_ch001f:DAPI-03,cyc003_ch002f:Cytokeratin5/8,cyc003_ch003f:SATB1,cyc003_ch004f:CD25,cyc004_ch001f:DAPI-04,cyc004_ch002f:CD19,cyc004_ch003f:JAG2,cyc004_ch004f:EPCAM,cyc005_ch001f:DAPI-05,cyc005_ch002f:SMA,cyc005_ch003f:CD86,cyc005_ch004f:CD45RA,cyc006_ch001f:DAPI-06,cyc006_ch002f:CD5,cyc006_ch003f:PD-L1,cyc006_ch004f:CD38,cyc007_ch001f:DAPI-07,cyc007_ch002f:ICAM/Caspase3,cyc007_ch003f:CD31,cyc007_ch004f:IL7R,cyc008_ch001f:DAPI-08,cyc008_ch002f:CD3,cyc008_ch003f:PD1,cyc008_ch004f:AIRE,cyc009_ch001f:DAPI-09,cyc009_ch002f:CD11c,cyc009_ch003f:COL4,cyc009_ch004f:PDGFRa,cyc010_ch001f:DAPI-10,cyc010_ch002f:CD7,cyc010_ch003f:CD4,cyc010_ch004f:CD20,cyc011_ch001f:DAPI-11,cyc011_ch002f:DLL1,cyc011_ch003f:CD80,cyc011_ch004f:Laminin,cyc012_ch001f:DAPI-12,cyc012_ch002f:CD1a,cyc012_ch003f:CD8a,cyc012_ch004f:CCR7,cyc013_ch001f:DAPI-13,cyc013_ch002f:CD68,cyc013_ch003f:VCAM,cyc013_ch004f:MCAM,cyc014_ch001f:DAPI-14,cyc014_ch002f:CD29,cyc014_ch003f:CD45RO,cyc014_ch004f:IgM,cyc015_ch001f:DAPI-15,cyc015_ch002f:CD44,cyc015_ch003f:DLL4,cyc015_ch004f:Empty,cyc016_ch001f:DAPI-16,"cyc016_ch002f:HLA-DR,DP,DQ",cyc016_ch003f:CD40,cyc016_ch004f:CD62L,cyc017_ch001f:DAPI-17,cyc017_ch002f:CD28,cyc017_ch003f:JAG1,cyc017_ch004f:Ki67,cyc018_ch001f:DAPI-18,cyc018_ch002f:Blank,cyc018_ch003f:Blank,cyc018_ch004f:Blank,cyc019_ch001f:DAPI-19,cyc019_ch002f:Blank,cyc019_ch003f:Blank,cyc019_ch004f:DRAQ5,cyc001_ch001i:DAPI-01_interior,cyc001_ch002i:Blank_interior,cyc001_ch003i:Blank_interior,cyc001_ch004i:Blank_interior,cyc002_ch001i:DAPI-02_interior,cyc002_ch002i:CD45_interior,"cyc002_ch003i:HLA-A,B,C_interior",cyc002_ch004i:TCRgd_interior,cyc003_ch001i:DAPI-03_interior,cyc003_ch002i:Cytokeratin5/8_interior,cyc003_ch003i:SATB1_interior,cyc003_ch004i:CD25_interior,cyc004_ch001i:DAPI-04_interior,cyc004_ch002i:CD19_interior,cyc004_ch003i:JAG2_interior,cyc004_ch004i:EPCAM_interior,cyc005_ch001i:DAPI-05_interior,cyc005_ch002i:SMA_interior,cyc005_ch003i:CD86_interior,cyc005_ch004i:CD45RA_interior,cyc006_ch001i:DAPI-06_interior,cyc006_ch002i:CD5_interior,cyc006_ch003i:PD-L1_interior,cyc006_ch004i:CD38_interior,cyc007_ch001i:DAPI-07_interior,cyc007_ch002i:ICAM/Caspase3_interior,cyc007_ch003i:CD31_interior,cyc007_ch004i:IL7R_interior,cyc008_ch001i:DAPI-08_interior,cyc008_ch002i:CD3_interior,cyc008_ch003i:PD1_interior,cyc008_ch004i:AIRE_interior,cyc009_ch001i:DAPI-09_interior,cyc009_ch002i:CD11c_interior,cyc009_ch003i:COL4_interior,cyc009_ch004i:PDGFRa_interior,cyc010_ch001i:DAPI-10_interior,cyc010_ch002i:CD7_interior,cyc010_ch003i:CD4_interior,cyc010_ch004i:CD20_interior,cyc011_ch001i:DAPI-11_interior,cyc011_ch002i:DLL1_interior,cyc011_ch003i:CD80_interior,cyc011_ch004i:Laminin_interior,cyc012_ch001i:DAPI-12_interior,cyc012_ch002i:CD1a_interior,cyc012_ch003i:CD8a_interior,cyc012_ch004i:CCR7_interior,cyc013_ch001i:DAPI-13_interior,cyc013_ch002i:CD68_interior,cyc013_ch003i:VCAM_interior,cyc013_ch004i:MCAM_interior,cyc014_ch001i:DAPI-14_interior,cyc014_ch002i:CD29_interior,cyc014_ch003i:CD45RO_interior,cyc014_ch004i:IgM_interior,cyc015_ch001i:DAPI-15_interior,cyc015_ch002i:CD44_interior,cyc015_ch003i:DLL4_interior,cyc015_ch004i:Empty_interior,cyc016_ch001i:DAPI-16_interior,"cyc016_ch002i:HLA-DR,DP,DQ_interior",cyc016_ch003i:CD40_interior,cyc016_ch004i:CD62L_interior,cyc017_ch001i:DAPI-17_interior,cyc017_ch002i:CD28_interior,cyc017_ch003i:JAG1_interior,cyc017_ch004i:Ki67_interior,cyc018_ch001i:DAPI-18_interior,cyc018_ch002i:Blank_interior,cyc018_ch003i:Blank_interior,cyc018_ch004i:Blank_interior,cyc019_ch001i:DAPI-19_interior,cyc019_ch002i:Blank_interior,cyc019_ch003i:Blank_interior,cyc019_ch004i:DRAQ5_interior,cyc001_ch001b:DAPI-01_border,cyc001_ch002b:Blank_border,cyc001_ch003b:Blank_border,cyc001_ch004b:Blank_border,cyc002_ch001b:DAPI-02_border,cyc002_ch002b:CD45_border,"cyc002_ch003b:HLA-A,B,C_border",cyc002_ch004b:TCRgd_border,cyc003_ch001b:DAPI-03_border,cyc003_ch002b:Cytokeratin5/8_border,cyc003_ch003b:SATB1_border,cyc003_ch004b:CD25_border,cyc004_ch001b:DAPI-04_border,cyc004_ch002b:CD19_border,cyc004_ch003b:JAG2_border,cyc004_ch004b:EPCAM_border,cyc005_ch001b:DAPI-05_border,cyc005_ch002b:SMA_border,cyc005_ch003b:CD86_border,cyc005_ch004b:CD45RA_border,cyc006_ch001b:DAPI-06_border,cyc006_ch002b:CD5_border,cyc006_ch003b:PD-L1_border,cyc006_ch004b:CD38_border,cyc007_ch001b:DAPI-07_border,cyc007_ch002b:ICAM/Caspase3_border,cyc007_ch003b:CD31_border,cyc007_ch004b:IL7R_border,cyc008_ch001b:DAPI-08_border,cyc008_ch002b:CD3_border,cyc008_ch003b:PD1_border,cyc008_ch004b:AIRE_border,cyc009_ch001b:DAPI-09_border,cyc009_ch002b:CD11c_border,cyc009_ch003b:COL4_border,cyc009_ch004b:PDGFRa_border,cyc010_ch001b:DAPI-10_border,cyc010_ch002b:CD7_border,cyc010_ch003b:CD4_border,cyc010_ch004b:CD20_border,cyc011_ch001b:DAPI-11_border,cyc011_ch002b:DLL1_border,cyc011_ch003b:CD80_border,cyc011_ch004b:Laminin_border,cyc012_ch001b:DAPI-12_border,cyc012_ch002b:CD1a_border,cyc012_ch003b:CD8a_border,cyc012_ch004b:CCR7_border,cyc013_ch001b:DAPI-13_border,cyc013_ch002b:CD68_border,cyc013_ch003b:VCAM_border,cyc013_ch004b:MCAM_border,cyc014_ch001b:DAPI-14_border,cyc014_ch002b:CD29_border,cyc014_ch003b:CD45RO_border,cyc014_ch004b:IgM_border,cyc015_ch001b:DAPI-15_border,cyc015_ch002b:CD44_border,cyc015_ch003b:DLL4_border,cyc015_ch004b:Empty_border,cyc016_ch001b:DAPI-16_border,"cyc016_ch002b:HLA-DR,DP,DQ_border",cyc016_ch003b:CD40_border,cyc016_ch004b:CD62L_border,cyc017_ch001b:DAPI-17_border,cyc017_ch002b:CD28_border,cyc017_ch003b:JAG1_border,cyc017_ch004b:Ki67_border,cyc018_ch001b:DAPI-18_border,cyc018_ch002b:Blank_border,cyc018_ch003b:Blank_border,cyc018_ch004b:Blank_border,cyc019_ch001b:DAPI-19_border,cyc019_ch002b:Blank_border,cyc019_ch003b:Blank_border,cyc019_ch004b:DRAQ5_border,tissueID,louvain_hf,umap_1,umap_2,clusterID,mergedID,CelltypeName,CelltypeID,kmeans_neighborhood,knn_niche,knn_umap_X,knn_umap_Y
0,0,2022-06-01-THYMUS-ARCHITECTURE-T098,1,0,1.0,1.0,1.0,821,447,0.0,821.0,447.0,89.0,50.0,39.0,0.000000,3066.562772,20589.468424,6502.766869,675.007002,0.000000,6588.201042,22946.397286,0.000000,4534.640049,17154.854439,10197.728909,0.000000,0.0,2409.43407,6898.027886,498.108599,0.0,0.000000,2427.957250,1528.828535,0.000000,1523.612753,4774.983849,1104.828677,0.0,0.000000,0.000000,4425.795720,4298.097377,0.000000,1549.674712,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7340.797149,0.000000,2939.395516,0.0,13474.948394,8858.903666,0.000000,1333.392753,37756.015511,9806.639084,1920.882211,1782.928654,3758.995970,8159.576461,1615.155063,18375.680873,0.000000,6037.581253,0.000000,2238.429524,9618.657514,7656.931369,0.000000,11866.039629,7049.108729,16837.082617,0.000000,2699.396127,7077.591460,32082.408915,537.817525,782.972177,6760.247612,3916.772574,0.000000,10847.169133,659.667582,2658.526218,0.000000,2972.235593,20258.744691,0.000000,0.000000,0.000000,10917.870304,25276.608631,0.000000,7293.677595,15289.714888,10849.463385,0.000000,0.0,875.874567,21210.177888,0.000000,0.0,0.000000,2078.324384,0.000000,0.000000,1445.836181,4669.861291,0.000000,0.0,0.000000,2698.540407,1469.057992,0.000000,0.000000,8702.877547,0.000000,0.000000,0.000000,8592.090380,0.000000,2842.810808,6824.795149,3222.545850,456.296312,0.000000,13338.387324,13608.625619,0.000000,3643.196687,55722.081731,5311.771435,377.923589,0.00000,8555.563087,8071.192697,0.000000,28640.707360,1500.671910,8083.537556,0.000000,5334.544302,12111.274536,0.0,0.000000,21037.967142,13102.667222,12573.740334,0.000000,0.000000,8220.776818,27278.993627,0.000000,2219.624193,7663.338004,5095.211131,0.000000,16533.083217,706.432961,0.000000,1020.984690,3012.909375,18878.298626,14660.821686,6430.822770,0.000000,2373.568094,10522.178511,3269.016189,3147.200611,16754.445247,4425.206296,3727.001464,0.0,2945.203318,0.000000,5440.569867,0.0,0.000000,1795.343423,6920.320573,0.000000,1256.770583,3306.413360,7131.534347,0.0,0.00000,0.000000,10085.989379,7264.813409,0.000000,0.000000,6197.617428,0.0,0.000000,0.000000,5060.757473,0.0,4875.446661,0.000000,8596.246701,0.0,9682.769282,1187.372878,5903.398996,0.0,22252.182541,9250.671354,6128.516947,4825.872136,1208.203066,4662.271044,6855.791321,6704.397347,0.000000,2758.724416,5185.491893,0.000000,5233.041707,13830.802689,2684.053294,4656.611926,2528.898420,17319.966835,4202.730751,5781.981908,4096.665985,39545.925704,7244.003788,0.000000,4692.500976,1261.499573,2948.305823,0.000000,550.599608,9299.828410,2022-06-01-THYMUS-ARCHITECTURE-T098_1,77,9.186737,11.784051,77,7,Class II+ DPs,4,1,3,-38.927532,13.051946
1,1,2022-06-01-THYMUS-ARCHITECTURE-T098,1,1,2.0,1.0,1.0,1996,1274,0.0,1996.0,1274.0,87.0,47.0,40.0,5833.210540,558.286388,3552.838477,2584.691652,7028.910730,496.411615,8956.837849,0.000000,6757.025778,0.000000,0.000000,0.000000,7319.227175,0.0,0.00000,0.000000,10393.830129,0.0,3770.654587,1047.621158,13039.831362,0.000000,0.000000,0.000000,7601.566942,0.0,0.000000,3399.039994,12939.999021,3839.230783,847.154454,0.000000,9098.364267,4292.152444,0.000000,4768.424949,10337.150148,868.496483,0.000000,1534.560439,11200.293681,0.0,0.000000,760.958443,7806.023059,0.000000,0.000000,0.000000,8758.019272,0.000000,0.000000,517.641590,10403.063403,0.000000,0.000000,0.000000,5475.536882,6083.370050,0.000000,1076.636738,4387.811048,2149.387258,7685.612648,0.000000,2814.215649,0.000000,0.000000,0.000000,6745.150275,10953.895680,13224.706704,663.620336,5143.037472,0.000000,14578.890847,4575.024899,10047.698749,803.224527,5467.849143,9058.836097,11310.237381,0.000000,9644.075929,847.675338,10991.460444,0.000000,0.000000,0.000000,10745.433085,0.0,0.000000,0.000000,13732.459657,0.0,732.211398,0.000000,17367.956510,2279.565172,0.000000,0.000000,12312.864804,0.0,0.000000,0.000000,16909.342301,10632.546303,0.000000,0.000000,13728.782545,14217.950435,0.000000,0.000000,14308.917623,5875.671724,0.000000,1976.712539,14633.218071,6606.535647,0.000000,0.000000,12348.547898,3403.705919,0.000000,0.000000,12414.771372,2155.55751,0.000000,0.000000,14428.081195,0.000000,0.000000,0.000000,9208.222339,5509.592751,0.000000,0.0,8079.338073,3161.764484,6589.259815,0.000000,6843.746034,0.000000,842.849500,0.000000,9757.470685,12692.037182,15250.267633,11301.237124,7886.548536,914.282549,3084.764830,6466.075912,26.608933,91.754277,611.728318,0.000000,1165.520034,0.000000,6251.421503,0.000000,739.174256,0.000000,0.000000,139.505956,2238.093969,0.0,0.000000,0.000000,4581.950771,0.0,6191.572077,2680.495106,4857.098721,0.000000,0.000000,0.000000,1453.238165,0.0,0.00000,18771.756398,5430.349019,0.000000,3197.190000,0.000000,1686.837182,0.0,0.000000,12989.909583,3071.354317,0.0,0.000000,1046.525504,4747.710363,0.0,0.000000,3959.093694,1316.739086,0.0,0.000000,0.000000,3337.952345,0.000000,0.000000,1604.725187,3404.249740,0.000000,0.000000,2106.736819,763.172925,3676.862560,0.000000,3282.851250,0.000000,934.794640,6340.161288,2928.768707,0.000000,0.000000,0.000000,0.000000,2517.425756,7802.814877,9118.434221,0.000000,1933.927349,0.000000,15149.814046,3752.831491,2022-06-01-THYMUS-ARCHITECTURE-T098_1,0,19.961880,8.410901,191,10,Auto,2,-1,-1,NaN,NaN
2,2,2022-06-01-THYMUS-ARCHITECTURE-T098,1,2,3.0,1.0,1.0,4338,1480,0.0,4338.0,1480.0,112.0,71.0,41.0,2008.679247,3863.597372,5161.734796,0.000000,5659.552805,4843.069172,1934.679304,4753.697940,3541.485045,10865.478030,0.000000,2752.101215,1912.313783,0.0,0.00000,3874.851813,8661.779679,0.0,0.000000,193.548822,6134.997889,0.000000,0.000000,120.665999,5205.210803,0.0,0.000000,8842.890881,8272.746711,8396.962679,0.000000,8497.210887,5642.628181,0.000000,2080.632193,5613.764197,3403.882500,0.000000,700.014736,4749.959737,5771.501307,0.0,1550.027224,3943.161781,4740.704249,0.000000,2876.451484,2211.339871,7268.424621,0.000000,0.000000,0.000000,5967.497088,3368.688314,0.000000,0.000000,3973.117052,10624.021648,0.000000,0.000000,3851.947038,437.132205,1193.201689,3763.848437,5342.611173,13367.764695,0.000000,5325.161163,2202.457405,0.000000,0.000000,0.000000,1597.373218,0.000000,5990.425572,0.000000,478.437053,3716.467089,5632.775115,92.913297,3873.329613,9473.249882,5421.528128,8623.504419,2460.679186,26285.612072,505.973421,3914.349726,682.349632,0.0,0.000000,0.000000,5720.998216,0.0,0.000000,3689.418825,3572.016324,0.000000,0.000000,1064.647753,3411.483048,0.0,0.000000,6183.302934,5321.485588,7125.905787,714.796039,5294.940528,3154.947185,0.000000,1513.510789,2476.224823,1820.352221,0.000000,5688.489303,0.000000,3674.950582,0.000000,9212.097917,5513.817533,2382.291321,0.000000,14475.875293,7352.724077,4494.199866,0.00000,1696.794754,1002.494960,3210.306094,6284.860943,4047.783377,0.000000,2750.545133,9663.892420,0.000000,0.0,1966.304768,3227.985961,5243.443694,1482.464501,3124.248877,8970.433396,0.000000,5713.944532,0.000000,0.000000,0.000000,2909.251216,142.435644,3298.271574,0.000000,0.000000,4834.273966,4055.614778,4222.825938,0.000000,7318.036946,1800.302647,0.000000,0.000000,4414.552016,2540.818109,0.000000,420.141904,4006.734279,0.0,0.000000,6702.334122,10886.918680,0.0,0.000000,0.000000,8924.742940,0.000000,0.000000,0.000000,7058.918910,0.0,0.00000,7120.914068,10890.231544,8344.962184,0.000000,9451.469788,8467.276831,0.0,2635.617394,6670.678379,5502.484893,0.0,0.000000,9520.210696,7790.164970,0.0,0.000000,917.478693,7762.593448,0.0,0.000000,0.000000,9945.903083,0.000000,0.000000,0.000000,9199.872398,1047.558919,0.000000,0.000000,5019.709297,9922.833580,0.000000,2165.391864,6798.052400,0.000000,0.000000,6344.952156,8388.420012,13159.074583,0.000000,4010.119876,6556.608705,0.000000,0.000000,0.000000,4619.015686,0.000000,9998.856283,2649.639871,2022-06-01-THYMUS-ARCHITECTURE-T098_1,80,21.217173,8.015275,80,10,Auto,2,-1,-1,NaN,NaN
3,3,2022-06-01-THYMUS-ARCHITECTURE-T098,1,3,4.0,1.0,1.0,1718,3139,0.0,1718.0,3139.0,70.0,38.0,32.0,18316.213387,0.000000,0.000000,3085.231697,20617.472441,10182.937768,18553.981548,8911.866964,18573.123257,0.000000,0.000000,0.000000,22620.301644,0.0,0.00000,24170.493605,24427.690948,0.0,8434.801320,21031.724406,23221.903526,16964.501136,0.000000,0.000000,24393.851532,0.0,5538.899894,0.000000,30925.315812,17397.060373,705.663522,15221.072404,24017.606902,0.000000,0.000000,0.000000,25996.663680,0.000000,7226.783820,0.000000,24276.029568,0.0,11859.954956,0.000000,25184.484582,0.000000,8211.788262,0.000000,24805.504834,0.000000,0.000000,0.000000,24193.622601,0.000000,0.000000,47243.301510,18504.152666,19787.050708,0.000000,0.000000,14967.092888,6964.624051,16355.955888,4900.115392,14267.807841,25564.254097,6698.606588,0.000000,18939.488246,0.000000,2739.163791,1950.187935,15176.371426,19026.794833,0.000000,12898.720379,17565.002005,0.000000,1570.150077,0.000000,21322.919765,23445.431836,16110.341399,8453.783928,19478.284206,0.000000,0.000000,0.000000,23135.389638,0.0,0.000000,0.000000,25618.474705,0.0,4012.394754,11932.856917,22919.022181,13775.162178,0.000000,609.589021,24904.962907,0.0,1863.661606,0.000000,31676.472274,24963.539676,1176.834978,30177.063054,23477.092148,0.000000,0.000000,0.000000,25400.827713,0.000000,21673.623090,0.000000,25331.607487,0.000000,31918.792996,1154.358869,24563.103125,0.000000,417.412283,0.000000,25784.394747,0.00000,217.054651,0.000000,24095.747952,0.000000,7800.605767,39621.598969,19301.681600,30747.211125,0.000000,0.0,15666.145292,8873.005435,16922.044957,2973.470022,15528.388992,14322.428901,10147.996922,0.000000,19390.626424,1090.152737,764.840489,8387.020890,15513.980488,19895.617133,0.000000,14249.694978,15814.615812,0.000000,0.000000,5859.903469,15694.761748,300.120186,15798.301579,4792.734764,13414.012634,126.352840,1245.033445,0.000000,16103.858390,0.0,0.000000,29473.512297,16457.713211,0.0,11194.242329,17706.515535,18080.021464,14157.972309,1613.835096,0.000000,18697.429892,0.0,5722.37045,0.000000,21717.212620,7878.442145,506.492703,2034.321969,18643.835232,0.0,0.000000,0.000000,19665.399070,0.0,0.000000,0.000000,16480.759648,0.0,1869.582110,0.000000,19715.072476,0.0,8125.541199,0.000000,17456.029145,0.000000,0.000000,0.000000,18101.049286,0.000000,0.000000,36399.061774,13989.828296,7967.658923,0.000000,0.000000,12325.239738,4362.544864,12663.765387,5534.954764,10839.924028,22952.755752,1884.071226,0.000000,14861.595538,0.000000,4588.622007,0.000000,13675.378250,6741.791687,0.000000,10771.035362,2022-06-01-THYMUS-ARCHITECTURE-T098_1,134,1.729497,17.368380,134,21,SPs,12,3,0,-37.102400,7.127068
4,4,2022-06-01-THYMUS-ARCHITECTURE-T098,1,4,5.0,1.0,1.0,3809,2617,0.0,3809.0,2617.0,101.0,57.0,44.0,8682.313240,3225.786540,10122.476575,2511.492849,14451.950781,3784.416135,1202.797810,3854.521170,11707.041466,0.000000,0.000000,13831.972176,11156.438046,0.0,0.00000,0.000000,16098.248500,0.0,0.000000,2206.445703,13552.943172,0.000000,0.000000,12853.510928,11965.341290,0.0,0.000000,0.000000,16392.954489,0.000000,0.000000,0.000000,11623.085303,0.000000,0.000000,809.715315,11292.199223,0.000000,8055.384817,11962.645623,14935.728269,0.0,10090.457636,0.000000,12601.367484,0.000000,2983.570883,0.000000,15828.209143,0.000000,23.660466,3821.060894,13059.990930,4057.220371,11245.050971,0.000000,11053.575918,6634.076681,0.000000,0.000000,10363.111780,6936.203555,881.550070,0.000000,10402.199882,0.000000,4526.438916,0.000000,9205.120460,362.124149,640.402933,0.000000,5919.413379,7363.688695,0.000000,6774.788369,7249.016149,2648.433678,5191.512284,3601.283155,13426.731032,0.000000,0.000000,6004.659975,9261.434193,0.000000,0.000000,3951.862888,9384.876566,0.0,0.000000,0.000000,13984.240518,0.0,0.000000,0.000000,11754.686820,0.000000,0.000000,0.000000,10398.570070,0.0,654.386447,0.000000,13446.736429,0.000000,0.000000,0.000000,9184.603358,0.000000,0.000000,0.000000,9504.152526,0.000000,0.000000,5497.303258,11813.043514,0.000000,0.000000,0.000000,10752.512682,0.000000,0.000000,0.000000,14196.405885,0.00000,0.000000,0.000000,11001.400554,0.000000,992.069272,0.000000,10087.628944,0.000000,0.000000,0.0,8919.482636,0.000000,0.000000,6349.265618,9084.405210,0.000000,0.000000,0.000000,8723.178144,0.000000,0.000000,951.408539,4672.535959,7718.112975,0.000000,5951.536175,10148.531448,3796.727283,14244.405566,339.992032,13393.625182,6439.074907,2982.961425,327.227854,13737.805783,0.000000,0.000000,15762.969000,12026.061890,0.0,1327.640768,2851.081594,15529.183245,0.0,0.000000,8248.112629,13542.682264,0.000000,0.000000,14751.851378,12617.996247,0.0,0.00000,3404.413832,17358.719576,2292.710626,0.000000,1366.789420,13389.515682,0.0,0.000000,5090.968254,12071.660597,0.0,9200.524965,11553.398297,16698.990564,0.0,10479.283598,2119.366585,13006.333609,0.0,3353.034377,1257.869246,14767.885283,1712.342905,1002.227453,5770.237038,13571.834803,8430.853312,11988.398349,0.000000,11039.048747,10820.274390,1336.187823,0.000000,11895.889505,10815.974528,1851.727328,0.000000,11638.935535,3718.387562,8444.033537,1855.409436,9034.845771,6175.710430,6260.141463,0.000000,8638.068143,2667.740675,0.000000,8649.639561,2022-06-01-THYMUS-ARCHITECTURE-T098_1,148,18.271640,8.451493,148,10,Auto,2,-1,-1,NaN,NaN

In [9]:
# Print the first few rows of each dataframe.
i=3
print(f"Dataframe {os.listdir(INPUT_DATA_PATH)[i]}:")
df_list[i].head()

Dataframe MultiRun-CombinedDataT098.csv:

,CellID,RunID,RegionID,RegCellID,cell_id:cell_id,region:region,tile_num:tile_num,x:x,y:y,z:z,x_tile:x_tile,y_tile:y_tile,size:size,interior:interior,border:border,cyc001_ch001f:DAPI-01,cyc001_ch002f:Blank,cyc001_ch003f:Blank,cyc001_ch004f:Blank,cyc002_ch001f:DAPI-02,cyc002_ch002f:CD45,"cyc002_ch003f:HLA-A,B,C",cyc002_ch004f:TCRgd,cyc003_ch001f:DAPI-03,cyc003_ch002f:Cytokeratin5/8,cyc003_ch003f:SATB1,cyc003_ch004f:CD25,cyc004_ch001f:DAPI-04,cyc004_ch002f:CD19,cyc004_ch003f:JAG2,cyc004_ch004f:EPCAM,cyc005_ch001f:DAPI-05,cyc005_ch002f:SMA,cyc005_ch003f:CD86,cyc005_ch004f:CD45RA,cyc006_ch001f:DAPI-06,cyc006_ch002f:CD5,cyc006_ch003f:PD-L1,cyc006_ch004f:CD38,cyc007_ch001f:DAPI-07,cyc007_ch002f:ICAM/Caspase3,cyc007_ch003f:CD31,cyc007_ch004f:IL7R,cyc008_ch001f:DAPI-08,cyc008_ch002f:CD3,cyc008_ch003f:PD1,cyc008_ch004f:AIRE,cyc009_ch001f:DAPI-09,cyc009_ch002f:CD11c,cyc009_ch003f:COL4,cyc009_ch004f:PDGFRa,cyc010_ch001f:DAPI-10,cyc010_ch002f:CD7,cyc010_ch003f:CD4,cyc010_ch004f:CD20,cyc011_ch001f:DAPI-11,cyc011_ch002f:DLL1,cyc011_ch003f:CD80,cyc011_ch004f:Laminin,cyc012_ch001f:DAPI-12,cyc012_ch002f:CD1a,cyc012_ch003f:CD8a,cyc012_ch004f:CCR7,cyc013_ch001f:DAPI-13,cyc013_ch002f:CD68,cyc013_ch003f:VCAM,cyc013_ch004f:MCAM,cyc014_ch001f:DAPI-14,cyc014_ch002f:CD29,cyc014_ch003f:CD45RO,cyc014_ch004f:IgM,cyc015_ch001f:DAPI-15,cyc015_ch002f:CD44,cyc015_ch003f:DLL4,cyc015_ch004f:Empty,cyc016_ch001f:DAPI-16,"cyc016_ch002f:HLA-DR,DP,DQ",cyc016_ch003f:CD40,cyc016_ch004f:CD62L,cyc017_ch001f:DAPI-17,cyc017_ch002f:CD28,cyc017_ch003f:JAG1,cyc017_ch004f:Ki67,cyc018_ch001f:DAPI-18,cyc018_ch002f:Blank,cyc018_ch003f:Blank,cyc018_ch004f:Blank,cyc019_ch001f:DAPI-19,cyc019_ch002f:Blank,cyc019_ch003f:Blank,cyc019_ch004f:DRAQ5,cyc001_ch001i:DAPI-01_interior,cyc001_ch002i:Blank_interior,cyc001_ch003i:Blank_interior,cyc001_ch004i:Blank_interior,cyc002_ch001i:DAPI-02_interior,cyc002_ch002i:CD45_interior,"cyc002_ch003i:HLA-A,B,C_interior",cyc002_ch004i:TCRgd_interior,cyc003_ch001i:DAPI-03_interior,cyc003_ch002i:Cytokeratin5/8_interior,cyc003_ch003i:SATB1_interior,cyc003_ch004i:CD25_interior,cyc004_ch001i:DAPI-04_interior,cyc004_ch002i:CD19_interior,cyc004_ch003i:JAG2_interior,cyc004_ch004i:EPCAM_interior,cyc005_ch001i:DAPI-05_interior,cyc005_ch002i:SMA_interior,cyc005_ch003i:CD86_interior,cyc005_ch004i:CD45RA_interior,cyc006_ch001i:DAPI-06_interior,cyc006_ch002i:CD5_interior,cyc006_ch003i:PD-L1_interior,cyc006_ch004i:CD38_interior,cyc007_ch001i:DAPI-07_interior,cyc007_ch002i:ICAM/Caspase3_interior,cyc007_ch003i:CD31_interior,cyc007_ch004i:IL7R_interior,cyc008_ch001i:DAPI-08_interior,cyc008_ch002i:CD3_interior,cyc008_ch003i:PD1_interior,cyc008_ch004i:AIRE_interior,cyc009_ch001i:DAPI-09_interior,cyc009_ch002i:CD11c_interior,cyc009_ch003i:COL4_interior,cyc009_ch004i:PDGFRa_interior,cyc010_ch001i:DAPI-10_interior,cyc010_ch002i:CD7_interior,cyc010_ch003i:CD4_interior,cyc010_ch004i:CD20_interior,cyc011_ch001i:DAPI-11_interior,cyc011_ch002i:DLL1_interior,cyc011_ch003i:CD80_interior,cyc011_ch004i:Laminin_interior,cyc012_ch001i:DAPI-12_interior,cyc012_ch002i:CD1a_interior,cyc012_ch003i:CD8a_interior,cyc012_ch004i:CCR7_interior,cyc013_ch001i:DAPI-13_interior,cyc013_ch002i:CD68_interior,cyc013_ch003i:VCAM_interior,cyc013_ch004i:MCAM_interior,cyc014_ch001i:DAPI-14_interior,cyc014_ch002i:CD29_interior,cyc014_ch003i:CD45RO_interior,cyc014_ch004i:IgM_interior,cyc015_ch001i:DAPI-15_interior,cyc015_ch002i:CD44_interior,cyc015_ch003i:DLL4_interior,cyc015_ch004i:Empty_interior,cyc016_ch001i:DAPI-16_interior,"cyc016_ch002i:HLA-DR,DP,DQ_interior",cyc016_ch003i:CD40_interior,cyc016_ch004i:CD62L_interior,cyc017_ch001i:DAPI-17_interior,cyc017_ch002i:CD28_interior,cyc017_ch003i:JAG1_interior,cyc017_ch004i:Ki67_interior,cyc018_ch001i:DAPI-18_interior,cyc018_ch002i:Blank_interior,cyc018_ch003i:Blank_interior,cyc018_ch004i:Blank_interior,cyc019_ch001i:DAPI-19_interior,cyc019_ch002i:Blank_interior,cyc019_ch003i:Blank_interior,cyc019_ch004i:DRAQ5_interior,cyc001_ch001b:DAPI-01_border,cyc001_ch002b:Blank_border,cyc001_ch003b:Blank_border,cyc001_ch004b:Blank_border,cyc002_ch001b:DAPI-02_border,cyc002_ch002b:CD45_border,"cyc002_ch003b:HLA-A,B,C_border",cyc002_ch004b:TCRgd_border,cyc003_ch001b:DAPI-03_border,cyc003_ch002b:Cytokeratin5/8_border,cyc003_ch003b:SATB1_border,cyc003_ch004b:CD25_border,cyc004_ch001b:DAPI-04_border,cyc004_ch002b:CD19_border,cyc004_ch003b:JAG2_border,cyc004_ch004b:EPCAM_border,cyc005_ch001b:DAPI-05_border,cyc005_ch002b:SMA_border,cyc005_ch003b:CD86_border,cyc005_ch004b:CD45RA_border,cyc006_ch001b:DAPI-06_border,cyc006_ch002b:CD5_border,cyc006_ch003b:PD-L1_border,cyc006_ch004b:CD38_border,cyc007_ch001b:DAPI-07_border,cyc007_ch002b:ICAM/Caspase3_border,cyc007_ch003b:CD31_border,cyc007_ch004b:IL7R_border,cyc008_ch001b:DAPI-08_border,cyc008_ch002b:CD3_border,cyc008_ch003b:PD1_border,cyc008_ch004b:AIRE_border,cyc009_ch001b:DAPI-09_border,cyc009_ch002b:CD11c_border,cyc009_ch003b:COL4_border,cyc009_ch004b:PDGFRa_border,cyc010_ch001b:DAPI-10_border,cyc010_ch002b:CD7_border,cyc010_ch003b:CD4_border,cyc010_ch004b:CD20_border,cyc011_ch001b:DAPI-11_border,cyc011_ch002b:DLL1_border,cyc011_ch003b:CD80_border,cyc011_ch004b:Laminin_border,cyc012_ch001b:DAPI-12_border,cyc012_ch002b:CD1a_border,cyc012_ch003b:CD8a_border,cyc012_ch004b:CCR7_border,cyc013_ch001b:DAPI-13_border,cyc013_ch002b:CD68_border,cyc013_ch003b:VCAM_border,cyc013_ch004b:MCAM_border,cyc014_ch001b:DAPI-14_border,cyc014_ch002b:CD29_border,cyc014_ch003b:CD45RO_border,cyc014_ch004b:IgM_border,cyc015_ch001b:DAPI-15_border,cyc015_ch002b:CD44_border,cyc015_ch003b:DLL4_border,cyc015_ch004b:Empty_border,cyc016_ch001b:DAPI-16_border,"cyc016_ch002b:HLA-DR,DP,DQ_border",cyc016_ch003b:CD40_border,cyc016_ch004b:CD62L_border,cyc017_ch001b:DAPI-17_border,cyc017_ch002b:CD28_border,cyc017_ch003b:JAG1_border,cyc017_ch004b:Ki67_border,cyc018_ch001b:DAPI-18_border,cyc018_ch002b:Blank_border,cyc018_ch003b:Blank_border,cyc018_ch004b:Blank_border,cyc019_ch001b:DAPI-19_border,cyc019_ch002b:Blank_border,cyc019_ch003b:Blank_border,cyc019_ch004b:DRAQ5_border,tissueID,louvain_hf,umap_1,umap_2,clusterID,mergedID,CelltypeName,CelltypeID,kmeans_neighborhood,knn_niche,knn_umap_X,knn_umap_Y
0,0,2022-06-01-THYMUS-ARCHITECTURE-T098,1,0,1.0,1.0,1.0,821,447,0.0,821.0,447.0,89.0,50.0,39.0,0.000000,3066.562772,20589.468424,6502.766869,675.007002,0.000000,6588.201042,22946.397286,0.000000,4534.640049,17154.854439,10197.728909,0.000000,0.0,2409.43407,6898.027886,498.108599,0.0,0.000000,2427.957250,1528.828535,0.000000,1523.612753,4774.983849,1104.828677,0.0,0.000000,0.000000,4425.795720,4298.097377,0.000000,1549.674712,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7340.797149,0.000000,2939.395516,0.0,13474.948394,8858.903666,0.000000,1333.392753,37756.015511,9806.639084,1920.882211,1782.928654,3758.995970,8159.576461,1615.155063,18375.680873,0.000000,6037.581253,0.000000,2238.429524,9618.657514,7656.931369,0.000000,11866.039629,7049.108729,16837.082617,0.000000,2699.396127,7077.591460,32082.408915,537.817525,782.972177,6760.247612,3916.772574,0.000000,10847.169133,659.667582,2658.526218,0.000000,2972.235593,20258.744691,0.000000,0.000000,0.000000,10917.870304,25276.608631,0.000000,7293.677595,15289.714888,10849.463385,0.000000,0.0,875.874567,21210.177888,0.000000,0.0,0.000000,2078.324384,0.000000,0.000000,1445.836181,4669.861291,0.000000,0.0,0.000000,2698.540407,1469.057992,0.000000,0.000000,8702.877547,0.000000,0.000000,0.000000,8592.090380,0.000000,2842.810808,6824.795149,3222.545850,456.296312,0.000000,13338.387324,13608.625619,0.000000,3643.196687,55722.081731,5311.771435,377.923589,0.00000,8555.563087,8071.192697,0.000000,28640.707360,1500.671910,8083.537556,0.000000,5334.544302,12111.274536,0.0,0.000000,21037.967142,13102.667222,12573.740334,0.000000,0.000000,8220.776818,27278.993627,0.000000,2219.624193,7663.338004,5095.211131,0.000000,16533.083217,706.432961,0.000000,1020.984690,3012.909375,18878.298626,14660.821686,6430.822770,0.000000,2373.568094,10522.178511,3269.016189,3147.200611,16754.445247,4425.206296,3727.001464,0.0,2945.203318,0.000000,5440.569867,0.0,0.000000,1795.343423,6920.320573,0.000000,1256.770583,3306.413360,7131.534347,0.0,0.00000,0.000000,10085.989379,7264.813409,0.000000,0.000000,6197.617428,0.0,0.000000,0.000000,5060.757473,0.0,4875.446661,0.000000,8596.246701,0.0,9682.769282,1187.372878,5903.398996,0.0,22252.182541,9250.671354,6128.516947,4825.872136,1208.203066,4662.271044,6855.791321,6704.397347,0.000000,2758.724416,5185.491893,0.000000,5233.041707,13830.802689,2684.053294,4656.611926,2528.898420,17319.966835,4202.730751,5781.981908,4096.665985,39545.925704,7244.003788,0.000000,4692.500976,1261.499573,2948.305823,0.000000,550.599608,9299.828410,2022-06-01-THYMUS-ARCHITECTURE-T098_1,77,9.186737,11.784051,77,7,Class II+ DPs,4,1,3,-38.927532,13.051946
1,1,2022-06-01-THYMUS-ARCHITECTURE-T098,1,1,2.0,1.0,1.0,1996,1274,0.0,1996.0,1274.0,87.0,47.0,40.0,5833.210540,558.286388,3552.838477,2584.691652,7028.910730,496.411615,8956.837849,0.000000,6757.025778,0.000000,0.000000,0.000000,7319.227175,0.0,0.00000,0.000000,10393.830129,0.0,3770.654587,1047.621158,13039.831362,0.000000,0.000000,0.000000,7601.566942,0.0,0.000000,3399.039994,12939.999021,3839.230783,847.154454,0.000000,9098.364267,4292.152444,0.000000,4768.424949,10337.150148,868.496483,0.000000,1534.560439,11200.293681,0.0,0.000000,760.958443,7806.023059,0.000000,0.000000,0.000000,8758.019272,0.000000,0.000000,517.641590,10403.063403,0.000000,0.000000,0.000000,5475.536882,6083.370050,0.000000,1076.636738,4387.811048,2149.387258,7685.612648,0.000000,2814.215649,0.000000,0.000000,0.000000,6745.150275,10953.895680,13224.706704,663.620336,5143.037472,0.000000,14578.890847,4575.024899,10047.698749,803.224527,5467.849143,9058.836097,11310.237381,0.000000,9644.075929,847.675338,10991.460444,0.000000,0.000000,0.000000,10745.433085,0.0,0.000000,0.000000,13732.459657,0.0,732.211398,0.000000,17367.956510,2279.565172,0.000000,0.000000,12312.864804,0.0,0.000000,0.000000,16909.342301,10632.546303,0.000000,0.000000,13728.782545,14217.950435,0.000000,0.000000,14308.917623,5875.671724,0.000000,1976.712539,14633.218071,6606.535647,0.000000,0.000000,12348.547898,3403.705919,0.000000,0.000000,12414.771372,2155.55751,0.000000,0.000000,14428.081195,0.000000,0.000000,0.000000,9208.222339,5509.592751,0.000000,0.0,8079.338073,3161.764484,6589.259815,0.000000,6843.746034,0.000000,842.849500,0.000000,9757.470685,12692.037182,15250.267633,11301.237124,7886.548536,914.282549,3084.764830,6466.075912,26.608933,91.754277,611.728318,0.000000,1165.520034,0.000000,6251.421503,0.000000,739.174256,0.000000,0.000000,139.505956,2238.093969,0.0,0.000000,0.000000,4581.950771,0.0,6191.572077,2680.495106,4857.098721,0.000000,0.000000,0.000000,1453.238165,0.0,0.00000,18771.756398,5430.349019,0.000000,3197.190000,0.000000,1686.837182,0.0,0.000000,12989.909583,3071.354317,0.0,0.000000,1046.525504,4747.710363,0.0,0.000000,3959.093694,1316.739086,0.0,0.000000,0.000000,3337.952345,0.000000,0.000000,1604.725187,3404.249740,0.000000,0.000000,2106.736819,763.172925,3676.862560,0.000000,3282.851250,0.000000,934.794640,6340.161288,2928.768707,0.000000,0.000000,0.000000,0.000000,2517.425756,7802.814877,9118.434221,0.000000,1933.927349,0.000000,15149.814046,3752.831491,2022-06-01-THYMUS-ARCHITECTURE-T098_1,0,19.961880,8.410901,191,10,Auto,2,-1,-1,NaN,NaN
2,2,2022-06-01-THYMUS-ARCHITECTURE-T098,1,2,3.0,1.0,1.0,4338,1480,0.0,4338.0,1480.0,112.0,71.0,41.0,2008.679247,3863.597372,5161.734796,0.000000,5659.552805,4843.069172,1934.679304,4753.697940,3541.485045,10865.478030,0.000000,2752.101215,1912.313783,0.0,0.00000,3874.851813,8661.779679,0.0,0.000000,193.548822,6134.997889,0.000000,0.000000,120.665999,5205.210803,0.0,0.000000,8842.890881,8272.746711,8396.962679,0.000000,8497.210887,5642.628181,0.000000,2080.632193,5613.764197,3403.882500,0.000000,700.014736,4749.959737,5771.501307,0.0,1550.027224,3943.161781,4740.704249,0.000000,2876.451484,2211.339871,7268.424621,0.000000,0.000000,0.000000,5967.497088,3368.688314,0.000000,0.000000,3973.117052,10624.021648,0.000000,0.000000,3851.947038,437.132205,1193.201689,3763.848437,5342.611173,13367.764695,0.000000,5325.161163,2202.457405,0.000000,0.000000,0.000000,1597.373218,0.000000,5990.425572,0.000000,478.437053,3716.467089,5632.775115,92.913297,3873.329613,9473.249882,5421.528128,8623.504419,2460.679186,26285.612072,505.973421,3914.349726,682.349632,0.0,0.000000,0.000000,5720.998216,0.0,0.000000,3689.418825,3572.016324,0.000000,0.000000,1064.647753,3411.483048,0.0,0.000000,6183.302934,5321.485588,7125.905787,714.796039,5294.940528,3154.947185,0.000000,1513.510789,2476.224823,1820.352221,0.000000,5688.489303,0.000000,3674.950582,0.000000,9212.097917,5513.817533,2382.291321,0.000000,14475.875293,7352.724077,4494.199866,0.00000,1696.794754,1002.494960,3210.306094,6284.860943,4047.783377,0.000000,2750.545133,9663.892420,0.000000,0.0,1966.304768,3227.985961,5243.443694,1482.464501,3124.248877,8970.433396,0.000000,5713.944532,0.000000,0.000000,0.000000,2909.251216,142.435644,3298.271574,0.000000,0.000000,4834.273966,4055.614778,4222.825938,0.000000,7318.036946,1800.302647,0.000000,0.000000,4414.552016,2540.818109,0.000000,420.141904,4006.734279,0.0,0.000000,6702.334122,10886.918680,0.0,0.000000,0.000000,8924.742940,0.000000,0.000000,0.000000,7058.918910,0.0,0.00000,7120.914068,10890.231544,8344.962184,0.000000,9451.469788,8467.276831,0.0,2635.617394,6670.678379,5502.484893,0.0,0.000000,9520.210696,7790.164970,0.0,0.000000,917.478693,7762.593448,0.0,0.000000,0.000000,9945.903083,0.000000,0.000000,0.000000,9199.872398,1047.558919,0.000000,0.000000,5019.709297,9922.833580,0.000000,2165.391864,6798.052400,0.000000,0.000000,6344.952156,8388.420012,13159.074583,0.000000,4010.119876,6556.608705,0.000000,0.000000,0.000000,4619.015686,0.000000,9998.856283,2649.639871,2022-06-01-THYMUS-ARCHITECTURE-T098_1,80,21.217173,8.015275,80,10,Auto,2,-1,-1,NaN,NaN
3,3,2022-06-01-THYMUS-ARCHITECTURE-T098,1,3,4.0,1.0,1.0,1718,3139,0.0,1718.0,3139.0,70.0,38.0,32.0,18316.213387,0.000000,0.000000,3085.231697,20617.472441,10182.937768,18553.981548,8911.866964,18573.123257,0.000000,0.000000,0.000000,22620.301644,0.0,0.00000,24170.493605,24427.690948,0.0,8434.801320,21031.724406,23221.903526,16964.501136,0.000000,0.000000,24393.851532,0.0,5538.899894,0.000000,30925.315812,17397.060373,705.663522,15221.072404,24017.606902,0.000000,0.000000,0.000000,25996.663680,0.000000,7226.783820,0.000000,24276.029568,0.0,11859.954956,0.000000,25184.484582,0.000000,8211.788262,0.000000,24805.504834,0.000000,0.000000,0.000000,24193.622601,0.000000,0.000000,47243.301510,18504.152666,19787.050708,0.000000,0.000000,14967.092888,6964.624051,16355.955888,4900.115392,14267.807841,25564.254097,6698.606588,0.000000,18939.488246,0.000000,2739.163791,1950.187935,15176.371426,19026.794833,0.000000,12898.720379,17565.002005,0.000000,1570.150077,0.000000,21322.919765,23445.431836,16110.341399,8453.783928,19478.284206,0.000000,0.000000,0.000000,23135.389638,0.0,0.000000,0.000000,25618.474705,0.0,4012.394754,11932.856917,22919.022181,13775.162178,0.000000,609.589021,24904.962907,0.0,1863.661606,0.000000,31676.472274,24963.539676,1176.834978,30177.063054,23477.092148,0.000000,0.000000,0.000000,25400.827713,0.000000,21673.623090,0.000000,25331.607487,0.000000,31918.792996,1154.358869,24563.103125,0.000000,417.412283,0.000000,25784.394747,0.00000,217.054651,0.000000,24095.747952,0.000000,7800.605767,39621.598969,19301.681600,30747.211125,0.000000,0.0,15666.145292,8873.005435,16922.044957,2973.470022,15528.388992,14322.428901,10147.996922,0.000000,19390.626424,1090.152737,764.840489,8387.020890,15513.980488,19895.617133,0.000000,14249.694978,15814.615812,0.000000,0.000000,5859.903469,15694.761748,300.120186,15798.301579,4792.734764,13414.012634,126.352840,1245.033445,0.000000,16103.858390,0.0,0.000000,29473.512297,16457.713211,0.0,11194.242329,17706.515535,18080.021464,14157.972309,1613.835096,0.000000,18697.429892,0.0,5722.37045,0.000000,21717.212620,7878.442145,506.492703,2034.321969,18643.835232,0.0,0.000000,0.000000,19665.399070,0.0,0.000000,0.000000,16480.759648,0.0,1869.582110,0.000000,19715.072476,0.0,8125.541199,0.000000,17456.029145,0.000000,0.000000,0.000000,18101.049286,0.000000,0.000000,36399.061774,13989.828296,7967.658923,0.000000,0.000000,12325.239738,4362.544864,12663.765387,5534.954764,10839.924028,22952.755752,1884.071226,0.000000,14861.595538,0.000000,4588.622007,0.000000,13675.378250,6741.791687,0.000000,10771.035362,2022-06-01-THYMUS-ARCHITECTURE-T098_1,134,1.729497,17.368380,134,21,SPs,12,3,0,-37.102400,7.127068
4,4,2022-06-01-THYMUS-ARCHITECTURE-T098,1,4,5.0,1.0,1.0,3809,2617,0.0,3809.0,2617.0,101.0,57.0,44.0,8682.313240,3225.786540,10122.476575,2511.492849,14451.950781,3784.416135,1202.797810,3854.521170,11707.041466,0.000000,0.000000,13831.972176,11156.438046,0.0,0.00000,0.000000,16098.248500,0.0,0.000000,2206.445703,13552.943172,0.000000,0.000000,12853.510928,11965.341290,0.0,0.000000,0.000000,16392.954489,0.000000,0.000000,0.000000,11623.085303,0.000000,0.000000,809.715315,11292.199223,0.000000,8055.384817,11962.645623,14935.728269,0.0,10090.457636,0.000000,12601.367484,0.000000,2983.570883,0.000000,15828.209143,0.000000,23.660466,3821.060894,13059.990930,4057.220371,11245.050971,0.000000,11053.575918,6634.076681,0.000000,0.000000,10363.111780,6936.203555,881.550070,0.000000,10402.199882,0.000000,4526.438916,0.000000,9205.120460,362.124149,640.402933,0.000000,5919.413379,7363.688695,0.000000,6774.788369,7249.016149,2648.433678,5191.512284,3601.283155,13426.731032,0.000000,0.000000,6004.659975,9261.434193,0.000000,0.000000,3951.862888,9384.876566,0.0,0.000000,0.000000,13984.240518,0.0,0.000000,0.000000,11754.686820,0.000000,0.000000,0.000000,10398.570070,0.0,654.386447,0.000000,13446.736429,0.000000,0.000000,0.000000,9184.603358,0.000000,0.000000,0.000000,9504.152526,0.000000,0.000000,5497.303258,11813.043514,0.000000,0.000000,0.000000,10752.512682,0.000000,0.000000,0.000000,14196.405885,0.00000,0.000000,0.000000,11001.400554,0.000000,992.069272,0.000000,10087.628944,0.000000,0.000000,0.0,8919.482636,0.000000,0.000000,6349.265618,9084.405210,0.000000,0.000000,0.000000,8723.178144,0.000000,0.000000,951.408539,4672.535959,7718.112975,0.000000,5951.536175,10148.531448,3796.727283,14244.405566,339.992032,13393.625182,6439.074907,2982.961425,327.227854,13737.805783,0.000000,0.000000,15762.969000,12026.061890,0.0,1327.640768,2851.081594,15529.183245,0.0,0.000000,8248.112629,13542.682264,0.000000,0.000000,14751.851378,12617.996247,0.0,0.00000,3404.413832,17358.719576,2292.710626,0.000000,1366.789420,13389.515682,0.0,0.000000,5090.968254,12071.660597,0.0,9200.524965,11553.398297,16698.990564,0.0,10479.283598,2119.366585,13006.333609,0.0,3353.034377,1257.869246,14767.885283,1712.342905,1002.227453,5770.237038,13571.834803,8430.853312,11988.398349,0.000000,11039.048747,10820.274390,1336.187823,0.000000,11895.889505,10815.974528,1851.727328,0.000000,11638.935535,3718.387562,8444.033537,1855.409436,9034.845771,6175.710430,6260.141463,0.000000,8638.068143,2667.740675,0.000000,8649.639561,2022-06-01-THYMUS-ARCHITECTURE-T098_1,148,18.271640,8.451493,148,10,Auto,2,-1,-1,NaN,NaN

In [10]:
# Print the first few rows of each dataframe.
i=4
print(f"Dataframe {os.listdir(INPUT_DATA_PATH)[i]}:")
df_list[i].head()

Dataframe MultiRun-CombinedData 2.csv:

,CellID,RunID,RegionID,RegCellID,cell_id:cell_id,region:region,tile_num:tile_num,x:x,y:y,z:z,x_tile:x_tile,y_tile:y_tile,size:size,interior:interior,border:border,cyc001_ch001:DAPI-01,cyc001_ch002:Blank,cyc001_ch003:Blank,cyc001_ch004:Blank,cyc002_ch001:DAPI-02,cyc002_ch002:CD45,"cyc002_ch003:HLA-A,B,C",cyc002_ch004:HES4,cyc003_ch001:DAPI-03,cyc003_ch002:Cytokeratin 5/8,cyc003_ch003:SATB1,cyc003_ch004:FOXP3,cyc004_ch001:DAPI-04,cyc004_ch002:CD19,cyc004_ch003:JAG2,cyc004_ch004:CD326,cyc005_ch001:DAPI-05,cyc005_ch002:SMA,cyc005_ch003:CD86,cyc005_ch004:CD45RA,cyc006_ch001:DAPI-06,cyc006_ch002:CD11b,cyc006_ch003:TCRgd,cyc006_ch004:PDGFRa,cyc007_ch001:DAPI-07,cyc007_ch002:CD5,cyc007_ch003:CD274,cyc007_ch004:CD38,cyc008_ch001:DAPI-08,cyc008_ch002:CD54,cyc008_ch003:CD31,cyc008_ch004:CD44,cyc009_ch001:DAPI-09,cyc009_ch002:CD3,cyc009_ch003:CD279,cyc009_ch004:Vimentin,cyc010_ch001:DAPI-10,cyc010_ch002:CD11c,cyc010_ch003:COL4,cyc010_ch004:Ki67,cyc011_ch001:DAPI-11,cyc011_ch002:CD7,cyc011_ch003:CD4,cyc011_ch004:CD47,cyc012_ch001:DAPI-12,cyc012_ch002:DLL1,cyc012_ch003:ERTR7,cyc012_ch004:Laminin,cyc013_ch001:DAPI-13,cyc013_ch002:CD1a,cyc013_ch003:CD8a,cyc013_ch004:CD197,cyc014_ch001:DAPI-14,cyc014_ch002:CD68,cyc014_ch003:VCAM,cyc014_ch004:MCAM,cyc015_ch001:DAPI-15,cyc015_ch002:CD29,cyc015_ch003:CD45RO,cyc015_ch004:IgM,cyc016_ch001:DAPI-16,cyc016_ch002:Empty,cyc016_ch003:DLL4,cyc016_ch004:Fibronectin,cyc017_ch001:DAPI-17,"cyc017_ch002:HLA-DR,DP,DQ",cyc017_ch003:CD40,cyc017_ch004:CD62L,cyc018_ch001:DAPI-18,cyc018_ch002:Empty,cyc018_ch003:JAG1,cyc018_ch004:15-PGDH,cyc019_ch001:DAPI-19,cyc019_ch002:Blank,cyc019_ch003:Blank,cyc019_ch004:Blank,cyc020_ch001:DAPI-20,cyc020_ch002:WGA,cyc020_ch003:Empty,cyc020_ch004:DRAQ5,cyc001_ch001:DAPI-01_interior,cyc001_ch002:Blank_interior,cyc001_ch003:Blank_interior,cyc001_ch004:Blank_interior,cyc002_ch001:DAPI-02_interior,cyc002_ch002:CD45_interior,"cyc002_ch003:HLA-A,B,C_interior",cyc002_ch004:HES4_interior,cyc003_ch001:DAPI-03_interior,cyc003_ch002:Cytokeratin 5/8_interior,cyc003_ch003:SATB1_interior,cyc003_ch004:FOXP3_interior,cyc004_ch001:DAPI-04_interior,cyc004_ch002:CD19_interior,cyc004_ch003:JAG2_interior,cyc004_ch004:CD326_interior,cyc005_ch001:DAPI-05_interior,cyc005_ch002:SMA_interior,cyc005_ch003:CD86_interior,cyc005_ch004:CD45RA_interior,cyc006_ch001:DAPI-06_interior,cyc006_ch002:CD11b_interior,cyc006_ch003:TCRgd_interior,cyc006_ch004:PDGFRa_interior,cyc007_ch001:DAPI-07_interior,cyc007_ch002:CD5_interior,cyc007_ch003:CD274_interior,cyc007_ch004:CD38_interior,cyc008_ch001:DAPI-08_interior,cyc008_ch002:CD54_interior,cyc008_ch003:CD31_interior,cyc008_ch004:CD44_interior,cyc009_ch001:DAPI-09_interior,cyc009_ch002:CD3_interior,cyc009_ch003:CD279_interior,cyc009_ch004:Vimentin_interior,cyc010_ch001:DAPI-10_interior,cyc010_ch002:CD11c_interior,cyc010_ch003:COL4_interior,cyc010_ch004:Ki67_interior,cyc011_ch001:DAPI-11_interior,cyc011_ch002:CD7_interior,cyc011_ch003:CD4_interior,cyc011_ch004:CD47_interior,cyc012_ch001:DAPI-12_interior,cyc012_ch002:DLL1_interior,cyc012_ch003:ERTR7_interior,cyc012_ch004:Laminin_interior,cyc013_ch001:DAPI-13_interior,cyc013_ch002:CD1a_interior,cyc013_ch003:CD8a_interior,cyc013_ch004:CD197_interior,cyc014_ch001:DAPI-14_interior,cyc014_ch002:CD68_interior,cyc014_ch003:VCAM_interior,cyc014_ch004:MCAM_interior,cyc015_ch001:DAPI-15_interior,cyc015_ch002:CD29_interior,cyc015_ch003:CD45RO_interior,cyc015_ch004:IgM_interior,cyc016_ch001:DAPI-16_interior,cyc016_ch002:Empty_interior,cyc016_ch003:DLL4_interior,cyc016_ch004:Fibronectin_interior,cyc017_ch001:DAPI-17_interior,"cyc017_ch002:HLA-DR,DP,DQ_interior",cyc017_ch003:CD40_interior,cyc017_ch004:CD62L_interior,cyc018_ch001:DAPI-18_interior,cyc018_ch002:Empty_interior,cyc018_ch003:JAG1_interior,cyc018_ch004:15-PGDH_interior,cyc019_ch001:DAPI-19_interior,cyc019_ch002:Blank_interior,cyc019_ch003:Blank_interior,cyc019_ch004:Blank_interior,cyc020_ch001:DAPI-20_interior,cyc020_ch002:WGA_interior,cyc020_ch003:Empty_interior,cyc020_ch004:DRAQ5_interior,cyc001_ch001:DAPI-01_border,cyc001_ch002:Blank_border,cyc001_ch003:Blank_border,cyc001_ch004:Blank_border,cyc002_ch001:DAPI-02_border,cyc002_ch002:CD45_border,"cyc002_ch003:HLA-A,B,C_border",cyc002_ch004:HES4_border,cyc003_ch001:DAPI-03_border,cyc003_ch002:Cytokeratin 5/8_border,cyc003_ch003:SATB1_border,cyc003_ch004:FOXP3_border,cyc004_ch001:DAPI-04_border,cyc004_ch002:CD19_border,cyc004_ch003:JAG2_border,cyc004_ch004:CD326_border,cyc005_ch001:DAPI-05_border,cyc005_ch002:SMA_border,cyc005_ch003:CD86_border,cyc005_ch004:CD45RA_border,cyc006_ch001:DAPI-06_border,cyc006_ch002:CD11b_border,cyc006_ch003:TCRgd_border,cyc006_ch004:PDGFRa_border,cyc007_ch001:DAPI-07_border,cyc007_ch002:CD5_border,cyc007_ch003:CD274_border,cyc007_ch004:CD38_border,cyc008_ch001:DAPI-08_border,cyc008_ch002:CD54_border,cyc008_ch003:CD31_border,cyc008_ch004:CD44_border,cyc009_ch001:DAPI-09_border,cyc009_ch002:CD3_border,cyc009_ch003:CD279_border,cyc009_ch004:Vimentin_border,cyc010_ch001:DAPI-10_border,cyc010_ch002:CD11c_border,cyc010_ch003:COL4_border,cyc010_ch004:Ki67_border,cyc011_ch001:DAPI-11_border,cyc011_ch002:CD7_border,cyc011_ch003:CD4_border,cyc011_ch004:CD47_border,cyc012_ch001:DAPI-12_border,cyc012_ch002:DLL1_border,cyc012_ch003:ERTR7_border,cyc012_ch004:Laminin_border,cyc013_ch001:DAPI-13_border,cyc013_ch002:CD1a_border,cyc013_ch003:CD8a_border,cyc013_ch004:CD197_border,cyc014_ch001:DAPI-14_border,cyc014_ch002:CD68_border,cyc014_ch003:VCAM_border,cyc014_ch004:MCAM_border,cyc015_ch001:DAPI-15_border,cyc015_ch002:CD29_border,cyc015_ch003:CD45RO_border,cyc015_ch004:IgM_border,cyc016_ch001:DAPI-16_border,cyc016_ch002:Empty_border,cyc016_ch003:DLL4_border,cyc016_ch004:Fibronectin_border,cyc017_ch001:DAPI-17_border,"cyc017_ch002:HLA-DR,DP,DQ_border",cyc017_ch003:CD40_border,cyc017_ch004:CD62L_border,cyc018_ch001:DAPI-18_border,cyc018_ch002:Empty_border,cyc018_ch003:JAG1_border,cyc018_ch004:15-PGDH_border,cyc019_ch001:DAPI-19_border,cyc019_ch002:Blank_border,cyc019_ch003:Blank_border,cyc019_ch004:Blank_border,cyc020_ch001:DAPI-20_border,cyc020_ch002:WGA_border,cyc020_ch003:Empty_border,cyc020_ch004:DRAQ5_border,tissueID,condition,louvain_raw,louvain_hf,umap_1,umap_2,clusterID,mergedID,CelltypeName,CelltypeID,kmeans_neighborhood,knn_niche,knn_umap_X,knn_umap_Y,knn_niche_20,NicheName,knn_niche_30
0,0,20201203_Laura_Thymus_2,1,0,1.0,1.0,1.0,3155,2718,3.0,3155.0,2718.0,265.0,174.0,91.0,2707.998621,0.000000,0.000000,0.000000,1043.068384,882.131623,0.000000,575.471980,1543.630071,2737.624494,0.000000,0.000000,2480.633821,0.000000,4154.455156,0.000000,1858.140054,0.000000,0.0,0.000000,4525.555096,0.000000,0.000000,250.434500,5640.485063,0.000000,1074.023832,6599.478495,5548.300984,0.000000,0.000000,0.000000,3170.757254,109.426226,0.000000,0.000000,6464.809248,0.0,0.000000,5952.000512,2434.969951,0.000000,3375.921330,4429.328921,6920.841569,0.0,0.0,5847.602418,6046.299332,3013.658123,7184.326778,0.000000,8053.505566,0.000000,0.000000,8671.792257,5024.642121,2234.038008,4250.008607,2261.035545,5305.322225,0.000000,4964.796020,0.000000,6068.265268,5568.449114,0.000000,3735.845730,4948.867433,2618.907525,886.930788,1731.186430,6714.868772,2307.811942,2194.220637,1021.253630,3845.326295,4300.968511,0.000000,2027.108677,2402.931673,0.000000,0.0,0.000000,1033.322313,5647.752251,2032.242666,0.0,1324.379132,7438.379049,0.000000,1299.679364,2159.5304,0.000000,6063.466644,1161.739495,1560.623189,0.000000,0.0,437.706170,4131.274055,0.000000,0.000000,2787.951725,5084.752756,0.000000,3469.685578,12167.272151,4769.124788,0.000000,0.000000,0.000000,2754.409959,982.490939,0.000000,0.0,5748.37065,0.0,0.0,6261.062840,2174.957183,91.227516,7150.390880,10323.114152,6050.544304,0.0,0.0,11131.814718,5345.681081,4905.902298,14438.790415,0.000000,7123.229496,0.000000,0.000000,13906.447259,4358.829506,5589.980039,7073.852756,3310.886144,4783.260262,0.000000,6883.187043,0.000000,5429.728159,11836.757072,2748.464789,5360.418821,4393.057018,4615.112077,3230.171540,1268.220658,5829.270036,2407.003129,2359.313135,3037.616134,3511.634344,6989.287481,0.000000,1647.311933,4758.864523,0.000000,0.000000,241.341629,2082.049738,0.000000,0.000000,2882.866800,3789.727894,0.000000,1629.922041,0.000000,4672.035091,0.000000,183.485114,0.000000,4297.503215,0.000000,0.000000,0.000000,5821.068571,480.009952,0.000000,0.000000,7329.139237,0.000000,0.000000,1977.752915,8542.905103,0.0000,0.000000,0.000000,5509.285504,0.000000,0.0,0.000000,8517.727324,0.0,0.000000,5059.738415,4139.822344,0.000000,0.000000,382.651911,9795.553102,0.0,0.000000,2096.943259,8325.997298,595.135754,75.092143,0.000000,10603.919393,0.000000,0.000000,0.000000,7670.214028,0.000000,1584.143055,1678.749581,6945.925189,0.000000,0.000000,0.000000,8062.902732,390.917156,0.000000,1412.863942,6967.546564,0.0,0.000000,2978.916611,9507.831238,2021.903350,1515.368184,0.000000,5147.086809,1604.014081,6568.039481,4736.600163,20201203_Laura_Thymus_2_1,healthy,7,0,24.620150,-1.069352,105,39,DP cells,10,3,2,-15.835876,-0.556352,5,VCAM+ DP & DP cell niche,2
1,1,20201203_Laura_Thymus_2,1,1,2.0,1.0,1.0,2917,2857,3.0,2917.0,2857.0,196.0,124.0,72.0,0.000000,0.000000,0.000000,0.000000,0.000000,486.989373,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6269.794398,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,11769.490374,0.000000,0.000000,0.000000,0.000000,3206.005895,0.000000,0.0,0.0,29950.371622,0.000000,3056.879915,2291.278344,63.889418,0.000000,2574.360824,19932.585985,0.000000,0.000000,1618.649978,557.812826,6899.951779,0.000000,1513.877989,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,17208.724704,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,2723.345616,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8059.123478,0.000000,0.000000,1008.032630,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,4076.600395,0.000000,0.0,0.0,380.234293,0.000000,2625.341325,3445.923622,0.000000,0.000000,0.000000,3302.498905,0.000000,0.000000,0.000000,2452.435291,0.000000,0.000000,4267.227061,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2819.971404,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2225.153065,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,404.914490,0.000000,0.000000,0.000000,2490.036010,0.000000,0.000000,3828.101011,1917.339240,0.0000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2488.714199,0.0,22971.084540,0.000000,0.000000,0.000000,0.000000,1756.576993,3095.119877,0.0,0.000000,39334.642700,2611.976342,2752.014339,855.237341,2608.253262,3637.504889,9392.915952,29143.538066,0.000000,1325.761320,4110.632150,0.000000,10723.524591,1830.000511,0.000000,0.000000,0.000000,2534.639495,339.473940,0.000000,1462.500177,1826.076606,0.0,1768.301263,2164.425846,2315.426401,0.000000,0.000000,0.000000,65.228710,30235.235544,0.000000,68.963257,20201203_Laura_Thymus_2_1,healthy,12,10,1.191181,3.588288,10,50,WGA+ cells,33,8,2,-11.548785,2.868561,2,Perivasculature & trabeculae niche,2
2,2,20201203_Laura_Thymus_2,1,3,4.0,1.0,1.0,2310,92,3.0,2310.0,92.0,230.0,162.0,68.0,0.000000,0.000000,0.000000,0.000000,0.000000,7441.499876,5747.677666,3817.916668,0.000000,3648.277987,7347.363670,0.000000,0.000000,575.788437,3620.188369,3304.560486,0.000000,0.000000,0.0,0.000000,1023.597630,0.000000,3692.896448,13931.081874,1357.137940,8992.516937,10692.610804,10210.164113,193.342467,0.000000,0.000000,1669.108584,375.523465,6798.972649,0.000000,2194.826373,494.783097,0.0,0.000000,1225.820327,0.000000,0.000000,2631.138728,12812.629829,1167.124635,0.0,0.0,2738.995295,2436.223797,5065.211804,3352.658773,0.000000,2949.679225,0.000000,0.000000,0.000000,1479.146059,5557.328961,8685.681246,2125.570637,797.339511,121.152738,11376.192444,3731.494999,3940.138886,14234.720121,808.860604,0.000000,2414.732703,13098.100354,2341.028065,5513.830329,2118.323798,0.000000,0.000000,0.000000,3051.812906,4379.603124,3634.365945,3598.291188,0.000000,0.000000,0.0,0.000000,0.000000,10812.641593,9894.480969,0.0,0.000000,5207.029796,4311.090191,0.000000,0.0000,26.748368,3185.884643,6263.279458,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,6193.028343,13284.880466,0.000000,9551.467023,11510.035282,10253.358768,0.000000,0.000000,0.000000,4031.612217,0.000000,10086.034101,0.000000,0.0,0.00000,0.0,0.0,739.512064,0.000000,1347.578803,5308.159375,19238.155324,0.000000,0.0,0.0,3108.611695,802.353240,4286.490516,5091.225974,0.000000,1331.993378,0.000000,0.000000,0.000000,48.981117,6402.810675,10854.764708,3121.097132,0.000000,1784.890891,8501.886609,5238.228075,2130.103883,14522.337272,1906.496914,743.149140,763.656402,18731.778767,3511.181991,5018.217511,425.411037,0.000000,0.000000,0.000000,1149.450249,2554.645155,1146.727729,1422.254805,5551.128458,0.000000,0.000000,0.000000,871.679093,5099.638768,3449.321470,9902.530887,3300.591044,2601.688368,21636.675942,0.000000,5219.995988,2369.680834,3839.850046,2024.222611,5293.939719,773.809056,2999.770684,292.036429,8264.334700,0.000000,363.766287,12980.026307,8826.704786,7555.755168,8827.786910,10516.965590,6349.434489,0.0000,0.000000,649.022541,7283.037871,3444.840048,0.0,14230.855075,7061.168656,0.0,0.000000,3573.268632,4724.365894,0.000000,926.987251,8454.639388,7342.334895,0.0,1650.792042,2665.213999,9977.807930,5938.223145,2428.925715,0.000000,9657.941844,0.000000,0.000000,1551.792748,8497.405529,5054.537408,6814.087476,2019.200877,7090.798002,0.000000,18110.838223,23.886183,11363.331446,14830.926216,483.242793,0.000000,9707.723449,0.0,1305.835326,5833.191379,9993.874804,0.000000,549.114181,0.000000,11355.356046,7701.787152,6613.572154,12262.375418,20201203_Laura_Thymus_2_1,healthy,4,82,8.216305,-10.352919,82,53,Class II+ DP cells,9,3,1,-14.729506,-3.209070,1,PD-L1+ & Class II+ late DP niche,1
3,3,20201203_Laura_Thymus_2,1,4,5.0,1.0,1.0,3427,1750,3.0,3427.0,1750.0,228.0,154.0,74.0,0.000000,0.000000,0.000000,0.000000,0.000000,417.561606,3919.806204,838.672691,0.000000,4003.481183,2274.073748,0.000000,0.000000,1358.556515,3232.207659,1896.523500,0.000000,0.000000,0.0,164.165393,0.000000,257.305491,5150.476953,1931.969245,0.000000,3643.922916,11717.465511,377.938194,0.000000,1652.527672,3680.690103,4388.243179,0.000000,573.511104,1221.534612,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,578.471461,0.000000,0.0,0.0,4277.758722,0.000000,0.000000,0.000000,0.000000,0.000000,256.729141,588.316306,557.557444,0.000000,2346.223164,1578.136279,3710.409721,0.000000,0.000000,0.000000,0.000000,0.000000,7946.922894,2399.171781,562.053514,0.000000,0.000000,2102.461942,1266.791626,0.000000,5688.890077,4124.840637,0.000000,0.000000,8044.451608,0.000000,0.000000,0.000000,62.949043,0.0,2057.757092,0.000000,3365.702413,5223.459101,0.0,0.000000,7482.673812,2119.205969,0.000000,0.0000,2722.221537,2006.341479,3459.672891,0.000000,0.000000,0.0,1032.946406,0.000000,587.434158,2733.656862,627.053910,0.000000,2776.081781,13845.994152,2332.013522,0.000000,1527.362826,5894.449518,5211.530689,0.000000,1870.892110,1862.098800,0.0,0.00000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,4588.610132,0.000000,0.0,0.0,3975.263559,0.000000,0.000000,0.000000,133.025197,0.000000,535.669716,390.740730,0.000000,0.000000,6319.142529,4525.246267,2551.693531,0.000000,0.000000,0.000000,0.000000,0.000000,13965.156824,4456.021894,2641.457037,0.000000,0.000000,3340.555992,1162.894212,0.000000,5366.208791,3885.294225,0.000000,0.000000,11249.960433,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3328.306771,3884.841669,0.000000,944.167012,3001.291626,0.000000,0.000000,0.000000,5260.264167,1203.309217,0.000000,0.000000,373.567786,0.000000,0.000000,0.000000,7753.757830,4308.137947,925.300266,4963.402240,7603.102262,0.000000,0.000000,2166.1423,410.263518,4139.176233,0.000000,0.000000,0.0,884.403071,0.000000,0.0,15.516165,20.796220,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,4196.198314,0.000000,0.000000,0.000000,0.000000,2752.080480,422.591346,1046.920028,3309.005794,0.000000,0.000000,0.000000,4670.681918,0.000000,4767.817774,1839.359092,0.000000,1171.639194,2838.917456,1473.505325,0.000000,1564.551663,0.0,1003.264352,1676.277871,991.978827,5802.195887,4263.507544,0.000000,257.070591,4785.021147,0.000000,2136.830704,20201203_Laura_Thymus_2_1,healthy,4,0,25.728025,-2.094930,100,42,DP cells,10,25,3,-4.583569,-2.030168,1,PD-L1+ & Class II+ late DP niche,3
4,4,20201203_Laura_Thymus_2,1,6,7.0,1.0,1.0,588,1609,3.0,588.0,1609.0,382.0,261.0,121.0,0.000000,55.036858,3653.180127,2903.912853,0.000000,0.000000,2768.124104,0.000000,0.000000,13867.952093,2207.200006,12851.992288,0.000000,11399.985838,6474.649683,2912.737551,0.000000,1669.070271,0.0,332.575552,0.000000,0.000000,404.526751,10132.329570,0.000000,2982.457546,35442.081853,0.000000,0.000000,0.000000,3049.278534,1448.743168,0.000000,653.831792,0.000000,0.000000,0.000000,0.0,0.000000,5365.892658,0.000000,1520.740585,0.000000,12094.118965,0.000000,0.0,0.0,2105.792142,0.000000,0.000000,0.000000,7121.775182,0.000000,0.000000,0.000000,1938.295607,0.000000,9714.446903,0.000000,1860.470664,0.000000,0.000000,4009.962629,10921.681504,0.000000,11700.150271,2152.828327,17208.125732,0.000000,0.000000,1314.065982,14057.296918,0.000000,0.000000,0.000000,3703.513725,0.000000,2093.614471,0.000000,0.000000,0.000000,0.000000,0.0,743.564719,0.000000,0.000000,2747.123403,0.0,0.000000,7348.169170,2700.812776,8577.170264,0.0000,3902.529557,3310.642641,2113.879049,0.000000,862.316186,0.0,427.325623,0.000000,0.000000,0.000000,5739.830434,0.000000,866.158191,22249.111722,0.000000,0.000000,0.000000,6049.191552,2313.540430,0.000000,1362.361413,655.824795,0.0,0.00000,0.0,0.0,4388.220338,0.000000,2201.152506,0.000000,13841.342597,0.000000,0.0,0.0,976.041472,0.000000,0.000000,0.000000,4839.758634,0.000000,0.000000,0.000000,1042.065362,0.000000,7142.414907,0.000000,1028.574598,0.000000,0.000000,3456.852488,12325.616075,0.000000,9291.785841,2110.074984,16650.042051,0.000000,0.000000,760.901742,14576.608564,0.000000,0.000000,0.000000,2506.435070,0.000000,3363.852588,0.000000,0.000000,0.000000,7105.113947,11087.822814,5633.350538,0.000000,0.000000,3197.835157,3126.028235,0.000000,20071.967675,0.000000,12741.464388,0.000000,23339.543750,11552.699143,3789.423080,0.000000,5127.151217,0.000000,448.915017,0.000000,0.000000,3207.559309,16568.271677,0.000000,6586.702862,45986.729629,1048.256687,0.000000,0.0000,0.000000,1282.343140,0.000000,395.940866,0.0,0.000000,0.000000,0.0,0.000000,9274.102662,0.000000,1225.653281,0.000000,10257.100369,0.000000,0.0,0.000000,2918.833775,0.000000,0.000000,0.000000,9862.181338,0.000000,0.000000,0.000000,3158.068298,0.000000,11238.019302,0.000000,2670.694265,0.000000,1636.591686,4992.914754,5709.989631,0.000000,13920.292069,2496.404149,14934.271336,0.000000,0.0,2123.119709,10113.631000,0.000000,1715.852844,525.126870,5039.740107,0.000000,1141.838989,0.000000,0.000000,20201203_Laura_Thymus_2_1,healthy,4,4,0.488293,4.352634,16,54,PD-L1+ CD3+ DP cells,24,2,3,-2.726925,-1.926185,0,Medulla,3

In [11]:
# Print the first few rows of each dataframe.
i=5
print(f"Dataframe {os.listdir(INPUT_DATA_PATH)[i]}:")
df_list[i].head()

Dataframe MultiRun-CombinedDataT096.csv:

,CellID,RunID,RegionID,RegCellID,cell_id:cell_id,region:region,tile_num:tile_num,x:x,y:y,z:z,x_tile:x_tile,y_tile:y_tile,size:size,interior:interior,border:border,cyc001_ch001f:DAPI-01,cyc001_ch002f:Blank,cyc001_ch003f:Blank,cyc001_ch004f:Blank,cyc002_ch001f:DAPI-02,cyc002_ch002f:HLA-ABC,cyc002_ch003f:DLL4,cyc002_ch004f:CD45,cyc003_ch001f:DAPI-03,cyc003_ch002f:Cytokeratin 5/8,cyc003_ch003f:TCRgd,cyc003_ch004f:CD326,cyc004_ch001f:DAPI-05,cyc004_ch002f:SMA,cyc004_ch003f:CD86,cyc004_ch004f:COL4,cyc005_ch001f:DAPI-06,cyc005_ch002f:Empty,cyc005_ch003f:CD274,cyc005_ch004f:CD3,cyc006_ch001f:DAPI-07,cyc006_ch002f:CP62L,cyc006_ch003f:CD5,cyc006_ch004f:AIRE,cyc007_ch001f:DAPI-08,cyc007_ch002f:CD11c,cyc007_ch003f:MCAM,cyc007_ch004f:15-PGDH,cyc008_ch001f:DAPI-09,cyc008_ch002f:CD7,cyc008_ch003f:Empty,cyc008_ch004f:DLL1,cyc009_ch001f:DAPI-10,cyc009_ch002f:CD197,cyc009_ch003f:CD19,cyc009_ch004f:Empty,cyc010_ch001f:DAPI-11,cyc010_ch002f:CD1a,cyc010_ch003f:CD38,cyc010_ch004f:CD31,cyc011_ch001f:DAPI-12,cyc011_ch002f:CD68,cyc011_ch003f:CD8a,cyc011_ch004f:IgM,cyc012_ch001f:DAPI-13,cyc012_ch002f:Ki67,cyc012_ch003f:VCAM,cyc012_ch004f:CD44,cyc013_ch001f:DAPI-14,cyc013_ch002f:CD29,cyc013_ch003f:CD45RO,cyc013_ch004f:CD279,cyc014_ch001f:DAPI-15,cyc014_ch002f:CD45RA,"cyc014_ch003f:HLA-DR,DP,DQ",cyc014_ch004f:Empty,cyc015_ch001f:DAPI-16,cyc015_ch002f:SATB1,cyc015_ch003f:CD40,cyc015_ch004f:ERTR7,cyc016_ch001f:DAPI-17,cyc016_ch002f:PDGFRa,cyc016_ch003f:CD11b,cyc016_ch004f:JAG2,cyc017_ch001f:DAPI-18,cyc017_ch002f:Laminin,cyc017_ch003f:JAG1,cyc017_ch004f:CD4,cyc018_ch001f:DAPI-19,cyc018_ch002f:Blank,cyc018_ch003f:Blank,cyc018_ch004f:Blank,cyc019_ch001f:DAPI-20,cyc019_ch002f:Empty,cyc019_ch003f:Empty,cyc019_ch004f:DRAQ5,cyc001_ch001i:DAPI-01_interior,cyc001_ch002i:Blank_interior,cyc001_ch003i:Blank_interior,cyc001_ch004i:Blank_interior,cyc002_ch001i:DAPI-02_interior,cyc002_ch002i:HLA-ABC_interior,cyc002_ch003i:DLL4_interior,cyc002_ch004i:CD45_interior,cyc003_ch001i:DAPI-03_interior,cyc003_ch002i:Cytokeratin 5/8_interior,cyc003_ch003i:TCRgd_interior,cyc003_ch004i:CD326_interior,cyc004_ch001i:DAPI-05_interior,cyc004_ch002i:SMA_interior,cyc004_ch003i:CD86_interior,cyc004_ch004i:COL4_interior,cyc005_ch001i:DAPI-06_interior,cyc005_ch002i:Empty_interior,cyc005_ch003i:CD274_interior,cyc005_ch004i:CD3_interior,cyc006_ch001i:DAPI-07_interior,cyc006_ch002i:CP62L_interior,cyc006_ch003i:CD5_interior,cyc006_ch004i:AIRE_interior,cyc007_ch001i:DAPI-08_interior,cyc007_ch002i:CD11c_interior,cyc007_ch003i:MCAM_interior,cyc007_ch004i:15-PGDH_interior,cyc008_ch001i:DAPI-09_interior,cyc008_ch002i:CD7_interior,cyc008_ch003i:Empty_interior,cyc008_ch004i:DLL1_interior,cyc009_ch001i:DAPI-10_interior,cyc009_ch002i:CD197_interior,cyc009_ch003i:CD19_interior,cyc009_ch004i:Empty_interior,cyc010_ch001i:DAPI-11_interior,cyc010_ch002i:CD1a_interior,cyc010_ch003i:CD38_interior,cyc010_ch004i:CD31_interior,cyc011_ch001i:DAPI-12_interior,cyc011_ch002i:CD68_interior,cyc011_ch003i:CD8a_interior,cyc011_ch004i:IgM_interior,cyc012_ch001i:DAPI-13_interior,cyc012_ch002i:Ki67_interior,cyc012_ch003i:VCAM_interior,cyc012_ch004i:CD44_interior,cyc013_ch001i:DAPI-14_interior,cyc013_ch002i:CD29_interior,cyc013_ch003i:CD45RO_interior,cyc013_ch004i:CD279_interior,cyc014_ch001i:DAPI-15_interior,cyc014_ch002i:CD45RA_interior,"cyc014_ch003i:HLA-DR,DP,DQ_interior",cyc014_ch004i:Empty_interior,cyc015_ch001i:DAPI-16_interior,cyc015_ch002i:SATB1_interior,cyc015_ch003i:CD40_interior,cyc015_ch004i:ERTR7_interior,cyc016_ch001i:DAPI-17_interior,cyc016_ch002i:PDGFRa_interior,cyc016_ch003i:CD11b_interior,cyc016_ch004i:JAG2_interior,cyc017_ch001i:DAPI-18_interior,cyc017_ch002i:Laminin_interior,cyc017_ch003i:JAG1_interior,cyc017_ch004i:CD4_interior,cyc018_ch001i:DAPI-19_interior,cyc018_ch002i:Blank_interior,cyc018_ch003i:Blank_interior,cyc018_ch004i:Blank_interior,cyc019_ch001i:DAPI-20_interior,cyc019_ch002i:Empty_interior,cyc019_ch003i:Empty_interior,cyc019_ch004i:DRAQ5_interior,cyc001_ch001b:DAPI-01_border,cyc001_ch002b:Blank_border,cyc001_ch003b:Blank_border,cyc001_ch004b:Blank_border,cyc002_ch001b:DAPI-02_border,cyc002_ch002b:HLA-ABC_border,cyc002_ch003b:DLL4_border,cyc002_ch004b:CD45_border,cyc003_ch001b:DAPI-03_border,cyc003_ch002b:Cytokeratin 5/8_border,cyc003_ch003b:TCRgd_border,cyc003_ch004b:CD326_border,cyc004_ch001b:DAPI-05_border,cyc004_ch002b:SMA_border,cyc004_ch003b:CD86_border,cyc004_ch004b:COL4_border,cyc005_ch001b:DAPI-06_border,cyc005_ch002b:Empty_border,cyc005_ch003b:CD274_border,cyc005_ch004b:CD3_border,cyc006_ch001b:DAPI-07_border,cyc006_ch002b:CP62L_border,cyc006_ch003b:CD5_border,cyc006_ch004b:AIRE_border,cyc007_ch001b:DAPI-08_border,cyc007_ch002b:CD11c_border,cyc007_ch003b:MCAM_border,cyc007_ch004b:15-PGDH_border,cyc008_ch001b:DAPI-09_border,cyc008_ch002b:CD7_border,cyc008_ch003b:Empty_border,cyc008_ch004b:DLL1_border,cyc009_ch001b:DAPI-10_border,cyc009_ch002b:CD197_border,cyc009_ch003b:CD19_border,cyc009_ch004b:Empty_border,cyc010_ch001b:DAPI-11_border,cyc010_ch002b:CD1a_border,cyc010_ch003b:CD38_border,cyc010_ch004b:CD31_border,cyc011_ch001b:DAPI-12_border,cyc011_ch002b:CD68_border,cyc011_ch003b:CD8a_border,cyc011_ch004b:IgM_border,cyc012_ch001b:DAPI-13_border,cyc012_ch002b:Ki67_border,cyc012_ch003b:VCAM_border,cyc012_ch004b:CD44_border,cyc013_ch001b:DAPI-14_border,cyc013_ch002b:CD29_border,cyc013_ch003b:CD45RO_border,cyc013_ch004b:CD279_border,cyc014_ch001b:DAPI-15_border,cyc014_ch002b:CD45RA_border,"cyc014_ch003b:HLA-DR,DP,DQ_border",cyc014_ch004b:Empty_border,cyc015_ch001b:DAPI-16_border,cyc015_ch002b:SATB1_border,cyc015_ch003b:CD40_border,cyc015_ch004b:ERTR7_border,cyc016_ch001b:DAPI-17_border,cyc016_ch002b:PDGFRa_border,cyc016_ch003b:CD11b_border,cyc016_ch004b:JAG2_border,cyc017_ch001b:DAPI-18_border,cyc017_ch002b:Laminin_border,cyc017_ch003b:JAG1_border,cyc017_ch004b:CD4_border,cyc018_ch001b:DAPI-19_border,cyc018_ch002b:Blank_border,cyc018_ch003b:Blank_border,cyc018_ch004b:Blank_border,cyc019_ch001b:DAPI-20_border,cyc019_ch002b:Empty_border,cyc019_ch003b:Empty_border,cyc019_ch004b:DRAQ5_border,tissueID,louvain_hf,umap_1,umap_2,clusterID,mergedID,CelltypeName,CelltypeID,kmeans_neighborhood,knn_niche,knn_umap_X,knn_umap_Y
0,0,20220921-T096-Thymic-Arch-Stanford-Panel,1,0,1.0,1.0,1.0,2754,1322,0.0,2754.0,1322.0,148.0,77.0,71.0,11950.912192,5276.995590,0.000000,8573.002868,4749.64364,0.000000,0.0,0.000000,10581.505193,0.000000,0.0,0.000000,7261.876798,0.000000,0.0,0.000000,6413.020232,6856.061717,0.0,0.000000,7126.57679,0.00000,0.000000,0.0,11593.842961,0.000000,0.0,0.000000,5739.070973,0.000000,3182.647805,0.000000,9328.973063,0.000000,0.0,0.000000,9569.89465,0.000000,0.000000,0.000000,13064.509999,0.000000,0.000000,0.00000,14305.904625,0.000000,0.000000,0.0,11031.85385,0.000000,0.0,0.000000,13665.549512,0.000000,0.000000,0.000000,5633.541726,0.00000,0.000000,0.000000,14221.655914,152.723802,0.0,0.000000,5820.679365,498.058856,0.000000,0.000000,10927.409656,5994.380583,3069.975970,2861.072051,13432.550937,7238.222266,756.896063,12534.952088,9240.128536,4107.531731,0.000000,9168.880932,3360.407623,0.000000,0.00000,0.000000,7705.649055,0.000000,0.0,0.000000,7082.363702,0.000000,0.0,0.0,4766.267008,8016.505167,0.0,0.000000,6260.799749,2714.061406,0.000000,0.0,10691.941085,0.000000,0.0,0.000000,4792.336552,0.000000,543.529809,0.000000,7825.182518,0.0,0.0,0.000000,8670.963531,0.000000,0.000000,0.000000,11838.624406,2921.778872,0.000000,0.000000,13557.942133,0.000000,0.000000,0.0,8810.755249,0.000000,0.0,0.000000,11855.177938,0.000000,0.000000,2445.488691,4074.240953,3285.219235,0.000000,0.000000,11819.112433,0.000000,0.0,0.000000,4451.551533,0.000000,0.000000,890.013591,9406.684726,7825.472855,3113.928647,7627.667255,12811.165276,6689.235187,4758.604378,12607.200876,13542.961209,5223.864238,0.000000,4172.231564,7217.189857,2466.869138,0.0,0.000000,13737.923247,0.000000,0.000000,0.0,7606.748787,0.000000,0.000000,0.000000,8694.285145,2333.637371,0.000000,0.000000,8146.368697,0.00000,0.000000,0.000000,11595.321022,0.000000,0.000000,0.000000,7441.400055,0.000000,3578.377374,0.000000,10665.296733,0.000000,0.0,7730.473886,9912.092445,0.000000,0.000000,0.000000,12353.609117,0.000000,0.000000,0.000000,12635.484236,2316.776636,0.000000,0.00000,13504.375694,0.000000,0.0,1942.532421,13346.267715,0.000000,0.000000,0.000000,8061.772976,0.000000,0.000000,5041.629421,14912.660520,8993.223636,0.0,0.000000,7933.998102,4105.415425,0.000000,0.000000,11495.492941,2794.414207,2337.991800,0.000000,11746.790403,3876.822811,0.0,11737.773457,20220921-T096-Thymic-Arch-Stanford-Panel_1,0,23.782488,9.286807,109,17,DPs,5,2,18,-37.266357,-25.409480
1,1,20220921-T096-Thymic-Arch-Stanford-Panel,1,1,2.0,1.0,1.0,1085,960,0.0,1085.0,960.0,133.0,75.0,58.0,3328.808352,0.000000,0.000000,0.000000,0.00000,8278.354751,0.0,9665.533154,3047.434739,23.768202,0.0,0.000000,0.000000,4437.171071,0.0,508.513281,2137.738219,0.000000,0.0,2954.796464,0.00000,17473.64829,5660.197821,0.0,2312.620966,3720.763823,0.0,0.000000,7468.076225,12308.055846,0.000000,0.000000,0.000000,5393.252585,0.0,170.159091,809.35028,4256.624625,0.000000,2548.178681,2913.552490,0.000000,4277.499426,4344.60421,4034.849427,0.000000,0.000000,0.0,0.00000,4307.416029,0.0,3230.178362,4133.142492,1197.159386,3567.364996,6169.250429,2190.820615,896.40304,1759.944836,0.000000,2658.002824,4399.339560,0.0,3153.401837,1372.491123,1077.989522,0.000000,1163.222765,5405.209378,0.000000,0.000000,0.000000,4809.295317,0.000000,0.000000,2150.071910,3564.210195,0.000000,0.000000,4744.187168,0.000000,9956.350133,0.00000,3387.554021,2462.567115,29.723612,0.0,0.000000,0.000000,2399.661327,0.0,0.0,1932.433673,0.000000,0.0,2897.564895,0.000000,6921.744468,6041.510947,0.0,721.981197,0.000000,0.0,0.000000,5644.226536,6010.176180,0.000000,0.000000,0.000000,0.0,0.0,0.000000,683.500495,9692.326625,0.000000,861.698246,2095.391317,0.000000,0.000000,11726.635944,3770.264380,0.000000,0.000000,0.0,0.000000,1624.180291,0.0,1354.092228,3599.780259,1405.945144,0.000000,0.000000,2510.595803,0.000000,0.000000,0.000000,216.394371,0.000000,0.0,298.616765,710.167650,0.000000,0.000000,0.000000,5601.009641,0.000000,0.000000,0.000000,3072.942123,0.000000,0.000000,3895.550346,3316.534198,0.000000,1715.013779,0.000000,0.000000,2459.777943,0.0,9825.798458,4104.396512,257.064071,0.000000,0.0,56.139670,4266.583981,4138.332614,4568.038901,2888.561715,0.000000,751.859157,1964.578185,2521.934048,17120.00475,4158.629356,0.000000,5103.654700,11020.695081,3838.982290,1325.799721,9431.407598,10901.815717,802.450281,0.000000,1215.131889,19708.134414,0.0,4224.624531,1887.247161,0.000000,1181.648981,2506.695992,4307.461383,9494.736355,10230.127814,0.000000,4110.009647,9385.725293,426.948817,5723.69629,2578.274006,4770.558424,0.0,4034.829711,4571.071765,864.846442,12100.554222,14038.283944,2302.146519,3158.681831,6832.101783,0.000000,7015.909784,11865.883552,0.0,6136.626986,3202.223604,2986.107861,0.000000,1392.797944,4381.796552,0.000000,0.000000,2068.597863,6697.790517,3033.255106,0.0,513.594702,20220921-T096-Thymic-Arch-Stanford-Panel_1,45,6.094935,-3.779018,45,6,Class II+ DPs,3,6,1,-32.056190,-19.276352
2,2,20220921-T096-Thymic-Arch-Stanford-Panel,1,2,3.0,1.0,1.0,3352,528,0.0,3352.0,528.0,145.0,85.0,60.0,1221.760332,2541.168859,290.671878,0.000000,0.00000,82.860541,0.0,5823.214443,254.056172,2703.294220,0.0,162.972824,0.000000,0.000000,0.0,0.000000,0.000000,3833.691231,0.0,3068.130366,0.00000,0.00000,4093.717243,0.0,2151.452659,6610.508036,0.0,6624.001403,0.000000,9170.065179,1074.920345,484.832404,725.203355,0.000000,0.0,2172.598073,0.00000,1903.009821,4097.935281,7753.029121,511.247101,9459.627551,10929.841123,0.00000,4457.185838,9109.409177,0.000000,0.0,0.00000,930.786021,0.0,0.000000,320.947746,8052.573675,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,363.600695,10613.661996,0.0,3936.920440,0.000000,2413.385594,625.690446,1754.947165,0.000000,542.483503,4789.439804,2306.808559,2556.205599,0.000000,5573.073161,4889.966379,123.145372,0.000000,2230.961875,0.000000,0.000000,808.595193,0.00000,9246.101676,0.000000,1852.296069,0.0,916.121907,0.000000,0.000000,0.0,0.0,0.000000,4336.793335,0.0,4713.060298,0.000000,706.684049,7689.894167,0.0,0.000000,15351.256083,0.0,3370.891787,0.000000,6112.849550,6006.127717,456.929497,0.000000,0.0,0.0,0.000000,0.000000,0.000000,126.658892,8083.828657,0.000000,13601.169872,1.201087,0.000000,2279.175790,6945.450939,0.000000,0.0,0.000000,2396.993998,0.0,0.000000,0.000000,12510.167453,0.000000,1033.681844,0.000000,3866.200214,0.000000,0.000000,0.000000,7549.961702,0.0,6985.335992,0.000000,805.867719,1607.323470,0.000000,0.000000,0.000000,4256.869543,5884.224131,1183.319427,1640.943003,8522.407025,3308.613604,3818.445920,7174.445903,0.000000,0.000000,2847.091040,0.000000,0.0,3041.611342,3446.110722,3294.049902,1157.924007,0.0,0.000000,566.501270,0.000000,5985.382930,1860.593704,1245.611504,288.970611,1717.529360,2115.945310,0.00000,1478.792467,2139.164966,6197.963746,0.000000,3936.034674,10444.582421,0.000000,7226.382290,0.000000,701.978849,3311.526398,0.000000,0.0,4828.598838,4328.293658,5415.622710,5769.138091,5303.428520,2844.340917,895.235284,17304.024598,771.386247,7047.508024,6437.703504,0.000000,0.00000,2094.205255,0.000000,0.0,3469.557255,3355.763843,0.000000,3313.996597,0.000000,1512.732842,0.000000,8257.202003,0.000000,5107.579849,7899.474637,0.0,0.000000,2023.009444,3176.915547,0.000000,2518.576102,1959.374252,2433.250637,4412.706400,0.000000,4421.988033,0.000000,0.0,6758.084964,20220921-T096-Thymic-Arch-Stanford-Panel_1,0,23.363194,8.416626,58,60,DPs,5,2,18,-38.023730,-25.747255
3,3,20220921-T096-Thymic-Arch-Stanford-Panel,1,3,4.0,1.0,1.0,3661,807,0.0,3661.0,807.0,141.0,76.0,65.0,0.000000,7983.058982,8849.023812,623.700506,0.00000,0.000000,0.0,0.000000,751.868296,2797.325373,0.0,0.000000,716.264329,0.000000,0.0,0.000000,0.000000,4949.795384,0.0,0.000000,0.00000,0.00000,0.000000,0.0,3440.575165,0.000000,0.0,5980.882127,0.000000,9528.271291,0.000000,5103.553078,1959.747790,0.000000,0.0,25534.201818,0.00000,1344.048731,0.000000,0.000000,1290.562407,1900.490796,0.000000,0.00000,3614.564234,0.000000,102.101390,0.0,0.00000,1064.007840,0.0,4027.425751,212.952238,0.000000,5592.165783,234.790087,0.000000,0.00000,3940.725366,4363.489914,747.228840,0.000000,0.0,7324.077854,0.000000,10008.183728,0.000000,6692.684341,0.000000,1228.584903,9002.122869,0.000000,2549.036280,0.000000,801.289094,6582.951583,0.000000,4578.052292,6312.595527,1611.307003,0.000000,7788.996932,4468.42462,1997.852349,0.000000,2262.642002,0.0,1591.806176,0.000000,0.000000,0.0,0.0,0.000000,2324.370463,0.0,296.127353,0.000000,0.000000,0.000000,0.0,2288.359350,0.000000,0.0,2875.368977,0.000000,15827.039734,0.000000,0.000000,809.207390,0.0,0.0,19785.583786,0.000000,339.131418,4143.268061,0.000000,433.509485,6260.570838,0.000000,0.000000,2954.541429,0.000000,0.000000,0.0,0.000000,5171.532241,0.0,0.000000,0.000000,9049.666685,9413.537354,1608.591451,0.000000,6737.773028,11798.400494,1864.585589,1339.327326,0.000000,0.0,4735.768466,0.000000,2809.922118,2955.565178,5499.838568,0.000000,161.597904,5369.025834,417.270280,1045.824698,0.000000,10743.244119,6564.275713,4805.916017,9841.351949,8984.392481,0.000000,101.294534,0.000000,0.0,0.000000,4413.814444,2698.311791,0.000000,0.0,3344.208361,0.000000,0.000000,0.000000,2960.548127,4459.868630,0.000000,0.000000,2352.691069,0.00000,0.000000,385.928513,5574.499245,0.000000,0.000000,9295.113131,0.000000,183.421699,0.000000,13316.033115,4684.897117,1881.531694,0.0,16076.941978,196.193726,1745.785965,0.000000,0.000000,3794.692168,0.000000,0.000000,0.000000,4954.284664,799.969162,304.373528,0.00000,2905.703060,0.000000,0.0,10823.430840,2444.986924,0.000000,0.000000,0.000000,561.921370,0.000000,0.000000,4810.231407,1415.762490,469.737328,0.0,8696.187118,2782.393696,10876.741018,0.000000,5094.347734,155.291730,2496.765526,10669.484897,0.000000,5276.844718,9722.614282,0.0,6867.770353,20220921-T096-Thymic-Arch-Stanford-Panel_1,0,23.368420,9.517406,87,25,DPs,5,2,13,-38.192770,-14.866151
4,4,20220921-T096-Thymic-Arch-Stanford-Panel,1,4,5.0,1.0,1.0,3182,1146,0.0,3182.0,1146.0,161.0,101.0,60.0,0.000000,2413.395935,3243.457276,4836.936829,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,15233.515633,0.0,0.000000,0.00000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,15122.480826,0.000000,0.000000,0.000000,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,15766.643406,0.0,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,4589.091220,0.000000,9737.653447,1965.302128,165.274109,0.000000,0.000000,0.000000,0.000000,0.000000,4700.312646,2628.257413,7375.290659,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,12097.495840,0.0,115.103613,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,10593.991062,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,90.427002,0.000000,3428.802107,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,3164.576076,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,3433.828561,0.000000,9268.382707,2442.735668,532.056462,0.000000,0.000000,3123.448897,0.000000,1029.235658,0.000000,3391.057124,0.000000,0.000000,1062.169637,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,9406.207077,0.000000,0.000000,0.000000,0.00000,0.000000,3601.591814,0.000000,0.000000,0.000000,0.000000,0.000000,2613.082697,11307.706753,0.000000,0.000000,0.000000,0.0,1346.854900,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,725.572959,25138.336570,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6474.867300,0.000000,590.007176,0.000000,5200.174641,0.0,0.000000,0.000000,0.000000,1057.300325,5282.556345,0.000000,7993.151150,934.431176,0.000000,0.000000,1042.096608,0.0,0.000000,20220921-T096-Thymic-Arch-Stanford-Panel_1,63,6.984132,13.013525,63,38,JAG1+ VCAM+ DCs,10,2,5,-30.405148,-27.966982

In [12]:
# Print the first few rows of each dataframe.
i=6
print(f"Dataframe {os.listdir(INPUT_DATA_PATH)[i]}:")
df_list[i].head()

Dataframe MultiRun-CombinedDataT097.csv:

,CellID,RunID,RegionID,RegCellID,cell_id:cell_id,region:region,tile_num:tile_num,x:x,y:y,z:z,x_tile:x_tile,y_tile:y_tile,size:size,interior:interior,border:border,cyc001_ch001f:DAPI-01,cyc001_ch002f:Blank,cyc001_ch003f:Blank,cyc001_ch004f:Blank,cyc002_ch001f:DAPI-02,cyc002_ch002f:CD45,"cyc002_ch003f:HLA-A,B,C",cyc002_ch004f:Empty,cyc003_ch001f:DAPI-03,cyc003_ch002f:Cytokeratin 5/8,cyc003_ch003f:SATB1,cyc003_ch004f:CD326,cyc004_ch001f:DAPI-04,cyc004_ch002f:CD19,cyc004_ch003f:JAG2,cyc004_ch004f:CD45RA,cyc005_ch001f:DAPI-05,cyc005_ch002f:SMA,cyc005_ch003f:CD86,cyc005_ch004f:CD38,cyc006_ch001f:DAPI-06,cyc006_ch002f:CD5,cyc006_ch003f:CD274,cyc006_ch004f:CD29,cyc007_ch001f:DAPI-07,cyc007_ch002f:CD3,cyc007_ch003f:CD31,cyc007_ch004f:AIRE,cyc008_ch001f:DAPI-08,cyc008_ch002f:CD11c,cyc008_ch003f:CD279,cyc008_ch004f:15-PGDH,cyc009_ch001f:DAPI-09,cyc009_ch002f:CD7,cyc009_ch003f:COL4,cyc009_ch004f:Laminin,cyc010_ch001f:DAPI-10,cyc010_ch002f:DLL1,cyc010_ch003f:CD4,cyc010_ch004f:CD197,cyc011_ch001f:DAPI-11,cyc011_ch002f:CD1a,cyc011_ch003f:ERTR7,cyc011_ch004f:MCAM,cyc012_ch001f:DAPI-12,cyc012_ch002f:CD68,cyc012_ch003f:CD8a,cyc012_ch004f:IgM,cyc013_ch001f:DAPI-13,cyc013_ch002f:Ki67,cyc013_ch003f:VCAM,cyc013_ch004f:CD44,cyc014_ch001f:DAPI-14,cyc014_ch002f:Empty,cyc014_ch003f:CD45RO,cyc014_ch004f:CD62L,cyc015_ch001f:DAPI-15,"cyc015_ch002f:HLA-DR,DP,DQ",cyc015_ch003f:CD11b,cyc015_ch004f:DLL4,cyc016_ch001f:DAPI-16,cyc016_ch002f:PDGFRa,cyc016_ch003f:CD40,cyc016_ch004f:Empty,cyc017_ch001f:DAPI-19,cyc017_ch002f:Empty,cyc017_ch003f:JAG1,cyc017_ch004f:Empty,cyc018_ch001f:DAPI-20,cyc018_ch002f:Blank,cyc018_ch003f:Blank,cyc018_ch004f:Blank,cyc019_ch001f:DAPI-21,cyc019_ch002f:Empty,cyc019_ch003f:Empty,cyc019_ch004f:DRAQ5,cyc001_ch001i:DAPI-01_interior,cyc001_ch002i:Blank_interior,cyc001_ch003i:Blank_interior,cyc001_ch004i:Blank_interior,cyc002_ch001i:DAPI-02_interior,cyc002_ch002i:CD45_interior,"cyc002_ch003i:HLA-A,B,C_interior",cyc002_ch004i:Empty_interior,cyc003_ch001i:DAPI-03_interior,cyc003_ch002i:Cytokeratin 5/8_interior,cyc003_ch003i:SATB1_interior,cyc003_ch004i:CD326_interior,cyc004_ch001i:DAPI-04_interior,cyc004_ch002i:CD19_interior,cyc004_ch003i:JAG2_interior,cyc004_ch004i:CD45RA_interior,cyc005_ch001i:DAPI-05_interior,cyc005_ch002i:SMA_interior,cyc005_ch003i:CD86_interior,cyc005_ch004i:CD38_interior,cyc006_ch001i:DAPI-06_interior,cyc006_ch002i:CD5_interior,cyc006_ch003i:CD274_interior,cyc006_ch004i:CD29_interior,cyc007_ch001i:DAPI-07_interior,cyc007_ch002i:CD3_interior,cyc007_ch003i:CD31_interior,cyc007_ch004i:AIRE_interior,cyc008_ch001i:DAPI-08_interior,cyc008_ch002i:CD11c_interior,cyc008_ch003i:CD279_interior,cyc008_ch004i:15-PGDH_interior,cyc009_ch001i:DAPI-09_interior,cyc009_ch002i:CD7_interior,cyc009_ch003i:COL4_interior,cyc009_ch004i:Laminin_interior,cyc010_ch001i:DAPI-10_interior,cyc010_ch002i:DLL1_interior,cyc010_ch003i:CD4_interior,cyc010_ch004i:CD197_interior,cyc011_ch001i:DAPI-11_interior,cyc011_ch002i:CD1a_interior,cyc011_ch003i:ERTR7_interior,cyc011_ch004i:MCAM_interior,cyc012_ch001i:DAPI-12_interior,cyc012_ch002i:CD68_interior,cyc012_ch003i:CD8a_interior,cyc012_ch004i:IgM_interior,cyc013_ch001i:DAPI-13_interior,cyc013_ch002i:Ki67_interior,cyc013_ch003i:VCAM_interior,cyc013_ch004i:CD44_interior,cyc014_ch001i:DAPI-14_interior,cyc014_ch002i:Empty_interior,cyc014_ch003i:CD45RO_interior,cyc014_ch004i:CD62L_interior,cyc015_ch001i:DAPI-15_interior,"cyc015_ch002i:HLA-DR,DP,DQ_interior",cyc015_ch003i:CD11b_interior,cyc015_ch004i:DLL4_interior,cyc016_ch001i:DAPI-16_interior,cyc016_ch002i:PDGFRa_interior,cyc016_ch003i:CD40_interior,cyc016_ch004i:Empty_interior,cyc017_ch001i:DAPI-19_interior,cyc017_ch002i:Empty_interior,cyc017_ch003i:JAG1_interior,cyc017_ch004i:Empty_interior,cyc018_ch001i:DAPI-20_interior,cyc018_ch002i:Blank_interior,cyc018_ch003i:Blank_interior,cyc018_ch004i:Blank_interior,cyc019_ch001i:DAPI-21_interior,cyc019_ch002i:Empty_interior,cyc019_ch003i:Empty_interior,cyc019_ch004i:DRAQ5_interior,cyc001_ch001b:DAPI-01_border,cyc001_ch002b:Blank_border,cyc001_ch003b:Blank_border,cyc001_ch004b:Blank_border,cyc002_ch001b:DAPI-02_border,cyc002_ch002b:CD45_border,"cyc002_ch003b:HLA-A,B,C_border",cyc002_ch004b:Empty_border,cyc003_ch001b:DAPI-03_border,cyc003_ch002b:Cytokeratin 5/8_border,cyc003_ch003b:SATB1_border,cyc003_ch004b:CD326_border,cyc004_ch001b:DAPI-04_border,cyc004_ch002b:CD19_border,cyc004_ch003b:JAG2_border,cyc004_ch004b:CD45RA_border,cyc005_ch001b:DAPI-05_border,cyc005_ch002b:SMA_border,cyc005_ch003b:CD86_border,cyc005_ch004b:CD38_border,cyc006_ch001b:DAPI-06_border,cyc006_ch002b:CD5_border,cyc006_ch003b:CD274_border,cyc006_ch004b:CD29_border,cyc007_ch001b:DAPI-07_border,cyc007_ch002b:CD3_border,cyc007_ch003b:CD31_border,cyc007_ch004b:AIRE_border,cyc008_ch001b:DAPI-08_border,cyc008_ch002b:CD11c_border,cyc008_ch003b:CD279_border,cyc008_ch004b:15-PGDH_border,cyc009_ch001b:DAPI-09_border,cyc009_ch002b:CD7_border,cyc009_ch003b:COL4_border,cyc009_ch004b:Laminin_border,cyc010_ch001b:DAPI-10_border,cyc010_ch002b:DLL1_border,cyc010_ch003b:CD4_border,cyc010_ch004b:CD197_border,cyc011_ch001b:DAPI-11_border,cyc011_ch002b:CD1a_border,cyc011_ch003b:ERTR7_border,cyc011_ch004b:MCAM_border,cyc012_ch001b:DAPI-12_border,cyc012_ch002b:CD68_border,cyc012_ch003b:CD8a_border,cyc012_ch004b:IgM_border,cyc013_ch001b:DAPI-13_border,cyc013_ch002b:Ki67_border,cyc013_ch003b:VCAM_border,cyc013_ch004b:CD44_border,cyc014_ch001b:DAPI-14_border,cyc014_ch002b:Empty_border,cyc014_ch003b:CD45RO_border,cyc014_ch004b:CD62L_border,cyc015_ch001b:DAPI-15_border,"cyc015_ch002b:HLA-DR,DP,DQ_border",cyc015_ch003b:CD11b_border,cyc015_ch004b:DLL4_border,cyc016_ch001b:DAPI-16_border,cyc016_ch002b:PDGFRa_border,cyc016_ch003b:CD40_border,cyc016_ch004b:Empty_border,cyc017_ch001b:DAPI-19_border,cyc017_ch002b:Empty_border,cyc017_ch003b:JAG1_border,cyc017_ch004b:Empty_border,cyc018_ch001b:DAPI-20_border,cyc018_ch002b:Blank_border,cyc018_ch003b:Blank_border,cyc018_ch004b:Blank_border,cyc019_ch001b:DAPI-21_border,cyc019_ch002b:Empty_border,cyc019_ch003b:Empty_border,cyc019_ch004b:DRAQ5_border,tissueID,louvain_hf,umap_1,umap_2,clusterID,mergedID,CelltypeName,CelltypeID,kmeans_neighborhood,knn_niche,knn_umap_X,knn_umap_Y
0,0,20220915-T097-Thymic-Arch-Stanford-Panel,1,0,1.0,1.0,1.0,2049,2812,0.0,2049.0,2812.0,89.0,52.0,37.0,7409.105207,2122.728668,0.0,0.000000,14290.853160,0.0,1501.343627,0.000000,16019.977364,1684.360489,0.000000,0.000000,15952.139397,0.000000,0.0,4687.398010,7290.915333,0.000000,0.0,0.0,11355.738733,0.000000,6888.281014,4008.860369,16351.547437,0.000000,0.0,4826.505641,12763.318471,757.221711,0.0,0.000000,7772.978189,0.000000,6631.358649,9047.665438,15351.065677,0.00000,0.000000,0.0,22143.442558,0.000000,2466.271875,8640.793532,20665.820059,0.000000,5821.839852,0.000000,25597.297013,8741.490802,0.000000,0.000000,21809.778801,11106.956469,0.0,896.867845,23447.653162,4184.176422,515.516763,812.779077,20068.868912,0.000000,4333.110741,0.000000,21596.754525,4210.081170,0.0,1862.305953,24681.080440,1256.115918,0.000000,0.000000,16773.134252,0.000000,0.000000,17693.915419,7377.882814,6559.360478,0.000000,0.000000,12814.258538,0.0,2748.777101,0.000000,13532.087425,1938.043735,0.000000,0.000000,15988.142348,0.000000,0.0,3332.131933,4216.066783,0.000000,794.387705,0.000000,9849.282849,0.000000,5338.88221,9480.761901,15536.908653,2295.371873,0.0,2291.494011,13074.953869,3830.971969,0.0,0.000000,6896.695213,5318.257922,7094.262779,0.000000,12672.424537,0.0,9524.988250,3456.523177,19583.995785,0.000000,3006.865545,9606.449103,18832.745993,0.000000,7983.778454,0.000000,22288.295646,5604.599557,0.000000,0.000000,17638.428694,9936.162756,1930.948545,60.202064,21145.212319,5324.611826,0.000000,0.000000,18488.844985,0.000000,5837.250358,0.000000,18760.235671,3698.850236,0.0,12198.191877,21282.150377,3267.190983,0.000000,50.455145,14864.069206,0.000000,0.000000,15982.990148,6312.984412,0.000000,1056.149641,0.00000,13171.621420,0.0,422.476941,0.000000,16511.577725,1573.014696,0.000000,1466.790114,12392.545052,3454.566907,0.0,3644.631237,10618.318944,0.000000,0.000000,0.000000,11523.942673,1745.539313,5540.138048,0.0,14277.174901,0.000000,0.0,5075.626814,9964.928265,0.000000,0.0,1098.271914,7549.473533,0.000000,4317.9494,15383.919301,16477.844140,2952.184723,0.000000,0.0,21180.571338,5236.817235,1185.026425,3094.090013,18877.068179,0.0,2962.651022,3630.814225,26124.280691,7315.116195,0.000000,4890.504542,23910.454156,5969.835017,0.000000,1634.164570,21826.320801,2951.843807,2054.722812,4233.700856,17847.297585,0.000000,1611.783237,1590.833964,20886.887162,2550.590174,0.0,0.000000,25025.758413,0.000000,0.000000,0.000000,16699.531381,1014.272252,0.000000,17849.547807,20220915-T097-Thymic-Arch-Stanford-Panel_1,343,-10.897217,8.084222,343,14,Auto,2,-1,-1,NaN,NaN
1,1,20220915-T097-Thymic-Arch-Stanford-Panel,1,2,3.0,1.0,1.0,6150,2119,0.0,6150.0,2119.0,103.0,58.0,45.0,0.000000,0.000000,0.0,0.000000,2419.963550,0.0,0.000000,0.000000,1343.251352,0.000000,0.000000,11628.695902,928.938028,0.000000,0.0,0.000000,7543.548531,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,9018.881631,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,2871.636981,0.000000,2513.89086,0.000000,0.0,4439.612361,137.826032,0.000000,924.757830,5903.493222,0.000000,0.000000,0.000000,7895.277200,0.000000,0.000000,0.000000,9359.731740,3006.868469,0.0,0.000000,3374.029413,0.000000,9231.634990,0.000000,2556.812332,5147.397654,0.000000,0.000000,2149.577104,8859.308835,0.0,4738.483296,8224.357562,0.000000,0.000000,0.000000,7292.372791,0.000000,0.000000,4136.644533,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1207.875824,0.000000,0.000000,0.000000,4817.485898,0.000000,1335.274216,0.0,0.000000,660.617556,0.000000,1135.671936,0.000000,0.000000,0.000000,0.00000,0.000000,693.607178,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1156.282742,0.000000,0.000000,551.803915,3175.562814,438.146383,0.000000,0.000000,0.000000,0.000000,1468.337340,0.000000,0.000000,0.000000,3194.964504,1380.084080,0.000000,0.000000,0.000000,0.000000,5619.594241,0.000000,0.000000,957.098240,0.000000,0.000000,0.000000,0.000000,0.0,1778.562113,1843.770312,0.000000,0.000000,4906.343010,1525.224767,0.000000,0.000000,294.929615,3433.664578,0.000000,0.000000,0.00000,10792.797075,0.0,0.000000,0.000000,9673.708008,143.685371,0.000000,11878.018805,7527.801987,0.000000,0.0,0.000000,16058.081469,5485.855584,0.000000,0.000000,294.782980,0.000000,0.000000,0.0,19374.590970,0.000000,0.0,533.763841,3025.320209,0.000000,0.0,567.013836,6825.609823,102.986734,0.0000,4763.790081,4723.077381,17127.198702,0.000000,0.0,11378.216450,0.000000,0.000000,1249.530193,13971.035727,0.0,0.000000,0.000000,15886.397760,0.000000,0.000000,0.000000,16510.962153,2995.092878,0.000000,0.000000,9075.828837,0.000000,13184.931603,0.000000,10603.372820,6664.083109,2171.249857,0.000000,8736.128922,12626.542936,0.0,5011.547967,15972.202779,0.000000,0.000000,0.000000,14303.866560,1317.775055,0.000000,9534.017561,20220915-T097-Thymic-Arch-Stanford-Panel_1,329,-11.819606,8.825025,329,14,Auto,2,-1,-1,NaN,NaN
2,2,20220915-T097-Thymic-Arch-Stanford-Panel,1,3,4.0,1.0,1.0,3044,362,0.0,3044.0,362.0,225.0,169.0,56.0,13680.353523,4699.450940,0.0,0.000000,18626.440451,0.0,0.000000,1313.448716,10192.292906,0.000000,0.000000,700.747603,21705.722584,0.000000,0.0,0.000000,11971.173286,0.000000,0.0,0.0,16907.113783,0.000000,0.000000,0.000000,16480.437552,0.000000,0.0,0.000000,15478.258451,0.000000,0.0,0.000000,15840.122591,0.000000,0.000000,0.000000,19487.088445,0.00000,0.000000,0.0,21263.608023,0.000000,0.000000,0.000000,16700.636245,0.000000,0.000000,0.000000,24496.788548,0.000000,0.000000,0.000000,20006.227708,13561.244385,0.0,4013.213014,17203.245419,0.000000,0.000000,0.000000,18563.774059,0.000000,0.000000,5789.476827,21198.429710,8641.633795,0.0,7851.757524,22554.373223,0.000000,738.812041,4558.027497,19883.093323,8230.918953,7514.192499,14899.664984,12957.710165,2143.421548,0.000000,0.000000,16069.533530,0.0,0.000000,4730.580424,9557.202093,0.000000,0.000000,0.000000,19732.931144,0.000000,0.0,0.000000,10537.047983,0.000000,0.000000,2428.897651,15482.316715,0.000000,0.00000,0.000000,15371.737478,0.000000,0.0,0.000000,14047.387238,0.000000,0.0,0.000000,13718.138073,0.000000,0.000000,0.000000,17334.033213,0.0,0.000000,0.000000,19737.628743,0.000000,0.000000,0.000000,15759.788860,0.000000,0.000000,0.000000,22573.953726,0.000000,0.000000,0.000000,18860.848699,8029.786558,0.000000,2948.397501,15770.184882,0.000000,0.000000,0.000000,16844.197868,0.000000,0.000000,3848.012694,19190.516227,7955.459343,0.0,9442.294691,20560.939221,0.000000,912.744422,4917.627545,19100.350710,3512.658079,9549.990574,13139.912454,8037.454093,9018.778035,0.000000,0.00000,14388.751853,0.0,0.000000,0.000000,4606.796402,0.000000,0.000000,10439.477558,15059.989297,0.000000,0.0,0.000000,7927.039649,0.000000,0.000000,0.000000,11475.841166,0.000000,0.000000,0.0,9617.363419,0.000000,0.0,0.000000,10595.042711,0.000000,0.0,423.558321,12092.110463,0.000000,0.0000,0.000000,15750.503331,0.000000,0.000000,0.0,13701.810492,0.000000,0.000000,0.000000,9363.460128,0.0,0.000000,0.000000,19218.867813,0.000000,0.000000,0.000000,13041.902413,14846.800471,0.000000,3804.621881,10988.077445,0.000000,0.000000,0.000000,11906.571164,0.000000,0.000000,5809.447716,14423.134609,3675.988283,0.0,0.000000,16897.152469,0.000000,0.000000,1515.618016,12198.303647,12087.474380,0.000000,11990.328743,20220915-T097-Thymic-Arch-Stanford-Panel_1,270,-8.443738,10.026274,270,14,Auto,2,-1,-1,NaN,NaN
3,3,20220915-T097-Thymic-Arch-Stanford-Panel,1,4,5.0,1.0,1.0,6527,4879,0.0,6527.0,4879.0,73.0,36.0,37.0,0.000000,0.000000,0.0,0.000000,5233.630537,0.0,0.000000,1.123575,4383.953434,349.906766,2024.597308,4466.685326,414.814890,3133.612382,0.0,6248.928515,7689.230567,7848.251363,0.0,0.0,0.000000,0.000000,0.000000,0.000000,6143.211353,7697.054632,0.0,9221.542026,689.586033,3283.883592,0.0,1252.828212,1436.060731,0.000000,0.000000,2068.990341,0.000000,0.00000,2281.758958,0.0,6061.807284,0.000000,0.000000,0.000000,6096.468101,0.000000,0.000000,7542.483765,6038.100542,0.000000,2679.533718,10778.835286,5653.206423,0.000000,0.0,12362.956119,4849.618939,0.000000,0.000000,3681.798940,2317.922039,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,166.153373,0.000000,8597.940009,5691.204666,0.000000,3391.082835,8757.441944,0.000000,1771.365299,0.000000,0.000000,2999.461963,3627.240681,2037.775266,0.0,0.000000,12151.653860,1958.533591,532.230591,3045.402524,0.000000,0.000000,9311.868303,0.0,0.000000,5896.895232,8419.475567,0.000000,0.000000,0.000000,518.304066,0.00000,0.000000,5448.725529,0.000000,0.0,0.000000,2708.210823,3135.964243,0.0,0.000000,0.000000,0.000000,0.000000,434.356723,0.000000,0.0,0.000000,0.000000,75.865467,0.000000,0.000000,0.000000,2488.930870,0.000000,0.000000,0.000000,1879.898157,0.000000,3373.482579,7723.793769,7530.494649,0.000000,0.000000,5464.319961,4591.447369,0.000000,0.000000,0.000000,0.000000,6168.168701,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,8953.930576,0.000000,2408.069314,12854.722372,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,8950.692375,0.0,0.000000,0.000000,7575.275345,249.478628,442.874994,7076.916137,3874.027442,0.000000,0.0,15476.173194,9588.568558,4413.743712,4242.926145,3811.595127,2052.475269,0.000000,3074.862926,0.0,7260.966377,12031.369891,0.0,13268.524078,0.000000,1875.011705,0.0,4162.794932,4536.200808,0.000000,0.0000,2738.941609,1321.663098,0.000000,837.193232,0.0,12556.628261,0.000000,1049.905440,0.000000,10060.343917,0.0,1765.805160,15530.266033,10753.343299,2802.542639,1166.527166,8627.608586,4192.321678,0.000000,1444.840751,12036.339995,5741.097037,0.000000,1830.778619,8282.417868,8239.815079,0.000000,0.000000,0.000000,3805.393333,0.000000,0.0,2940.987681,0.000000,13185.883546,1769.510968,0.000000,5167.528542,1553.458565,0.000000,8567.329999,20220915-T097-Thymic-Arch-Stanford-Panel_1,246,-8.466493,9.272611,246,14,Auto,2,-1,-1,NaN,NaN
4,4,20220915-T097-Thymic-Arch-Stanford-Panel,1,5,6.0,1.0,1.0,5184,4754,0.0,5184.0,4754.0,135.0,79.0,56.0,0.000000,8600.745114,0.0,17776.907078,8920.603003,0.0,0.000000,14371.061389,6705.006917,7419.273597,453.601589,2145.007371,5405.282251,2041.418750,0.0,0.000000,10388.957393,0.000000,0.0,0.0,4683.258774,2159.405012,0.000000,0.000000,10116.509346,0.000000,0.0,6271.508091,4781.296761,0.000000,0.0,2269.740236,4872.234933,2417.465312,0.000000,7694.893084,2918.472962,0.00000,1278.866496,0.0,5984.177119,3245.374869,4799.439408,4507.072274,7735.890775,904.360849,8778.237870,23531.098310,6961.325529,0.000000,0.000000,1684.501006,10256.171670,0.000000,0.0,1222.286988,9899.274688,0.000000,0.000000,2552.985138,6432.722728,0.000000,0.000000,0.000000,3846.775023,0.000000,0.0,0.000000,8852.633613,4884.454918,5374.552644,0.000000,8347.376107,0.000000,14720.040988,6535.860380,0.000000,3728.263734,385.351718,7872.466607,8434.054510,0.0,0.000000,17435.873442,5915.723564,5863.335455,0.000000,6489.431712,4667.341467,1819.574227,0.0,0.000000,8722.649630,3241.908045,0.000000,0.000000,5695.528852,1170.502779,0.00000,0.000000,7720.227150,915.806337,0.0,11318.871655,4725.660069,0.000000,0.0,2742.740629,4918.416799,2941.336311,0.000000,12938.724156,3854.439182,0.0,0.000000,0.000000,5875.500991,550.958285,0.000000,7207.919024,8275.368019,8749.356575,14078.269177,21626.226938,4884.382247,352.741251,0.000000,1385.705807,8264.753681,0.000000,0.000000,11103.378372,10282.270118,0.000000,0.000000,8013.244266,6497.247758,0.000000,5395.362837,0.000000,4216.856743,7730.804556,0.0,0.000000,9114.194224,2090.085068,5143.569697,0.000000,9538.350252,0.000000,2302.581206,6317.015675,929.284073,9714.987759,0.000000,18849.45603,7702.802492,0.0,0.000000,3283.910111,6784.851515,8177.107883,1887.349029,0.000000,5565.875756,1526.774210,0.0,0.000000,10826.809329,0.000000,0.000000,428.374853,2555.396922,2241.572090,0.000000,0.0,11873.747962,0.000000,0.0,0.000000,4252.725642,0.000000,0.0,1529.726408,3991.569271,886.140331,0.0000,0.000000,1354.988669,0.000000,1417.790935,0.0,5170.336433,4964.533814,9553.310225,0.000000,5579.190253,0.0,2884.282413,13200.835976,9166.775943,0.000000,0.000000,1316.587839,11472.571818,264.399251,0.000000,0.000000,7458.937588,0.000000,0.000000,0.000000,5121.192145,39.274515,0.000000,958.260289,2718.839390,0.000000,0.0,0.000000,6949.361919,5801.055467,4832.453485,1392.413847,5313.458743,0.000000,18673.149673,6507.772698,20220915-T097-Thymic-Arch-Stanford-Panel_1,384,-8.496761,8.976599,384,14,Auto,2,-1,-1,NaN,NaN

In [13]:
# Print the first few rows of each dataframe.
i=7
print(f"Dataframe {os.listdir(INPUT_DATA_PATH)[i]}:")
df_list[i].head()

Dataframe MultiRun-CombinedDataT100.csv:

,CellID,RunID,RegionID,RegCellID,cell_id:cell_id,region:region,tile_num:tile_num,x:x,y:y,z:z,x_tile:x_tile,y_tile:y_tile,size:size,interior:interior,border:border,cyc001_ch001f:DAPI-01,cyc001_ch002f:Blank,cyc001_ch003f:Blank,cyc001_ch004f:Blank,cyc002_ch001f:DAPI-02,cyc002_ch002f:HLA-ABC,cyc002_ch003f:CD5,cyc002_ch004f:CD45,cyc003_ch001f:DAPI-03,cyc003_ch002f:Cytokeratin 5/8,cyc003_ch003f:TCRgd,cyc003_ch004f:CD326,cyc004_ch001f:DAPI-04,cyc004_ch002f:CD45RA,cyc004_ch003f:JAG1,cyc004_ch004f:COL4,cyc005_ch001f:DAPI-05,cyc005_ch002f:SMA,cyc005_ch003f:CD86,cyc005_ch004f:CD279,cyc006_ch001f:DAPI-06,cyc006_ch002f:Laminin,cyc006_ch003f:CD274,cyc006_ch004f:CD31,cyc007_ch001f:DAPI-07,cyc007_ch002f:CD45RA,cyc007_ch003f:CD19,cyc007_ch004f:AIRE,cyc008_ch001f:DAPI-08,cyc008_ch002f:CD11c,"cyc008_ch003f:HLA-DR,DP,DQ",cyc008_ch004f:15-PGDH,cyc009_ch001f:DAPI-09,cyc009_ch002f:CD7,cyc009_ch003f:MCAM,cyc009_ch004f:CD3,cyc010_ch001f:DAPI-10,cyc010_ch002f:CD62L,cyc010_ch003f:Empty,cyc010_ch004f:DLL1,cyc011_ch001f:DAPI-11,cyc011_ch002f:CD1a,cyc011_ch003f:CD38,cyc011_ch004f:CD4,cyc012_ch001f:DAPI-12,cyc012_ch002f:CD68,cyc012_ch003f:CD8a,cyc012_ch004f:IgM,cyc013_ch001f:DAPI-13,cyc013_ch002f:Ki67,cyc013_ch003f:VCAM,cyc013_ch004f:CD44,cyc014_ch001f:DAPI-14,cyc014_ch002f:CD29,cyc014_ch003f:CD45RO,cyc014_ch004f:Empty,cyc015_ch001f:DAPI-15,cyc015_ch002f:CD197,cyc015_ch003f:CD11b,cyc015_ch004f:DLL4,cyc016_ch001f:DAPI-16,cyc016_ch002f:SATB1,cyc016_ch003f:CD40,cyc016_ch004f:ERTR7,cyc017_ch001f:DAPI-17,cyc017_ch002f:PDGFRa,cyc017_ch003f:DLL4,cyc017_ch004f:JAG2,cyc018_ch001f:DAPI-18,cyc018_ch002f:Blank,cyc018_ch003f:Blank,cyc018_ch004f:Blank,cyc019_ch001f:DAPI-19,cyc019_ch002f:Empty,cyc019_ch003f:Empty,cyc019_ch004f:DRAQ5,cyc001_ch001i:DAPI-01_interior,cyc001_ch002i:Blank_interior,cyc001_ch003i:Blank_interior,cyc001_ch004i:Blank_interior,cyc002_ch001i:DAPI-02_interior,cyc002_ch002i:HLA-ABC_interior,cyc002_ch003i:CD5_interior,cyc002_ch004i:CD45_interior,cyc003_ch001i:DAPI-03_interior,cyc003_ch002i:Cytokeratin 5/8_interior,cyc003_ch003i:TCRgd_interior,cyc003_ch004i:CD326_interior,cyc004_ch001i:DAPI-04_interior,cyc004_ch002i:CD45RA_interior,cyc004_ch003i:JAG1_interior,cyc004_ch004i:COL4_interior,cyc005_ch001i:DAPI-05_interior,cyc005_ch002i:SMA_interior,cyc005_ch003i:CD86_interior,cyc005_ch004i:CD279_interior,cyc006_ch001i:DAPI-06_interior,cyc006_ch002i:Laminin_interior,cyc006_ch003i:CD274_interior,cyc006_ch004i:CD31_interior,cyc007_ch001i:DAPI-07_interior,cyc007_ch002i:CD45RA_interior,cyc007_ch003i:CD19_interior,cyc007_ch004i:AIRE_interior,cyc008_ch001i:DAPI-08_interior,cyc008_ch002i:CD11c_interior,"cyc008_ch003i:HLA-DR,DP,DQ_interior",cyc008_ch004i:15-PGDH_interior,cyc009_ch001i:DAPI-09_interior,cyc009_ch002i:CD7_interior,cyc009_ch003i:MCAM_interior,cyc009_ch004i:CD3_interior,cyc010_ch001i:DAPI-10_interior,cyc010_ch002i:CD62L_interior,cyc010_ch003i:Empty_interior,cyc010_ch004i:DLL1_interior,cyc011_ch001i:DAPI-11_interior,cyc011_ch002i:CD1a_interior,cyc011_ch003i:CD38_interior,cyc011_ch004i:CD4_interior,cyc012_ch001i:DAPI-12_interior,cyc012_ch002i:CD68_interior,cyc012_ch003i:CD8a_interior,cyc012_ch004i:IgM_interior,cyc013_ch001i:DAPI-13_interior,cyc013_ch002i:Ki67_interior,cyc013_ch003i:VCAM_interior,cyc013_ch004i:CD44_interior,cyc014_ch001i:DAPI-14_interior,cyc014_ch002i:CD29_interior,cyc014_ch003i:CD45RO_interior,cyc014_ch004i:Empty_interior,cyc015_ch001i:DAPI-15_interior,cyc015_ch002i:CD197_interior,cyc015_ch003i:CD11b_interior,cyc015_ch004i:DLL4_interior,cyc016_ch001i:DAPI-16_interior,cyc016_ch002i:SATB1_interior,cyc016_ch003i:CD40_interior,cyc016_ch004i:ERTR7_interior,cyc017_ch001i:DAPI-17_interior,cyc017_ch002i:PDGFRa_interior,cyc017_ch003i:DLL4_interior,cyc017_ch004i:JAG2_interior,cyc018_ch001i:DAPI-18_interior,cyc018_ch002i:Blank_interior,cyc018_ch003i:Blank_interior,cyc018_ch004i:Blank_interior,cyc019_ch001i:DAPI-19_interior,cyc019_ch002i:Empty_interior,cyc019_ch003i:Empty_interior,cyc019_ch004i:DRAQ5_interior,cyc001_ch001b:DAPI-01_border,cyc001_ch002b:Blank_border,cyc001_ch003b:Blank_border,cyc001_ch004b:Blank_border,cyc002_ch001b:DAPI-02_border,cyc002_ch002b:HLA-ABC_border,cyc002_ch003b:CD5_border,cyc002_ch004b:CD45_border,cyc003_ch001b:DAPI-03_border,cyc003_ch002b:Cytokeratin 5/8_border,cyc003_ch003b:TCRgd_border,cyc003_ch004b:CD326_border,cyc004_ch001b:DAPI-04_border,cyc004_ch002b:CD45RA_border,cyc004_ch003b:JAG1_border,cyc004_ch004b:COL4_border,cyc005_ch001b:DAPI-05_border,cyc005_ch002b:SMA_border,cyc005_ch003b:CD86_border,cyc005_ch004b:CD279_border,cyc006_ch001b:DAPI-06_border,cyc006_ch002b:Laminin_border,cyc006_ch003b:CD274_border,cyc006_ch004b:CD31_border,cyc007_ch001b:DAPI-07_border,cyc007_ch002b:CD45RA_border,cyc007_ch003b:CD19_border,cyc007_ch004b:AIRE_border,cyc008_ch001b:DAPI-08_border,cyc008_ch002b:CD11c_border,"cyc008_ch003b:HLA-DR,DP,DQ_border",cyc008_ch004b:15-PGDH_border,cyc009_ch001b:DAPI-09_border,cyc009_ch002b:CD7_border,cyc009_ch003b:MCAM_border,cyc009_ch004b:CD3_border,cyc010_ch001b:DAPI-10_border,cyc010_ch002b:CD62L_border,cyc010_ch003b:Empty_border,cyc010_ch004b:DLL1_border,cyc011_ch001b:DAPI-11_border,cyc011_ch002b:CD1a_border,cyc011_ch003b:CD38_border,cyc011_ch004b:CD4_border,cyc012_ch001b:DAPI-12_border,cyc012_ch002b:CD68_border,cyc012_ch003b:CD8a_border,cyc012_ch004b:IgM_border,cyc013_ch001b:DAPI-13_border,cyc013_ch002b:Ki67_border,cyc013_ch003b:VCAM_border,cyc013_ch004b:CD44_border,cyc014_ch001b:DAPI-14_border,cyc014_ch002b:CD29_border,cyc014_ch003b:CD45RO_border,cyc014_ch004b:Empty_border,cyc015_ch001b:DAPI-15_border,cyc015_ch002b:CD197_border,cyc015_ch003b:CD11b_border,cyc015_ch004b:DLL4_border,cyc016_ch001b:DAPI-16_border,cyc016_ch002b:SATB1_border,cyc016_ch003b:CD40_border,cyc016_ch004b:ERTR7_border,cyc017_ch001b:DAPI-17_border,cyc017_ch002b:PDGFRa_border,cyc017_ch003b:DLL4_border,cyc017_ch004b:JAG2_border,cyc018_ch001b:DAPI-18_border,cyc018_ch002b:Blank_border,cyc018_ch003b:Blank_border,cyc018_ch004b:Blank_border,cyc019_ch001b:DAPI-19_border,cyc019_ch002b:Empty_border,cyc019_ch003b:Empty_border,cyc019_ch004b:DRAQ5_border,tissueID,louvain_hf,umap_1,umap_2,clusterID,mergedID,CelltypeName,CelltypeID,kmeans_neighborhood,knn_niche,knn_umap_X,knn_umap_Y,condition
0,0,20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel,1,0,1.0,1.0,1.0,741,785,0.0,741.0,785.0,103.0,45.0,58.0,2315.853063,6541.191534,0.000000,0.000000,2428.952015,989.433242,0.000000,2397.935071,78.465701,0.000000,0.0,0.000000,1898.794118,11950.832792,965.956982,0.0,0.000000,20299.109619,0.0,0.0,0.000000,13397.492939,4850.622225,0.0,0.000000,12781.748403,0.0,0.0,1369.608736,16751.410835,0.000000,2994.721679,0.000000,9454.123106,0.000000,0.0,0.000000,15195.941688,0.000000,0.0,609.110942,12234.892167,7048.625165,3064.786860,0.000000,12569.446746,10160.890200,0.0,0.000000,13635.253594,0.000000,0.000000,905.770284,0.000000,0.0,0.000000,0.000000,1160.064778,0.0,0.0,0.000000,16075.138602,0.0,0.0,1917.096401,18168.437268,0.0,0.000000,1388.827313,14873.399830,12439.655265,13252.912437,0.000000,0.000000,4325.192718,0.000000,1055.762208,2476.593481,0.000000,0.000000,1075.861456,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,701.077851,13087.892648,2690.155016,0.0,0.0,19719.757585,1806.472019,0.0,0.0,14462.238771,11632.243561,0.0,0.0,14988.965234,0.0,0.0,152.274957,17256.626737,0.000000,4412.886385,0.0,10201.732536,660.968778,0.000000,0.0,14607.625662,0.000000,0.0,78.426957,12539.563605,4665.313797,17.854740,0.0,12925.171573,12852.998917,0.0,0.0,13629.002348,975.082017,0.000000,206.553893,230.615950,0.0,0.000000,0.0,3909.426531,0.0,0.0,0.0,13814.635937,0.0,0.0,581.974179,13046.842311,0.0,0.000000,134.993501,13160.055053,11224.175808,10001.933523,0.0,1231.708879,6531.298692,0.0,3660.085009,6948.198708,814.830347,0.0,3203.940720,1545.006135,1341.495279,4201.505087,1125.283034,0.000000,0.0,0.000000,2758.675561,6976.574455,0.000000,0.0,463.544364,15823.948271,0.0,0.0,847.075379,9168.083366,0.000000,0.0,130.148568,7357.684437,0.0,0.0,2812.580700,13449.471367,597.130980,1127.938894,1295.818090,6323.869278,0.000000,599.453629,528.252887,13577.867790,608.768867,0.0,1625.790257,10224.901361,7724.278685,4206.796768,0.000000,9390.979848,6096.272962,0.0,0.000000,10926.786406,0.000000,0.0,1831.535105,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,395.379141,15083.944013,0.0,0.0,3308.396553,19144.529765,0.0,454.058237,2806.168750,14423.422159,11800.463815,14055.459673,1531.851381,0.000000,1935.749011,0.000000,20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_1,7,5.164259,8.241049,7,49,Auto,2,-1,-1,NaN,NaN,1
1,1,20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel,1,1,2.0,1.0,1.0,528,555,0.0,528.0,555.0,122.0,58.0,64.0,2762.315021,3302.953430,4741.994835,2251.664503,3134.684620,0.000000,0.000000,0.000000,1103.559056,0.000000,0.0,0.000000,1050.474018,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,467.375731,0.000000,8501.298522,3939.695429,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,2433.599395,5547.458689,5834.342747,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,874.084543,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,670.240957,0.000000,0.0,4644.260350,0.000000,2092.515711,3127.191221,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10037.435536,12385.158884,8384.798840,0.000000,2066.392804,0.000000,3457.797279,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,8093.171910,0.000000,0.0,939.673608,4822.468364,908.651062,0.0,1229.438522,0.000000,0.0,0.000000,4302.721822,8483.582678,10454.888085,0.0,68.944889,1881.922836,0.0,0.0,0.000000,1383.191661,0.000000,0.000000,7232.672798,0.0,1071.746590,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,1012.844975,0.000000,668.674770,4100.315236,0.000000,0.0,0.000000,0.000000,0.0,9233.331893,0.000000,0.000000,0.0,11176.897620,0.000000,0.000000,0.000000,10341.728856,0.000000,0.0,0.000000,10759.575955,0.000000,3138.852283,0.0,7444.100749,0.000000,0.0,0.0,10061.290086,0.000000,0.000000,0.0,8493.526335,0.000000,0.0,0.0,10455.308332,0.000000,5937.718746,7245.775509,10466.399744,0.000000,0.000000,0.000000,6807.645925,0.000000,0.000000,0.0,8706.468573,801.527428,3130.528708,2435.742689,7017.053288,0.000000,0.000000,0.0,5639.916497,240.922609,0.000000,0.0,9147.181955,0.0,0.0,0.000000,3932.999063,1224.551070,0.0,0.0,8330.666485,2896.227549,0.0,0.0,10341.970929,0.000000,0.0,8071.272721,9333.436250,3674.880273,1253.120634,422.244185,9015.425318,0.000000,0.000000,9784.586453,20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_1,0,23.030910,10.230530,25,46,Class II+ DPs,4,9,0,-56.217580,86.96396,1
2,2,20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel,1,2,3.0,1.0,1.0,377,1248,0.0,377.0,1248.0,104.0,46.0,58.0,6933.453029,2656.285294,0.000000,609.118180,9890.297897,473.153970,0.000000,0.000000,7187.138407,1079.057643,0.0,0.000000,7558.975378,0.000000,0.000000,0.0,5749.660295,0.000000,0.0,0.0,5351.870466,0.000000,0.000000,0.0,5702.639715,0.000000,0.0,0.0,9935.377915,869.133521,18376.007429,3199.034659,6369.360549,1356.255073,7662.995444,0.0,6415.587803,571.017216,11024.256059,0.0,5929.405554,183.660120,957.869682,0.000000,3687.160168,0.000000,21016.171648,0.0,1929.523314,138.249982,1889.233008,0.000000,6934.605563,68.417129,0.0,13380.354176,4988.660035,0.000000,0.0,0.0,3992.490345,0.000000,0.0,0.0,8944.017409,0.000000,0.0,2954.747299,6803.321766,1319.946108,5624.401566,2779.024971,3894.350532,12952.965996,11507.728066,3161.644644,0.000000,0.000000,0.000000,2544.685311,0.000000,3146.498211,0.000000,0.000000,0.0,2066.748741,0.0,1497.697215,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,879.935130,17418.523969,0.000000,0.0,425.616396,18388.106750,0.000000,0.0,0.000000,6908.173889,0.0,0.000000,0.000000,4595.345513,0.000000,0.0,0.000000,16734.481320,0.0,0.0,0.000000,0.000000,0.000000,0.000000,1828.693025,0.0,8943.065724,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,4540.023857,0.000000,0.0,7117.193688,18410.473271,0.0,17984.553655,4116.357448,110.193921,0.0,22291.797939,0.000000,0.000000,0.000000,21162.715536,600.024194,0.0,0.000000,21100.512089,0.000000,4767.850988,0.0,19250.964268,0.000000,0.0,0.0,18797.598047,0.000000,2381.062605,0.0,19519.177657,0.000000,0.0,0.0,24295.187484,942.202745,13452.379082,8402.266546,21107.071170,2417.597575,0.000000,0.000000,20323.122794,2385.672778,12073.724137,0.0,20204.570589,1988.857000,0.000000,872.960991,16746.880831,463.196380,19528.610665,0.0,15511.912389,2877.094048,2890.191438,0.0,20789.752862,0.0,0.0,13713.757625,18036.877111,2411.477301,0.0,0.0,17540.478935,0.000000,0.0,0.0,22052.486524,0.000000,0.0,8531.715447,20820.156698,5012.632880,6045.419017,8590.412154,17615.366802,14843.505533,4093.017054,15894.348938,20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_1,14,2.440887,6.809934,35,44,Class II+ DPs,4,9,0,-57.290195,87.00390,1
3,3,20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel,1,3,4.0,1.0,1.0,1381,624,0.0,1381.0,624.0,124.0,62.0,62.0,7730.756819,691.893092,0.000000,0.000000,6808.996543,10337.621574,4920.145656,0.000000,3429.315492,9721.337783,0.0,3502.837681,3204.970480,10613.494186,0.000000,0.0,1204.694763,11919.924659,0.0,0.0,1541.764931,11154.962889,0.000000,0.0,2264.215591,11756.503094,0.0,0.0,4340.014442,11299.662326,5456.465464,0.000000,1706.256473,3435.293247,6366.020895,0.0,952.097796,11818.371601,0.000000,0.0,2667.877235,1247.635792,504.384058,0.000000,1044.034471,6338.778579,6929.134835,0.0,194.158339,9980.963649,858.450552,951.876878,324.794817,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,486.334756,6662.180305,0.0,0.0,3651.444604,3138.309913,0.0,0.000000,1479.467831,8684.331517,12917.243701,0.000000,441.991766,0.000000,0.000000,0.000000,555.918273,4491.347586,0.000000,0.000000,0.000000,18799.227825,12689.877395,3641.260502,0.0,4583.203151,0.0,2519.204085,0.000000,8265.936146,0.000000,0.0,0.0,8737.856070,0.000000,0.0,0.0,8245.994840,0.000000,0.0,0.0,8377.859729,0.0,0.0,0.000000,6520.861965,5503.596815,0.000000,0.0,4584.957298,12266.445472,0.000000,0.0,7212.244020,0.000000,0.0,0.000000,1433.552101,4090.937772,3418.277793,0.0,5512.533337,8877.613281,0.0,0.0,3807.507552,2824.473768,6453.794783,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,2372.881750,0.0,0.0,0.000000,1169.007155,0.0,0.000000,0.000000,6021.379823,11258.666133,0.000000,0.0,0.000000,0.000000,0.0,14561.894681,0.000000,0.000000,0.0,13064.170350,276.241980,0.000000,0.000000,10883.033645,13512.885988,0.0,4360.726050,11357.055800,10110.576080,0.000000,0.0,8335.054606,13378.849802,0.0,0.0,9353.689330,12929.912887,0.000000,0.0,10419.452543,14520.787888,0.0,0.0,11743.014387,17106.337768,3411.401261,0.000000,9413.117142,1711.818025,749.128085,0.000000,9573.939587,16790.418009,0.000000,0.0,10456.172597,1260.312894,0.000000,0.000000,9069.125382,5684.373126,3222.849609,0.0,8521.763567,16796.677202,0.000000,0.0,8591.356069,0.0,0.0,0.000000,6999.344523,810.800979,0.0,0.0,9037.517512,10686.407468,0.0,0.0,12028.533428,4782.029772,0.0,0.000000,10105.911433,10328.280287,12021.040600,0.000000,8882.774367,0.000000,568.604787,7785.160037,20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_1,22,7.005392,1.256144,22,51,Auto,2,-1,-1,NaN,NaN,1
4,4,20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel,1,4,5.0,1.0,1.0,1373,622,0.0,1373.0,622.0,102.0,49.0,53.0,0.000000,0.000000,0.000000,0.000000,0.000000,7034.543957,0.000000,0.000000,0.000000,19549.166836,0.0,7929.628719,0.000000,10089.767694,0.000000,0.0,0.000000,7789.474971,0.0,0.0,0.000000,10582.467098,0.000000,0.0,0.000000,9612.810820,0.0,0.0,0.000000,8445.675599,5555.115379,0.000000,0.000000,0.000000,6788.312526,0.0,0.000000,6308.969073,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,3444.466838,4934.465884,0.0,0.000000,6253.592833,1302.920625,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,4018.665919,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,3809.889356,8303.782847,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1821.424011,6908.741117,0.000000,4418.738416,2354.028370,0.000000,0.0,27979.181671,0.0,14707.368098,0.000000,1313.886725,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,1129.987287,0.000000,0.0,0.0,2041.825596,0.0,0.0,0.000000,158.058371,6628.722285,0.000000,0.0,0.000000,3064.828562,0.000000,0.0,0.000000,730.783394,0.0,0.000000,0.000000,0.000000,519.731855,0.0,0.000000,117.791997,0.0,0.0,0.000000,1792.894352,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,2553.579387,0.000000,0.0,0.000000,0.000000,0.0,9618.526247,0.000000,0.000000,0.0,9840.691886,7646.427227,0.000000,0.000000,6703.426478,14589.574093,0.0,3248.072227,6840.395117,18815.422556,0.000000,0.0,4918.698178,18678.897871,0.0,0.0,6275.486249,23767.467709,0.000000,0.0,5171.827497,20235.978605,0.0,0.0,6827.628274,20839.656273,2632.411140,117.312029,6129.469528,3379.802650,9152.209729,0.000000,4274.796751,15708.759645,0.000000,0.0,4881.115259,4261.619538,0.000000,0.000000,4538.946468,12683.166539,8155.478314,0.0,4382.615895,14678.637224,1123.450089,0.0,4023.573112,0.0,0.0,0.000000,2168.441084,8893.766323,0.0,0.0,3123.828142,9870.799625,0.0,0.0,5825.434693,0.000000,0.0,0.000000,3487.960864,11242.922601,14248.312610,0.000000,3425.501652,0.000000,0.000000,4844.174805,20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_1,6,-5.414980,7.423517,6,50,Auto,2,-1,-1,NaN,NaN,1

In [14]:
# Check if all dataframes have the same columns.
columns = [set(df.columns) for df in df_list]
if all(col == columns[0] for col in columns):
    print("All dataframes have the same columns.")
else:
    print("Dataframes have different columns.")

Dataframes have different columns.

In [15]:
# check if x:x and x_tile:x_tile in df_list[7] are equal
# convert to integer type
df_list[7]['x:x'] = df_list[7]['x:x'].astype(int)
df_list[7]['x_tile:x_tile'] = df_list[7]['x_tile:x_tile'].astype(int)
df_list[7]['y:y'] = df_list[7]['y:y'].astype(int)
df_list[7]['y_tile:y_tile'] = df_list[7]['y_tile:y_tile'].astype(int)
print(df_list[7]['x:x'].equals(df_list[7]['x_tile:x_tile']))
print(df_list[7]['y:y'].equals(df_list[7]['y_tile:y_tile']))

True
True

In [16]:
# print unique tissueID in df_list
for i in range(len(df_list)):
    print(f"Unique tissueID in dataframe {i}:")
    print(df_list[i]['tissueID'].unique())

# Print total number of unique tissueID in all dataframes.
unique_tissueID = set()
for df in df_list:
    unique_tissueID.update(df['tissueID'].unique())
print(f"Total number of unique tissueID in all dataframes: {len(unique_tissueID)}")

Unique tissueID in dataframe 0:
['20201203_Laura_Thymus_2_1' '20201203_Laura_Thymus_2_2'
 '20201203_Laura_Thymus_2_3' '20201203_Laura_Thymus_2_4'
 '20201203_Laura_Thymus_2_5' '20201203_Laura_Thymus_2_6'
 '20201203_Laura_Thymus_2_7' '20201203_Laura_Thymus_2_8'
 '20201203_Laura_Thymus_2_9' '20201203_Laura_Thymus_2_10']
Unique tissueID in dataframe 1:
['20201203_Laura_Thymus_2_1' '20201203_Laura_Thymus_2_2'
 '20201203_Laura_Thymus_2_3' '20201203_Laura_Thymus_2_4'
 '20201203_Laura_Thymus_2_5' '20201203_Laura_Thymus_2_6'
 '20201203_Laura_Thymus_2_7' '20201203_Laura_Thymus_2_8'
 '20201203_Laura_Thymus_2_9' '20201203_Laura_Thymus_2_10']
Unique tissueID in dataframe 2:
['2022-06-01-THYMUS-ARCHITECTURE-T098_1'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_2'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_3'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_4'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_5'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_6'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_7'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_8'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_9'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_10']
Unique tissueID in dataframe 3:
['2022-06-01-THYMUS-ARCHITECTURE-T098_1'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_2'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_3'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_4'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_5'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_6'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_7'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_8'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_9'
 '2022-06-01-THYMUS-ARCHITECTURE-T098_10']
Unique tissueID in dataframe 4:
['20201203_Laura_Thymus_2_1' '20201203_Laura_Thymus_2_2'
 '20201203_Laura_Thymus_2_3' '20201203_Laura_Thymus_2_4'
 '20201203_Laura_Thymus_2_5' '20201203_Laura_Thymus_2_6'
 '20201203_Laura_Thymus_2_7' '20201203_Laura_Thymus_2_8'
 '20201203_Laura_Thymus_2_9' '20201203_Laura_Thymus_2_10']
Unique tissueID in dataframe 5:
['20220921-T096-Thymic-Arch-Stanford-Panel_1'
 '20220921-T096-Thymic-Arch-Stanford-Panel_2'
 '20220921-T096-Thymic-Arch-Stanford-Panel_3'
 '20220921-T096-Thymic-Arch-Stanford-Panel_4'
 '20220921-T096-Thymic-Arch-Stanford-Panel_5']
Unique tissueID in dataframe 6:
['20220915-T097-Thymic-Arch-Stanford-Panel_1'
 '20220915-T097-Thymic-Arch-Stanford-Panel_2'
 '20220915-T097-Thymic-Arch-Stanford-Panel_3'
 '20220915-T097-Thymic-Arch-Stanford-Panel_4'
 '20220915-T097-Thymic-Arch-Stanford-Panel_5'
 '20220915-T097-Thymic-Arch-Stanford-Panel_6'
 '20220915-T097-Thymic-Arch-Stanford-Panel_7']
Unique tissueID in dataframe 7:
['20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_1'
 '20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_2'
 '20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_3'
 '20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_4'
 '20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_5'
 '20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_6'
 '20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_7'
 '20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_8'
 '20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_9'
 '20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_10']
Total number of unique tissueID in all dataframes: 42

In [17]:
# Check if all dataframes have "x:x" and "y:y" columns.
for i in range(len(df_list)):
    if "x:x" not in df_list[i].columns or "y:y" not in df_list[i].columns:
        print(f"Dataframe {i} does not have x:x or y:y columns.")
    else:
        print(f"Dataframe {i} has x:x and y:y columns.")

Dataframe 0 has x:x and y:y columns.
Dataframe 1 has x:x and y:y columns.
Dataframe 2 has x:x and y:y columns.
Dataframe 3 has x:x and y:y columns.
Dataframe 4 has x:x and y:y columns.
Dataframe 5 has x:x and y:y columns.
Dataframe 6 has x:x and y:y columns.
Dataframe 7 has x:x and y:y columns.

In [18]:
# check if all dataframes have CelltypeName column
for i in range(len(df_list)):
    if "CelltypeName" not in df_list[i].columns:
        print(f"Dataframe {i} does not have CelltypeName column.")
    else:
        print(f"Dataframe {i} has CelltypeName column.")

Dataframe 0 has CelltypeName column.
Dataframe 1 has CelltypeName column.
Dataframe 2 has CelltypeName column.
Dataframe 3 has CelltypeName column.
Dataframe 4 has CelltypeName column.
Dataframe 5 has CelltypeName column.
Dataframe 6 has CelltypeName column.
Dataframe 7 has CelltypeName column.

In [60]:
# Iterate through all dataframes. For each dataframe, get tissueID, x:x, y:y, and CelltypeName columns. 
# For each unique value in tissueID, get the corresponding x:x, y:y, and CelltypeName values. Create a new dataframe with these values.
# Save the new dataframe to a csv file in the output data path. NAme the csv file as tissueID.csv.
for i in range(len(df_list)):
    # Print the name of the dataframe.
    filename = os.listdir(INPUT_DATA_PATH)[i].split('.')[0]
    print(f"Processing dataframe {i}: {filename}")
    df = df_list[i]
    tissueID = df['tissueID'].unique()
    for j in range(len(tissueID)):
        # print the unique tissueID
        print(f"Processing tissueID {tissueID[j]}")
        tissueID_df = df[df['tissueID'] == tissueID[j]]
        tissueID_df = tissueID_df[['x:x', 'y:y', 'CelltypeName']]
        # Rename columns to x, y, and Cell Type.
        tissueID_df.columns = ['x', 'y', 'Cell Type']
        # Replace space in file name with underscore.
        filename = filename.replace(" ", "_")
        # Save to csv file.
        tissueID_df.to_csv(os.path.join(OUTPUT_DATA_PATH, f"{filename}--{tissueID[j]}.csv"), index=False)

# Print the names of all files in output data path.
print("Files in output data path:")
pprint(os.listdir(OUTPUT_DATA_PATH))

Processing dataframe 0: MultiRun-CombinedData
Processing tissueID 20201203_Laura_Thymus_2_1
Processing tissueID 20201203_Laura_Thymus_2_2
Processing tissueID 20201203_Laura_Thymus_2_3
Processing tissueID 20201203_Laura_Thymus_2_4
Processing tissueID 20201203_Laura_Thymus_2_5
Processing tissueID 20201203_Laura_Thymus_2_6
Processing tissueID 20201203_Laura_Thymus_2_7
Processing tissueID 20201203_Laura_Thymus_2_8
Processing tissueID 20201203_Laura_Thymus_2_9
Processing tissueID 20201203_Laura_Thymus_2_10
Processing dataframe 1: MultiRun-CombinedDataT087
Processing tissueID 20201203_Laura_Thymus_2_1
Processing tissueID 20201203_Laura_Thymus_2_2
Processing tissueID 20201203_Laura_Thymus_2_3
Processing tissueID 20201203_Laura_Thymus_2_4
Processing tissueID 20201203_Laura_Thymus_2_5
Processing tissueID 20201203_Laura_Thymus_2_6
Processing tissueID 20201203_Laura_Thymus_2_7
Processing tissueID 20201203_Laura_Thymus_2_8
Processing tissueID 20201203_Laura_Thymus_2_9
Processing tissueID 20201203_Laura_Thymus_2_10
Processing dataframe 2: MultiRun-CombinedDataT098 2
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_1
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_2
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_3
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_4
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_5
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_6
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_7
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_8
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_9
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_10
Processing dataframe 3: MultiRun-CombinedDataT098
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_1
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_2
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_3
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_4
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_5
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_6
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_7
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_8
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_9
Processing tissueID 2022-06-01-THYMUS-ARCHITECTURE-T098_10
Processing dataframe 4: MultiRun-CombinedData 2
Processing tissueID 20201203_Laura_Thymus_2_1
Processing tissueID 20201203_Laura_Thymus_2_2
Processing tissueID 20201203_Laura_Thymus_2_3
Processing tissueID 20201203_Laura_Thymus_2_4
Processing tissueID 20201203_Laura_Thymus_2_5
Processing tissueID 20201203_Laura_Thymus_2_6
Processing tissueID 20201203_Laura_Thymus_2_7
Processing tissueID 20201203_Laura_Thymus_2_8
Processing tissueID 20201203_Laura_Thymus_2_9
Processing tissueID 20201203_Laura_Thymus_2_10
Processing dataframe 5: MultiRun-CombinedDataT096
Processing tissueID 20220921-T096-Thymic-Arch-Stanford-Panel_1
Processing tissueID 20220921-T096-Thymic-Arch-Stanford-Panel_2
Processing tissueID 20220921-T096-Thymic-Arch-Stanford-Panel_3
Processing tissueID 20220921-T096-Thymic-Arch-Stanford-Panel_4
Processing tissueID 20220921-T096-Thymic-Arch-Stanford-Panel_5
Processing dataframe 6: MultiRun-CombinedDataT097
Processing tissueID 20220915-T097-Thymic-Arch-Stanford-Panel_1
Processing tissueID 20220915-T097-Thymic-Arch-Stanford-Panel_2
Processing tissueID 20220915-T097-Thymic-Arch-Stanford-Panel_3
Processing tissueID 20220915-T097-Thymic-Arch-Stanford-Panel_4
Processing tissueID 20220915-T097-Thymic-Arch-Stanford-Panel_5
Processing tissueID 20220915-T097-Thymic-Arch-Stanford-Panel_6
Processing tissueID 20220915-T097-Thymic-Arch-Stanford-Panel_7
Processing dataframe 7: MultiRun-CombinedDataT100
Processing tissueID 20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_1
Processing tissueID 20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_2
Processing tissueID 20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_3
Processing tissueID 20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_4
Processing tissueID 20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_5
Processing tissueID 20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_6
Processing tissueID 20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_7
Processing tissueID 20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_8
Processing tissueID 20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_9
Processing tissueID 20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_10
Files in output data path:
['MultiRun-CombinedData--20201203_Laura_Thymus_2_1.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_2.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_3.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_4.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_5.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_6.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_7.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_8.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_9.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_10.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_1.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_2.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_3.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_4.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_5.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_6.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_7.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_8.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_9.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_10.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_5.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_6.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_7.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_8.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_9.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_5.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_6.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_7.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_8.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_9.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_1.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_2.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_3.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_4.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_5.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_6.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_7.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_8.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_9.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_10.csv',
 'MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_1.csv',
 'MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_2.csv',
 'MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_3.csv',
 'MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_4.csv',
 'MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_5.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_1.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_2.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_3.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_4.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_5.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_6.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_7.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_1.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_2.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_3.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_4.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_5.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_6.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_7.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_8.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_9.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_10.csv']

In [61]:
pprint(len(os.listdir(OUTPUT_DATA_PATH)))

72

In [ ]:
# copy output directory to "/u/yashjain/vitessce-files/cifar-data/peter-zandstra-data". Create the directory if it does not exist.
if not os.path.exists(CDN_PATH):
    os.makedirs(CDN_PATH)
# copy the output data path to the new directory
import shutil
shutil.copytree(OUTPUT_DATA_PATH, CDN_PATH, dirs_exist_ok=True)

'/u/yashjain/vitessce-files/cifar-data/peter-zandstra-data'

In [63]:
# list files in "/u/yashjain/vitessce-files"
print("Files in vitessce-files path:")
pprint(os.listdir("/u/yashjain/vitessce-files"))

Files in vitessce-files path:
['Gloria_internal',
 'vitessce-test-files',
 'lymphNode_RongFan',
 'vccf-data-cell-nodes',
 'LN-yale-vitessce',
 'cifar-data']

In [ ]:
# list files in "/u/yashjain/vitessce-files/peter-zandstra-data"
print("Files in vitessce-files path:")
pprint(os.listdir(CDN_PATH))

# Print the number of files in "/u/yashjain/vitessce-files/peter-zandstra-data"
print(f"Number of files in vitessce-files path: {len(os.listdir(CDN_PATH))}")

Files in vitessce-files path:
['MultiRun-CombinedData--20201203_Laura_Thymus_2_1.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_2.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_3.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_4.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_5.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_6.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_7.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_8.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_9.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_10.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_1.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_2.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_3.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_4.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_5.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_6.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_7.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_8.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_9.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_10.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_5.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_6.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_7.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_8.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_9.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_5.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_6.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_7.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_8.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_9.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_1.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_2.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_3.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_4.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_5.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_6.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_7.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_8.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_9.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_10.csv',
 'MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_1.csv',
 'MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_2.csv',
 'MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_3.csv',
 'MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_4.csv',
 'MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_5.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_1.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_2.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_3.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_4.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_5.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_6.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_7.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_1.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_2.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_3.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_4.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_5.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_6.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_7.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_8.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_9.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_10.csv']
Number of files in vitessce-files path: 72

In [65]:
# Upload files to cdn.
!aws s3 --profile hra-images sync --delete ~/vitessce-files/cifar-data/peter-zandstra-data/ s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/

delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData#20201203_Laura_Thymus_2_1.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData#20201203_Laura_Thymus_2_4.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData#20201203_Laura_Thymus_2_8.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData#20201203_Laura_Thymus_2_2.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData#20201203_Laura_Thymus_2_10.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData#20201203_Laura_Thymus_2_3.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData#20201203_Laura_Thymus_2_5.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData#20201203_Laura_Thymus_2_6.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData#20201203_Laura_Thymus_2_7.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData#20201203_Laura_Thymus_2_9.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_8.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_8.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087#20201203_Laura_Thymus_2_1.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_6.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_6.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_10.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_10.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_2.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_2.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_1.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_1.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_5.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_5.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_3.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_3.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087#20201203_Laura_Thymus_2_10.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_4.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_4.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_7.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_7.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_9.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedData--20201203_Laura_Thymus_2_9.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087#20201203_Laura_Thymus_2_3.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087#20201203_Laura_Thymus_2_2.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087#20201203_Laura_Thymus_2_5.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087#20201203_Laura_Thymus_2_4.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087#20201203_Laura_Thymus_2_8.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087#20201203_Laura_Thymus_2_9.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087#20201203_Laura_Thymus_2_7.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087#20201203_Laura_Thymus_2_6.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_6.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_6.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_10.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_10.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_3.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_3.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_8.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_8.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_5.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_5.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT096#20220921-T096-Thymic-Arch-Stanford-Panel_1.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_2.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_2.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_4.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_4.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT096#20220921-T096-Thymic-Arch-Stanford-Panel_2.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_9.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_9.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT096#20220921-T096-Thymic-Arch-Stanford-Panel_3.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT096#20220921-T096-Thymic-Arch-Stanford-Panel_4.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_7.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_7.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_1.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_1.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT096#20220921-T096-Thymic-Arch-Stanford-Panel_5.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097#20220915-T097-Thymic-Arch-Stanford-Panel_2.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097#20220915-T097-Thymic-Arch-Stanford-Panel_1.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097#20220915-T097-Thymic-Arch-Stanford-Panel_4.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097#20220915-T097-Thymic-Arch-Stanford-Panel_3.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097#20220915-T097-Thymic-Arch-Stanford-Panel_5.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097#20220915-T097-Thymic-Arch-Stanford-Panel_6.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097#20220915-T097-Thymic-Arch-Stanford-Panel_7.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_1.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_1.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_2.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_2.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_4.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_4.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_3.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_3.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_5.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_5.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098#2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098#2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098#2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_1.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_1.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098#2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_2.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_2.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098#2022-06-01-THYMUS-ARCHITECTURE-T098_5.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098#2022-06-01-THYMUS-ARCHITECTURE-T098_7.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098#2022-06-01-THYMUS-ARCHITECTURE-T098_6.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098#2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098#2022-06-01-THYMUS-ARCHITECTURE-T098_8.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_3.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_3.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098#2022-06-01-THYMUS-ARCHITECTURE-T098_9.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_5.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_5.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_7.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_7.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_6.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_6.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_4.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_4.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2#2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2#2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2#2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2#2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_5.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_5.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_7.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_7.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2#2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2#2022-06-01-THYMUS-ARCHITECTURE-T098_5.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2#2022-06-01-THYMUS-ARCHITECTURE-T098_6.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2#2022-06-01-THYMUS-ARCHITECTURE-T098_7.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2#2022-06-01-THYMUS-ARCHITECTURE-T098_8.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2#2022-06-01-THYMUS-ARCHITECTURE-T098_9.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_6.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_6.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_8.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_8.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_9.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_9.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT100#20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_2.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT100#20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_1.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT100#20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_10.csv
upload: ../vitessce-files/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv
delete: s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/MultiRun-CombinedDataT100#20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_3.csv

In [84]:
# List files in the s3 bucket.
!aws s3 --profile hra-images ls s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/

2025-04-16 14:38:21     946361 MultiRun-CombinedData--20201203_Laura_Thymus_2_1.csv
2025-04-16 14:38:21     995267 MultiRun-CombinedData--20201203_Laura_Thymus_2_10.csv
2025-04-16 14:38:21     996341 MultiRun-CombinedData--20201203_Laura_Thymus_2_2.csv
2025-04-16 14:38:21     996255 MultiRun-CombinedData--20201203_Laura_Thymus_2_3.csv
2025-04-16 14:38:21    1032009 MultiRun-CombinedData--20201203_Laura_Thymus_2_4.csv
2025-04-16 14:38:21    1044891 MultiRun-CombinedData--20201203_Laura_Thymus_2_5.csv
2025-04-16 14:38:21     917080 MultiRun-CombinedData--20201203_Laura_Thymus_2_6.csv
2025-04-16 14:38:21     930791 MultiRun-CombinedData--20201203_Laura_Thymus_2_7.csv
2025-04-16 14:38:21     995129 MultiRun-CombinedData--20201203_Laura_Thymus_2_8.csv
2025-04-16 14:38:21     987490 MultiRun-CombinedData--20201203_Laura_Thymus_2_9.csv
2025-04-16 14:38:22     768863 MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_1.csv
2025-04-16 14:38:22     752312 MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_10.csv
2025-04-16 14:38:22     731478 MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_2.csv
2025-04-16 14:38:22     791864 MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_3.csv
2025-04-16 14:38:22     736811 MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_4.csv
2025-04-16 14:38:22     736926 MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_5.csv
2025-04-16 14:38:22     711586 MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_6.csv
2025-04-16 14:38:22     673535 MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_7.csv
2025-04-16 14:38:22     700649 MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_8.csv
2025-04-16 14:38:22     779653 MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_9.csv
2025-04-16 14:38:22     602669 MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_1.csv
2025-04-16 14:38:22     747811 MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_2.csv
2025-04-16 14:38:22     736121 MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_3.csv
2025-04-16 14:38:22     660889 MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_4.csv
2025-04-16 14:38:22     706219 MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_5.csv
2025-04-16 14:38:22    2262445 MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_1.csv
2025-04-16 14:38:22    2447071 MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_2.csv
2025-04-16 14:38:22    2827100 MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_3.csv
2025-04-16 14:38:22    2549594 MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_4.csv
2025-04-16 14:38:22    2155262 MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_5.csv
2025-04-16 14:38:22    2537579 MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_6.csv
2025-04-16 14:38:22    2513793 MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_7.csv
2025-04-16 14:38:22    1261561 MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv
2025-04-16 14:38:22    1240794 MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv
2025-04-16 14:38:22    1286538 MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv
2025-04-16 14:38:22    1246050 MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv
2025-04-16 14:38:22    1315161 MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv
2025-04-16 14:38:22    1270519 MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_5.csv
2025-04-16 14:38:22    1301725 MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_6.csv
2025-04-16 14:38:22    1267356 MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_7.csv
2025-04-16 14:38:23    1270503 MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_8.csv
2025-04-16 14:38:23    1004473 MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_9.csv
2025-04-16 14:38:23    1261561 MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv
2025-04-16 14:38:23    1240794 MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv
2025-04-16 14:38:23    1286538 MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv
2025-04-16 14:38:23    1246050 MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv
2025-04-16 14:38:23    1315161 MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv
2025-04-16 14:38:23    1270519 MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_5.csv
2025-04-16 14:38:23    1301725 MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_6.csv
2025-04-16 14:38:23    1267356 MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_7.csv
2025-04-16 14:38:23    1270503 MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_8.csv
2025-04-16 14:38:23    1004473 MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_9.csv
2025-04-16 14:38:23      27299 MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_1.csv
2025-04-16 14:38:23     102806 MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_10.csv
2025-04-16 14:38:23      21006 MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_2.csv
2025-04-16 14:38:23     122547 MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_3.csv
2025-04-16 14:38:23     136165 MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_4.csv
2025-04-16 14:38:23      97918 MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_5.csv
2025-04-16 14:38:23     140807 MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_6.csv
2025-04-16 14:38:23     130448 MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_7.csv
2025-04-16 14:38:23     156556 MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_8.csv
2025-04-16 14:38:23     141965 MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_9.csv
2025-04-16 14:38:23     946361 MultiRun-CombinedData_2--20201203_Laura_Thymus_2_1.csv
2025-04-16 14:38:23     995267 MultiRun-CombinedData_2--20201203_Laura_Thymus_2_10.csv
2025-04-16 14:38:23     996341 MultiRun-CombinedData_2--20201203_Laura_Thymus_2_2.csv
2025-04-16 14:38:23     996255 MultiRun-CombinedData_2--20201203_Laura_Thymus_2_3.csv
2025-04-16 14:38:23    1032009 MultiRun-CombinedData_2--20201203_Laura_Thymus_2_4.csv
2025-04-16 14:38:23    1044891 MultiRun-CombinedData_2--20201203_Laura_Thymus_2_5.csv
2025-04-16 14:38:23     917080 MultiRun-CombinedData_2--20201203_Laura_Thymus_2_6.csv
2025-04-16 14:38:23     930791 MultiRun-CombinedData_2--20201203_Laura_Thymus_2_7.csv
2025-04-16 14:38:23     995129 MultiRun-CombinedData_2--20201203_Laura_Thymus_2_8.csv
2025-04-16 14:38:23     987490 MultiRun-CombinedData_2--20201203_Laura_Thymus_2_9.csv
2025-04-16 14:39:17       9784 __s3_files-cifar-zandstra.csv

In [67]:
# Visualize using Cell DIstance Exp
#Install and import external packages
# %pip install ipywidgets hra_jupyter_widgets

import os
import csv

import ipywidgets as widgets

# Import hra-jupyter-widgets. For documentation, please see https://github.com/x-atlas-consortia/hra-jupyter-widgets/blob/main/usage.ipynb
from hra_jupyter_widgets import CdeVisualization

In [68]:

# Next, let's define a function that turns a DataFrame into a node list that can then be passed into the CdeVisualization or NodeDistVis widget
def make_node_list(df:pd.DataFrame, is_3d:bool = False):
  """Turn a DataFrame into a list of dicts for passing them into a HRA widget

  Args:
      df (pd.DataFrame): A DataFrame with cells
  """
  
  # If the df does not have a z-axis column, let's add one and set all cells to 0
  if not is_3d:
    df.loc[:, ('z')] = 0
  
  node_list = [{'x': row['x'], 'y': row['y'], 'z': row['z'], 'Cell Type': row['Cell Type']}
                 for index, row in df.iterrows()]

  return node_list

In [69]:
# Read a random file from the output data path.
file = os.listdir(OUTPUT_DATA_PATH)[0]
df_nodes = pd.read_csv(os.path.join(OUTPUT_DATA_PATH, file))
node_list = make_node_list(df_nodes, False)
edge_list = [["Cell ID","Target ID", "X1", "Y1", "Z1", "X2", "Y2", "Z2"]] # this makes an empty edges list

In [ ]:
# Check if df_nodes has "ECs" or "Endothelial cells" in Cell Type column. Assign whichever exists to anchor_cell_type variable.
if "ECs" in df_nodes['Cell Type'].values:
    anchor_cell_type = "ECs"
elif "Endothelial cells" in df_nodes['Cell Type'].values:
    anchor_cell_type = "Endothelial cells"
else:
    anchor_cell_type = None

In [ ]:
# Finally, let's instantiate the CDEVisualization class with our node_list as parameter.
cde = CdeVisualization(
    node_target_selector=anchor_cell_type,
    max_edge_distance=200,
    nodes=node_list,
    node_target_key = "Cell Type",
)

# Display our new widget
display(cde)

CdeVisualization(age=None, color_map=None, color_map_key=None, color_map_value_key=None, creation_timestamp=No…

In [ ]:
# You can download files from https://cdn.humanatlas.io/image-store/cifar-data/peter-zandstra-data.

In [72]:
# List files in the s3 bucket. Save the filename in the output to a list.
!aws s3 --profile hra-images ls s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/ > s3_files-cifar-zandstra.txt

In [73]:
# Read a txt file and save the filenames in a list.
with open('s3_files-cifar-zandstra.txt', 'r') as f:
    lines = f.readlines()
    filenames = [line.split()[-1] for line in lines]

# Print the filenames.
pprint(filenames)

['MultiRun-CombinedData--20201203_Laura_Thymus_2_1.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_10.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_2.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_3.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_4.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_5.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_6.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_7.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_8.csv',
 'MultiRun-CombinedData--20201203_Laura_Thymus_2_9.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_1.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_10.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_2.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_3.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_4.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_5.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_6.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_7.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_8.csv',
 'MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_9.csv',
 'MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_1.csv',
 'MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_2.csv',
 'MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_3.csv',
 'MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_4.csv',
 'MultiRun-CombinedDataT096--20220921-T096-Thymic-Arch-Stanford-Panel_5.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_1.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_2.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_3.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_4.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_5.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_6.csv',
 'MultiRun-CombinedDataT097--20220915-T097-Thymic-Arch-Stanford-Panel_7.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_5.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_6.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_7.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_8.csv',
 'MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_9.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_5.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_6.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_7.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_8.csv',
 'MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_9.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_1.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_10.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_2.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_3.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_4.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_5.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_6.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_7.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_8.csv',
 'MultiRun-CombinedDataT100--20220928_LS_KS_T100_Thymic_Arch_Stanford_Panel_9.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_1.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_10.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_2.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_3.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_4.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_5.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_6.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_7.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_8.csv',
 'MultiRun-CombinedData_2--20201203_Laura_Thymus_2_9.csv']

In [74]:
len(filenames)

72

In [75]:
# Write the filenames to a csv file. Append https://cdn.humanatlas.io/image-store/cifar-data/peter-zandstra-data/ to each filename.
with open('s3_files-cifar-zandstra.csv', 'w') as f:
    writer = csv.writer(f)
    for filename in filenames:
        writer.writerow([f"https://cdn.humanatlas.io/image-store/cifar-data/peter-zandstra-data/{filename}"])

In [76]:

# Read the csv file and print the first few rows.
df = pd.read_csv('s3_files-cifar-zandstra.csv', header=None)
print(df.head())

                                                   0
0  https://cdn.humanatlas.io/image-store/cifar-da...
1  https://cdn.humanatlas.io/image-store/cifar-da...
2  https://cdn.humanatlas.io/image-store/cifar-da...
3  https://cdn.humanatlas.io/image-store/cifar-da...
4  https://cdn.humanatlas.io/image-store/cifar-da...

In [77]:
len(df)

72

In [ ]:
# copy the csv file to the output data path.
shutil.copy('s3_files-cifar-zandstra.csv', f"{CDN_PATH}/__s3_files-cifar-zandstra.csv")

'/u/yashjain/vitessce-files/cifar-data/peter-zandstra-data/__s3_files-cifar-zandstra.csv'

In [95]:
# Upload file to cdn.
!aws s3 --profile hra-images sync --delete ~/vitessce-files/cifar-data/peter-zandstra-data/ s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/

upload: ../vitessce-files/cifar-data/peter-zandstra-data/__s3_files-cifar-zandstra.csv to s3://cdn-humanatlas-io/image-store/cifar-data/peter-zandstra-data/__s3_files-cifar-zandstra.csv

In [80]:
#File at https://cdn.humanatlas.io/image-store/cifar-data/peter-zandstra-data/__s3_files-cifar-zandstra.csv

### Check cell type names in files.

In [92]:
# Read all files in the output data path. Check if "ECs" or "Endothelial cells" is in the Cell Type column for each file.
for filename in os.listdir(OUTPUT_DATA_PATH):
    df = pd.read_csv(os.path.join(OUTPUT_DATA_PATH, filename))
    if "ECs" in df['Cell Type'].unique() or "Endothelial cells" in df['Cell Type'].unique():
        # print(f"{filename} has ECs in Cell Type column.")
        continue
    else:
        print(f"{filename} does not have ECs in Cell Type column.")

In [91]:
# # Read all files in the output data path. Print unique cell types in each file.

for filename in os.listdir(OUTPUT_DATA_PATH):
    df = pd.read_csv(os.path.join(OUTPUT_DATA_PATH, filename))
    print(f"Unique cell types in {filename}: {df['Cell Type'].unique()}")
    # print(f"Number of unique cell types in {filename}: {len(df['Cell Type'].unique())}")

Unique cell types in MultiRun-CombinedData--20201203_Laura_Thymus_2_1.csv: ['DP cells' 'WGA+ cells' 'Class II+ DP cells' 'PD-L1+ CD3+ DP cells '
 'SP cells' 'ETPs' 'JAG1+ macrophages ' 'CD45RA+ SP cells' 'Macrophages'
 'ETPs (proliferating)' 'VCAM+ DP cells' 'IgM+ cells'
 'SATB1+ CD3+ DP cells' 'CD40+ APCs' 'Vascular smooth muscle cells'
 'TCRgd cells' 'JAG1+ VCAM+ macrophages' 'Myeloid cells' 'cTECs'
 'TCRgd cells (proliferating)' 'CCR7+ cells' 'CD274+ APCs' 'COL4+ mTECs'
 'APCs' 'mTECs' 'Fibroblasts' 'Pericytes' 'JAG1+ macrophages'
 'Endothelial cells' 'CD19+ Cytokeratin 5/8+ cells' 'CD3+ DP cells'
 'ICAM+ epithelial cells' 'JAG2+ mTECs' 'COL4+ cells' 'SATB1+ SP cells'
 'Dendritic cells']
Unique cell types in MultiRun-CombinedData--20201203_Laura_Thymus_2_2.csv: ['DP cells' 'WGA+ cells' 'SATB1+ CD3+ DP cells'
 'TCRgd cells (proliferating)' 'IgM+ cells' 'CD45RA+ SP cells'
 'CD40+ APCs' 'JAG1+ VCAM+ macrophages' 'Endothelial cells'
 'SATB1+ SP cells' 'CD19+ Cytokeratin 5/8+ cells' 'mTECs' 'COL4+ cells'
 'SP cells' 'ETPs' 'ETPs (proliferating)' 'cTECs' 'CCR7+ cells'
 'JAG1+ macrophages ' 'Fibroblasts' 'TCRgd cells' 'COL4+ mTECs'
 'Dendritic cells' 'PD-L1+ CD3+ DP cells ' 'JAG1+ macrophages'
 'VCAM+ DP cells' 'Pericytes' 'CD3+ DP cells' 'Myeloid cells'
 'Class II+ DP cells' 'Macrophages' 'JAG2+ mTECs' 'ICAM+ epithelial cells'
 'Vascular smooth muscle cells' 'CD274+ APCs' 'APCs']
Unique cell types in MultiRun-CombinedData--20201203_Laura_Thymus_2_3.csv: ['DP cells' 'JAG1+ VCAM+ macrophages' 'ETPs (proliferating)'
 'CD3+ DP cells' 'TCRgd cells' 'VCAM+ DP cells' 'Endothelial cells'
 'cTECs' 'CD40+ APCs' 'Macrophages' 'TCRgd cells (proliferating)' 'ETPs'
 'SATB1+ CD3+ DP cells' 'WGA+ cells' 'Class II+ DP cells'
 'JAG1+ macrophages ' 'JAG1+ macrophages' 'CD274+ APCs' 'COL4+ mTECs'
 'SP cells' 'CD45RA+ SP cells' 'Pericytes' 'CCR7+ cells' 'mTECs'
 'PD-L1+ CD3+ DP cells ' 'APCs' 'ICAM+ epithelial cells' 'SATB1+ SP cells'
 'Vascular smooth muscle cells' 'Myeloid cells'
 'CD19+ Cytokeratin 5/8+ cells' 'IgM+ cells' 'COL4+ cells' 'JAG2+ mTECs'
 'Dendritic cells' 'Fibroblasts']
Unique cell types in MultiRun-CombinedData--20201203_Laura_Thymus_2_4.csv: ['DP cells' 'TCRgd cells' 'COL4+ cells' 'CD19+ Cytokeratin 5/8+ cells'
 'APCs' 'SATB1+ CD3+ DP cells' 'WGA+ cells' 'SP cells'
 'JAG1+ VCAM+ macrophages' 'cTECs' 'TCRgd cells (proliferating)'
 'Macrophages' 'ETPs (proliferating)' 'CD274+ APCs' 'VCAM+ DP cells'
 'Endothelial cells' 'Pericytes' 'CD45RA+ SP cells' 'CCR7+ cells'
 'Dendritic cells' 'CD40+ APCs' 'PD-L1+ CD3+ DP cells '
 'ICAM+ epithelial cells' 'SATB1+ SP cells' 'COL4+ mTECs' 'JAG2+ mTECs'
 'Fibroblasts' 'CD3+ DP cells' 'Class II+ DP cells' 'JAG1+ macrophages'
 'JAG1+ macrophages ' 'Vascular smooth muscle cells' 'Myeloid cells'
 'IgM+ cells' 'ETPs' 'mTECs']
Unique cell types in MultiRun-CombinedData--20201203_Laura_Thymus_2_5.csv: ['DP cells' 'TCRgd cells (proliferating)' 'Endothelial cells'
 'Dendritic cells' 'VCAM+ DP cells' 'TCRgd cells' 'SP cells'
 'SATB1+ CD3+ DP cells' 'CD19+ Cytokeratin 5/8+ cells'
 'PD-L1+ CD3+ DP cells ' 'mTECs' 'IgM+ cells' 'ETPs' 'JAG2+ mTECs'
 'COL4+ mTECs' 'Class II+ DP cells' 'ICAM+ epithelial cells' 'CCR7+ cells'
 'Macrophages' 'CD274+ APCs' 'CD45RA+ SP cells' 'JAG1+ macrophages '
 'JAG1+ VCAM+ macrophages' 'APCs' 'ETPs (proliferating)' 'WGA+ cells'
 'Myeloid cells' 'CD40+ APCs' 'COL4+ cells' 'Pericytes' 'cTECs'
 'SATB1+ SP cells' 'CD3+ DP cells' 'Vascular smooth muscle cells'
 'JAG1+ macrophages' 'Fibroblasts']
Unique cell types in MultiRun-CombinedData--20201203_Laura_Thymus_2_6.csv: ['DP cells' 'WGA+ cells' 'Endothelial cells' 'ICAM+ epithelial cells'
 'CD3+ DP cells' 'SATB1+ CD3+ DP cells' 'CD45RA+ SP cells' 'SP cells'
 'Class II+ DP cells' 'SATB1+ SP cells' 'CD274+ APCs' 'VCAM+ DP cells'
 'IgM+ cells' 'ETPs (proliferating)' 'Vascular smooth muscle cells'
 'CD19+ Cytokeratin 5/8+ cells' 'mTECs' 'cTECs' 'Macrophages'
 'JAG1+ macrophages' 'CCR7+ cells' 'COL4+ cells' 'JAG1+ macrophages '
 'Pericytes' 'TCRgd cells (proliferating)' 'APCs' 'PD-L1+ CD3+ DP cells '
 'COL4+ mTECs' 'Dendritic cells' 'ETPs' 'JAG1+ VCAM+ macrophages'
 'TCRgd cells' 'Myeloid cells' 'JAG2+ mTECs' 'Fibroblasts' 'CD40+ APCs']
Unique cell types in MultiRun-CombinedData--20201203_Laura_Thymus_2_7.csv: ['cTECs' 'TCRgd cells (proliferating)' 'CD19+ Cytokeratin 5/8+ cells'
 'COL4+ cells' 'Myeloid cells' 'ICAM+ epithelial cells'
 'SATB1+ CD3+ DP cells' 'DP cells' 'CD3+ DP cells' 'SP cells'
 'CCR7+ cells' 'VCAM+ DP cells' 'TCRgd cells' 'Dendritic cells'
 'JAG2+ mTECs' 'CD45RA+ SP cells' 'CD274+ APCs' 'IgM+ cells' 'WGA+ cells'
 'Macrophages' 'JAG1+ VCAM+ macrophages' 'Endothelial cells'
 'ETPs (proliferating)' 'PD-L1+ CD3+ DP cells ' 'SATB1+ SP cells' 'mTECs'
 'JAG1+ macrophages' 'APCs' 'JAG1+ macrophages ' 'ETPs'
 'Class II+ DP cells' 'Vascular smooth muscle cells' 'CD40+ APCs'
 'COL4+ mTECs' 'Pericytes' 'Fibroblasts']
Unique cell types in MultiRun-CombinedData--20201203_Laura_Thymus_2_8.csv: ['DP cells' 'ICAM+ epithelial cells' 'CD45RA+ SP cells'
 'Vascular smooth muscle cells' 'JAG1+ VCAM+ macrophages' 'CD274+ APCs'
 'APCs' 'PD-L1+ CD3+ DP cells ' 'COL4+ cells' 'Myeloid cells'
 'Endothelial cells' 'CD19+ Cytokeratin 5/8+ cells' 'Dendritic cells'
 'SATB1+ CD3+ DP cells' 'ETPs (proliferating)' 'TCRgd cells' 'cTECs'
 'mTECs' 'CCR7+ cells' 'CD3+ DP cells' 'SP cells' 'IgM+ cells'
 'VCAM+ DP cells' 'WGA+ cells' 'Class II+ DP cells'
 'TCRgd cells (proliferating)' 'Pericytes' 'ETPs' 'Macrophages'
 'JAG1+ macrophages ' 'COL4+ mTECs' 'JAG2+ mTECs' 'SATB1+ SP cells'
 'JAG1+ macrophages' 'CD40+ APCs' 'Fibroblasts']
Unique cell types in MultiRun-CombinedData--20201203_Laura_Thymus_2_9.csv: ['CCR7+ cells' 'Myeloid cells' 'DP cells' 'cTECs'
 'JAG1+ VCAM+ macrophages' 'ETPs (proliferating)'
 'TCRgd cells (proliferating)' 'PD-L1+ CD3+ DP cells ' 'Endothelial cells'
 'VCAM+ DP cells' 'COL4+ mTECs' 'SATB1+ CD3+ DP cells' 'Pericytes' 'ETPs'
 'APCs' 'Class II+ DP cells' 'CD19+ Cytokeratin 5/8+ cells' 'WGA+ cells'
 'Macrophages' 'SP cells' 'CD40+ APCs' 'Vascular smooth muscle cells'
 'JAG1+ macrophages ' 'Dendritic cells' 'mTECs' 'SATB1+ SP cells'
 'CD45RA+ SP cells' 'CD3+ DP cells' 'COL4+ cells' 'TCRgd cells'
 'ICAM+ epithelial cells' 'JAG1+ macrophages' 'Fibroblasts' 'CD274+ APCs'
 'IgM+ cells' 'JAG2+ mTECs']
Unique cell types in MultiRun-CombinedData--20201203_Laura_Thymus_2_10.csv: ['Class II+ DP cells' 'APCs' 'DP cells' 'SP cells' 'SATB1+ CD3+ DP cells'
 'ETPs (proliferating)' 'Pericytes' 'SATB1+ SP cells' 'Macrophages'
 'JAG1+ VCAM+ macrophages' 'TCRgd cells' 'JAG1+ macrophages'
 'PD-L1+ CD3+ DP cells ' 'cTECs' 'Dendritic cells' 'VCAM+ DP cells'
 'WGA+ cells' 'Endothelial cells' 'Vascular smooth muscle cells'
 'COL4+ cells' 'TCRgd cells (proliferating)' 'CD45RA+ SP cells'
 'IgM+ cells' 'CD3+ DP cells' 'JAG2+ mTECs' 'JAG1+ macrophages '
 'CCR7+ cells' 'CD274+ APCs' 'mTECs' 'ICAM+ epithelial cells' 'CD40+ APCs'
 'Myeloid cells' 'CD19+ Cytokeratin 5/8+ cells' 'ETPs' 'COL4+ mTECs'
 'Fibroblasts']
Unique cell types in MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_1.csv: ['DPs' 'cTECs' 'mTECs' 'Class II+ DPs' 'Fibs' 'VSMCs' 'Auto' 'CD3+ DPs'
 'JAG1+ VCAM+ DCs' 'DCs' 'IgM+' 'SPs' 'JAG1+ DCs' 'ECs' 'APCs'
 'Activated mTECs']
Unique cell types in MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_2.csv: ['CD3+ DPs' 'DPs' 'JAG1+ VCAM+ DCs' 'IgM+' 'DCs' 'SPs' 'mTECs' 'ECs'
 'Fibs' 'cTECs' 'APCs' 'VSMCs' 'Activated mTECs' 'Auto' 'JAG1+ DCs'
 'Class II+ DPs']
Unique cell types in MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_3.csv: ['DPs' 'JAG1+ DCs' 'Activated mTECs' 'mTECs' 'JAG1+ VCAM+ DCs' 'ECs'
 'cTECs' 'SPs' 'DCs' 'Auto' 'Fibs' 'Class II+ DPs' 'CD3+ DPs' 'APCs'
 'VSMCs' 'IgM+']
Unique cell types in MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_4.csv: ['DPs' 'DCs' 'Auto' 'Fibs' 'APCs' 'cTECs' 'SPs' 'ECs' 'JAG1+ DCs'
 'CD3+ DPs' 'mTECs' 'JAG1+ VCAM+ DCs' 'VSMCs' 'Class II+ DPs' 'IgM+'
 'Activated mTECs']
Unique cell types in MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_5.csv: ['DPs' 'ECs' 'APCs' 'cTECs' 'SPs' 'CD3+ DPs' 'Fibs' 'mTECs' 'IgM+' 'DCs'
 'Class II+ DPs' 'VSMCs' 'JAG1+ DCs' 'JAG1+ VCAM+ DCs' 'Auto'
 'Activated mTECs']
Unique cell types in MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_6.csv: ['DPs' 'Fibs' 'ECs' 'APCs' 'CD3+ DPs' 'SPs' 'Class II+ DPs' 'mTECs' 'DCs'
 'JAG1+ DCs' 'IgM+' 'cTECs' 'VSMCs' 'JAG1+ VCAM+ DCs' 'Auto'
 'Activated mTECs']
Unique cell types in MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_7.csv: ['DPs' 'cTECs' 'Fibs' 'SPs' 'APCs' 'ECs' 'DCs' 'Auto' 'mTECs' 'CD3+ DPs'
 'JAG1+ VCAM+ DCs' 'VSMCs' 'Class II+ DPs' 'JAG1+ DCs' 'IgM+'
 'Activated mTECs']
Unique cell types in MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_8.csv: ['DPs' 'DCs' 'VSMCs' 'JAG1+ VCAM+ DCs' 'mTECs' 'Fibs' 'Activated mTECs'
 'cTECs' 'CD3+ DPs' 'APCs' 'ECs' 'Class II+ DPs' 'Auto' 'SPs' 'IgM+'
 'JAG1+ DCs']
Unique cell types in MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_9.csv: ['DPs' 'DCs' 'cTECs' 'CD3+ DPs' 'JAG1+ VCAM+ DCs' 'ECs' 'SPs' 'APCs'
 'JAG1+ DCs' 'Fibs' 'mTECs' 'Class II+ DPs' 'Activated mTECs' 'VSMCs'
 'Auto' 'IgM+']
Unique cell types in MultiRun-CombinedDataT087--20201203_Laura_Thymus_2_10.csv: ['DPs' 'SPs' 'ECs' 'DCs' 'cTECs' 'Class II+ DPs' 'JAG1+ DCs' 'CD3+ DPs'
 'mTECs' 'APCs' 'VSMCs' 'Fibs' 'JAG1+ VCAM+ DCs' 'IgM+' 'Auto'
 'Activated mTECs']
Unique cell types in MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv: ['Class II+ DPs' 'Auto' 'SPs' 'JAG1+ DCs' 'DPs' 'cTECs' 'APCs' 'ECs'
 'JAG1+ VCAM+ DCs' 'CD3+ DPs' 'mTECs' 'VSMCs' 'Fibs' 'Activated mTECs'
 'DCs' 'IgM+']
Unique cell types in MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv: ['Auto' 'JAG1+ VCAM+ DCs' 'ECs' 'SPs' 'APCs' 'mTECs' 'VSMCs' 'IgM+'
 'CD3+ DPs' 'cTECs' 'DPs' 'Fibs' 'DCs' 'Activated mTECs' 'JAG1+ DCs'
 'Class II+ DPs']
Unique cell types in MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv: ['VSMCs' 'Auto' 'JAG1+ VCAM+ DCs' 'ECs' 'DPs' 'Fibs' 'mTECs' 'cTECs'
 'IgM+' 'Activated mTECs' 'CD3+ DPs' 'SPs' 'JAG1+ DCs' 'APCs' 'DCs'
 'Class II+ DPs']
Unique cell types in MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv: ['Auto' 'SPs' 'DPs' 'cTECs' 'DCs' 'ECs' 'JAG1+ VCAM+ DCs'
 'Activated mTECs' 'APCs' 'VSMCs' 'CD3+ DPs' 'mTECs' 'JAG1+ DCs' 'IgM+'
 'Fibs' 'Class II+ DPs']
Unique cell types in MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_5.csv: ['APCs' 'Auto' 'Activated mTECs' 'VSMCs' 'CD3+ DPs' 'ECs'
 'JAG1+ VCAM+ DCs' 'Fibs' 'IgM+' 'mTECs' 'DCs' 'JAG1+ DCs' 'cTECs' 'DPs'
 'SPs' 'Class II+ DPs']
Unique cell types in MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_6.csv: ['Auto' 'Fibs' 'mTECs' 'SPs' 'CD3+ DPs' 'Activated mTECs' 'DPs'
 'JAG1+ VCAM+ DCs' 'VSMCs' 'ECs' 'cTECs' 'APCs' 'JAG1+ DCs' 'IgM+'
 'Class II+ DPs' 'DCs']
Unique cell types in MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_7.csv: ['APCs' 'mTECs' 'Auto' 'cTECs' 'CD3+ DPs' 'Fibs' 'JAG1+ VCAM+ DCs' 'DPs'
 'SPs' 'ECs' 'DCs' 'VSMCs' 'JAG1+ DCs' 'Class II+ DPs' 'IgM+'
 'Activated mTECs']
Unique cell types in MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_8.csv: ['Auto' 'APCs' 'CD3+ DPs' 'cTECs' 'JAG1+ VCAM+ DCs' 'ECs' 'Fibs' 'SPs'
 'DPs' 'mTECs' 'VSMCs' 'Class II+ DPs' 'JAG1+ DCs' 'Activated mTECs'
 'IgM+' 'DCs']
Unique cell types in MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_9.csv: ['IgM+' 'APCs' 'mTECs' 'Auto' 'JAG1+ VCAM+ DCs' 'ECs' 'VSMCs' 'JAG1+ DCs'
 'cTECs' 'Fibs' 'Activated mTECs' 'SPs' 'DPs' 'CD3+ DPs' 'DCs'
 'Class II+ DPs']
Unique cell types in MultiRun-CombinedDataT098_2--2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv: ['Auto' 'DPs' 'Activated mTECs' 'CD3+ DPs' 'Fibs' 'APCs' 'DCs' 'mTECs'
 'VSMCs' 'cTECs' 'ECs' 'JAG1+ VCAM+ DCs' 'JAG1+ DCs' 'SPs' 'Class II+ DPs'
 'IgM+']
Unique cell types in MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_1.csv: ['Class II+ DPs' 'Auto' 'SPs' 'JAG1+ DCs' 'DPs' 'cTECs' 'APCs' 'ECs'
 'JAG1+ VCAM+ DCs' 'CD3+ DPs' 'mTECs' 'VSMCs' 'Fibs' 'Activated mTECs'
 'DCs' 'IgM+']
Unique cell types in MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_2.csv: ['Auto' 'JAG1+ VCAM+ DCs' 'ECs' 'SPs' 'APCs' 'mTECs' 'VSMCs' 'IgM+'
 'CD3+ DPs' 'cTECs' 'DPs' 'Fibs' 'DCs' 'Activated mTECs' 'JAG1+ DCs'
 'Class II+ DPs']
Unique cell types in MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_3.csv: ['VSMCs' 'Auto' 'JAG1+ VCAM+ DCs' 'ECs' 'DPs' 'Fibs' 'mTECs' 'cTECs'
 'IgM+' 'Activated mTECs' 'CD3+ DPs' 'SPs' 'JAG1+ DCs' 'APCs' 'DCs'
 'Class II+ DPs']
Unique cell types in MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_4.csv: ['Auto' 'SPs' 'DPs' 'cTECs' 'DCs' 'ECs' 'JAG1+ VCAM+ DCs'
 'Activated mTECs' 'APCs' 'VSMCs' 'CD3+ DPs' 'mTECs' 'JAG1+ DCs' 'IgM+'
 'Fibs' 'Class II+ DPs']
Unique cell types in MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_5.csv: ['APCs' 'Auto' 'Activated mTECs' 'VSMCs' 'CD3+ DPs' 'ECs'
 'JAG1+ VCAM+ DCs' 'Fibs' 'IgM+' 'mTECs' 'DCs' 'JAG1+ DCs' 'cTECs' 'DPs'
 'SPs' 'Class II+ DPs']
Unique cell types in MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_6.csv: ['Auto' 'Fibs' 'mTECs' 'SPs' 'CD3+ DPs' 'Activated mTECs' 'DPs'
 'JAG1+ VCAM+ DCs' 'VSMCs' 'ECs' 'cTECs' 'APCs' 'JAG1+ DCs' 'IgM+'
 'Class II+ DPs' 'DCs']
Unique cell types in MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_7.csv: ['APCs' 'mTECs' 'Auto' 'cTECs' 'CD3+ DPs' 'Fibs' 'JAG1+ VCAM+ DCs' 'DPs'
 'SPs' 'ECs' 'DCs' 'VSMCs' 'JAG1+ DCs' 'Class II+ DPs' 'IgM+'
 'Activated mTECs']
Unique cell types in MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_8.csv: ['Auto' 'APCs' 'CD3+ DPs' 'cTECs' 'JAG1+ VCAM+ DCs' 'ECs' 'Fibs' 'SPs'
 'DPs' 'mTECs' 'VSMCs' 'Class II+ DPs' 'JAG1+ DCs' 'Activated mTECs'
 'IgM+' 'DCs']
Unique cell types in MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_9.csv: ['IgM+' 'APCs' 'mTECs' 'Auto' 'JAG1+ VCAM+ DCs' 'ECs' 'VSMCs' 'JAG1+ DCs'
 'cTECs' 'Fibs' 'Activated mTECs' 'SPs' 'DPs' 'CD3+ DPs' 'DCs'
 'Class II+ DPs']
Unique cell types in MultiRun-CombinedDataT098--2022-06-01-THYMUS-ARCHITECTURE-T098_10.csv: ['Auto' 'DPs' 'Activated mTECs' 'CD3+ DPs' 'Fibs' 'APCs' 'DCs' 'mTECs'
 'VSMCs' 'cTECs' 'ECs' 'JAG1+ VCAM+ DCs' 'JAG1+ DCs' 'SPs' 'Class II+ DPs'
 'IgM+']
Unique cell types in MultiRun-CombinedData_2--20201203_Laura_Thymus_2_1.csv: ['DP cells' 'WGA+ cells' 'Class II+ DP cells' 'PD-L1+ CD3+ DP cells '
 'SP cells' 'ETPs' 'JAG1+ macrophages ' 'CD45RA+ SP cells' 'Macrophages'
 'ETPs (proliferating)' 'VCAM+ DP cells' 'IgM+ cells'
 'SATB1+ CD3+ DP cells' 'CD40+ APCs' 'Vascular smooth muscle cells'
 'TCRgd cells' 'JAG1+ VCAM+ macrophages' 'Myeloid cells' 'cTECs'
 'TCRgd cells (proliferating)' 'CCR7+ cells' 'CD274+ APCs' 'COL4+ mTECs'
 'APCs' 'mTECs' 'Fibroblasts' 'Pericytes' 'JAG1+ macrophages'
 'Endothelial cells' 'CD19+ Cytokeratin 5/8+ cells' 'CD3+ DP cells'
 'ICAM+ epithelial cells' 'JAG2+ mTECs' 'COL4+ cells' 'SATB1+ SP cells'
 'Dendritic cells']
Unique cell types in MultiRun-CombinedData_2--20201203_Laura_Thymus_2_2.csv: ['DP cells' 'WGA+ cells' 'SATB1+ CD3+ DP cells'
 'TCRgd cells (proliferating)' 'IgM+ cells' 'CD45RA+ SP cells'
 'CD40+ APCs' 'JAG1+ VCAM+ macrophages' 'Endothelial cells'
 'SATB1+ SP cells' 'CD19+ Cytokeratin 5/8+ cells' 'mTECs' 'COL4+ cells'
 'SP cells' 'ETPs' 'ETPs (proliferating)' 'cTECs' 'CCR7+ cells'
 'JAG1+ macrophages ' 'Fibroblasts' 'TCRgd cells' 'COL4+ mTECs'
 'Dendritic cells' 'PD-L1+ CD3+ DP cells ' 'JAG1+ macrophages'
 'VCAM+ DP cells' 'Pericytes' 'CD3+ DP cells' 'Myeloid cells'
 'Class II+ DP cells' 'Macrophages' 'JAG2+ mTECs' 'ICAM+ epithelial cells'
 'Vascular smooth muscle cells' 'CD274+ APCs' 'APCs']
Unique cell types in MultiRun-CombinedData_2--20201203_Laura_Thymus_2_3.csv: ['DP cells' 'JAG1+ VCAM+ macrophages' 'ETPs (proliferating)'
 'CD3+ DP cells' 'TCRgd cells' 'VCAM+ DP cells' 'Endothelial cells'
 'cTECs' 'CD40+ APCs' 'Macrophages' 'TCRgd cells (proliferating)' 'ETPs'
 'SATB1+ CD3+ DP cells' 'WGA+ cells' 'Class II+ DP cells'
 'JAG1+ macrophages ' 'JAG1+ macrophages' 'CD274+ APCs' 'COL4+ mTECs'
 'SP cells' 'CD45RA+ SP cells' 'Pericytes' 'CCR7+ cells' 'mTECs'
 'PD-L1+ CD3+ DP cells ' 'APCs' 'ICAM+ epithelial cells' 'SATB1+ SP cells'
 'Vascular smooth muscle cells' 'Myeloid cells'
 'CD19+ Cytokeratin 5/8+ cells' 'IgM+ cells' 'COL4+ cells' 'JAG2+ mTECs'
 'Dendritic cells' 'Fibroblasts']
Unique cell types in MultiRun-CombinedData_2--20201203_Laura_Thymus_2_4.csv: ['DP cells' 'TCRgd cells' 'COL4+ cells' 'CD19+ Cytokeratin 5/8+ cells'
 'APCs' 'SATB1+ CD3+ DP cells' 'WGA+ cells' 'SP cells'
 'JAG1+ VCAM+ macrophages' 'cTECs' 'TCRgd cells (proliferating)'
 'Macrophages' 'ETPs (proliferating)' 'CD274+ APCs' 'VCAM+ DP cells'
 'Endothelial cells' 'Pericytes' 'CD45RA+ SP cells' 'CCR7+ cells'
 'Dendritic cells' 'CD40+ APCs' 'PD-L1+ CD3+ DP cells '
 'ICAM+ epithelial cells' 'SATB1+ SP cells' 'COL4+ mTECs' 'JAG2+ mTECs'
 'Fibroblasts' 'CD3+ DP cells' 'Class II+ DP cells' 'JAG1+ macrophages'
 'JAG1+ macrophages ' 'Vascular smooth muscle cells' 'Myeloid cells'
 'IgM+ cells' 'ETPs' 'mTECs']
Unique cell types in MultiRun-CombinedData_2--20201203_Laura_Thymus_2_5.csv: ['DP cells' 'TCRgd cells (proliferating)' 'Endothelial cells'
 'Dendritic cells' 'VCAM+ DP cells' 'TCRgd cells' 'SP cells'
 'SATB1+ CD3+ DP cells' 'CD19+ Cytokeratin 5/8+ cells'
 'PD-L1+ CD3+ DP cells ' 'mTECs' 'IgM+ cells' 'ETPs' 'JAG2+ mTECs'
 'COL4+ mTECs' 'Class II+ DP cells' 'ICAM+ epithelial cells' 'CCR7+ cells'
 'Macrophages' 'CD274+ APCs' 'CD45RA+ SP cells' 'JAG1+ macrophages '
 'JAG1+ VCAM+ macrophages' 'APCs' 'ETPs (proliferating)' 'WGA+ cells'
 'Myeloid cells' 'CD40+ APCs' 'COL4+ cells' 'Pericytes' 'cTECs'
 'SATB1+ SP cells' 'CD3+ DP cells' 'Vascular smooth muscle cells'
 'JAG1+ macrophages' 'Fibroblasts']
Unique cell types in MultiRun-CombinedData_2--20201203_Laura_Thymus_2_6.csv: ['DP cells' 'WGA+ cells' 'Endothelial cells' 'ICAM+ epithelial cells'
 'CD3+ DP cells' 'SATB1+ CD3+ DP cells' 'CD45RA+ SP cells' 'SP cells'
 'Class II+ DP cells' 'SATB1+ SP cells' 'CD274+ APCs' 'VCAM+ DP cells'
 'IgM+ cells' 'ETPs (proliferating)' 'Vascular smooth muscle cells'
 'CD19+ Cytokeratin 5/8+ cells' 'mTECs' 'cTECs' 'Macrophages'
 'JAG1+ macrophages' 'CCR7+ cells' 'COL4+ cells' 'JAG1+ macrophages '
 'Pericytes' 'TCRgd cells (proliferating)' 'APCs' 'PD-L1+ CD3+ DP cells '
 'COL4+ mTECs' 'Dendritic cells' 'ETPs' 'JAG1+ VCAM+ macrophages'
 'TCRgd cells' 'Myeloid cells' 'JAG2+ mTECs' 'Fibroblasts' 'CD40+ APCs']
Unique cell types in MultiRun-CombinedData_2--20201203_Laura_Thymus_2_7.csv: ['cTECs' 'TCRgd cells (proliferating)' 'CD19+ Cytokeratin 5/8+ cells'
 'COL4+ cells' 'Myeloid cells' 'ICAM+ epithelial cells'
 'SATB1+ CD3+ DP cells' 'DP cells' 'CD3+ DP cells' 'SP cells'
 'CCR7+ cells' 'VCAM+ DP cells' 'TCRgd cells' 'Dendritic cells'
 'JAG2+ mTECs' 'CD45RA+ SP cells' 'CD274+ APCs' 'IgM+ cells' 'WGA+ cells'
 'Macrophages' 'JAG1+ VCAM+ macrophages' 'Endothelial cells'
 'ETPs (proliferating)' 'PD-L1+ CD3+ DP cells ' 'SATB1+ SP cells' 'mTECs'
 'JAG1+ macrophages' 'APCs' 'JAG1+ macrophages ' 'ETPs'
 'Class II+ DP cells' 'Vascular smooth muscle cells' 'CD40+ APCs'
 'COL4+ mTECs' 'Pericytes' 'Fibroblasts']
Unique cell types in MultiRun-CombinedData_2--20201203_Laura_Thymus_2_8.csv: ['DP cells' 'ICAM+ epithelial cells' 'CD45RA+ SP cells'
 'Vascular smooth muscle cells' 'JAG1+ VCAM+ macrophages' 'CD274+ APCs'
 'APCs' 'PD-L1+ CD3+ DP cells ' 'COL4+ cells' 'Myeloid cells'
 'Endothelial cells' 'CD19+ Cytokeratin 5/8+ cells' 'Dendritic cells'
 'SATB1+ CD3+ DP cells' 'ETPs (proliferating)' 'TCRgd cells' 'cTECs'
 'mTECs' 'CCR7+ cells' 'CD3+ DP cells' 'SP cells' 'IgM+ cells'
 'VCAM+ DP cells' 'WGA+ cells' 'Class II+ DP cells'
 'TCRgd cells (proliferating)' 'Pericytes' 'ETPs' 'Macrophages'
 'JAG1+ macrophages ' 'COL4+ mTECs' 'JAG2+ mTECs' 'SATB1+ SP cells'
 'JAG1+ macrophages' 'CD40+ APCs' 'Fibroblasts']

In [ ]:
# Read all files in output data and compute total rows.
total_rows = 0
for filename in os.listdir(OUTPUT_DATA_PATH):
    df = pd.read_csv(os.path.join(OUTPUT_DATA_PATH, filename))
    total_rows += len(df)
print(f"Total cells in all files: {total_rows}")

Total rows in all files: 4490977